### ISSUE TITLE
Unable to run ios-server-0.6.0.jar file with build- [Exception in thread "main" org.openqa.selenium.WebDriverExceptio]

### ISSUE THREAD

**Issue by satheesh-na** [ios-driver/ios-driver#113]
Hi,

Currently am investigating ios-driver for testing ios application. I am unable to complete the SetUp process, Facing issues below.

I have tried to execute jar file along with build like java -jar ios-server-0.6.0.jar -aut ~/Documents/build/buildName.app -port 4444

but here am facing issue regarding WebDriver exception. I have included the log file below, let me know, how to resolve this issue?. 

Exception in thread "main" org.openqa.selenium.WebDriverException: execution failed. Exit code =1 , command was : [xcodebuild, -showsdks]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.6.0_45'
Driver info: driver.version: unknown
    at org.uiautomation.ios.utils.Command.executeAndWait(Command.java:61)
    at org.uiautomation.ios.utils.ClassicCommands.getInstalledSDKs(ClassicCommands.java:107)
    at org.uiautomation.ios.utils.ClassicCommands.getDefaultSDK(ClassicCommands.java:113)
    at org.uiautomation.ios.server.HostInfo.<init>(HostInfo.java:45)
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:54)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:115)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:88)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:61)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:65)

**Comment by darraghgrace** [comment]
Hi, 

Do you have xcode installed, including xcode command line tools? See http://ios-driver.github.io/ios-driver/setup.html#sysreqs

In a terminal window run the command
xcodebuild -showsdks

You should see a list of OS X sdks.

**Comment by freynaud** [comment]
closing as this is explained on the setup pge of the doc now.
