### ISSUE TITLE
Session not created exception while running the scripts on iPad simulator

### ISSUE THREAD

**Issue by jayanthvijayakumar** [ios-driver/ios-driver#116]
Here the code that i gave for ipad simulator

DesiredCapabilities cap = IOSCapabilities.ipad("InternationalMountains");

For iphone simulator
        DesiredCapabilities cap = IOSCapabilities.iphone("InternationalMountains");

the above code is working fine as it launches the iphone simulator and run the scripts

The following error displayed for ipad simulator in the eclipse console,
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: {simulator=true, timeHack=false, variation=Regular, locale=en_GB, CFBundleName=InternationalMountains, device=ipad, language=en} not found on server.

**Comment by SThiyagi** [comment]
Hi,

I am also getting the below error in eclipse….Please help me in fixing this…

Code
        DesiredCapabilities cap = IOSCapabilities.iphone("TrueVUEMobileiOS", "888.0.0");
        cap.setCapability("language", "en");
        // start the application
        driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub/"), cap);

startup command...
java -jar ios-server-0.6.5-jar-with-dependencies.jar -aut ~/Desktop/iOSAutomation/App/TrueVUEMobileiOS.app/ -host hostname -port 4444 -simulators

FAILED CONFIGURATION: @BeforeClass setUp
org.openqa.selenium.SessionNotCreatedException: {simulator=true, timeHack=false, variation=Regular, locale=en_GB, CFBundleName=TrueVUEMobileiOS, device=iphone, CFBundleVersion=888.0.0, language=en} not found on server.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: driver.version: unknown
Command duration or timeout: 316 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:191)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:111)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:129)
at tyco.com.ios.commonlibraries.Sample.setUp(Sample.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:617)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
at org.testng.SuiteRunner.run(SuiteRunner.java:240)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
at org.testng.TestNG.run(TestNG.java:1057)
at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by freynaud** [comment]
what is the output of your http://localhost:4444/wd/hub/status

**Comment by asabhijitshelar** [comment]
Hi,

Any updates. I am also getting same error
