### ISSUE TITLE
Project not getting compiled via maven pom.xml in eclipse

### ISSUE THREAD

**Issue by PavithraNavaneeth** [ios-driver/ios-driver#117]
When I try to execute my pom.xml it is throwing the following exception:
Fatal error compiling invalid target release: 1.7 invalid target release: 
 1.7
Note: My project properties is to set to use jdk 1.7.
Also my mvn -version is showing below:
Apache Maven 3.0.3 (r1075438; 2011-02-28 23:01:09+0530)
Maven home: /usr/share/maven
Java version: 1.7.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_25.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.7.4", arch: "x86_64", family: "mac"

Here is my pom.xml file content:

```
<repositories>
    <repository>
        <id>ios-server</id>
        <url>http://repo1.maven.org/maven2/org/uiautomation/ios-server/</url>
    </repository>
    <repository>
        <id>ios-grid</id>
        <url>http://repo1.maven.org/maven2/org/org/uiautomation/ios-grid/</url>
    </repository>
    <repository>
        <id>testng</id>
        <url>http://repo1.maven.org/maven2/org/testng/testng/</url>
    </repository>
    <repository>
        <id>jxl</id>
        <url>http://repo1.maven.org/maven2/net/sourceforge/jexcelapi/jxl/
        </url>
    </repository>
    <repository>
        <id>mvn assembly plugin</id>
        <url>http://mvnrepository.com/artifact/org.apache.maven.plugins/maven-assembly-plugin</url>
    </repository>
    <repository>
        <id>reportng rep</id>
        <name>clojure jars</name>
        <url>http://clojars.org/repo</url>
    </repository>
</repositories>


<dependencies>
     <dependency> 
        <groupId>org.mortbay.jetty</groupId> 
        <artifactId>jetty-runner</artifactId> 
        <version>7.4.4.v20110707</version> 
        <type>jar</type> 
        <scope>compile</scope> 
    </dependency> 

    <dependency>
    <groupId>org.apache.servicemix.bundles</groupId>
    <artifactId>org.apache.servicemix.bundles.jasper</artifactId>
    <version>6.0.14_4</version>
</dependency>

    <dependency>
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>6.0.1</version>
    </dependency>

    <dependency>
        <groupId>org.uiautomation</groupId>
        <artifactId>ios-server</artifactId>
        <version>0.6.2</version>
        <exclusions>
            <exclusion>
            <groupId>libimobiledevice-java</groupId>
            <artifactId>libimobiledevice-java</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.uiautomation</groupId>
        <artifactId>ios-grid</artifactId>
        <version>0.6.2</version>
    </dependency>

    <dependency>
        <groupId>net.sourceforge.jexcelapi</groupId>
        <artifactId>jxl</artifactId>
        <version>2.6.12</version>
    </dependency>
    <dependency>
        <groupId>log4j</groupId>
        <artifactId>log4j</artifactId>
        <version>1.2.16</version>
    </dependency>
    <dependency>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>2.2.1</version>
    </dependency>
    <dependency>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.1</version>
          <type>maven-plugin</type>
    </dependency>
    <dependency>
        <groupId>org.uncommons</groupId>
        <artifactId>reportng</artifactId>
        <version>1.1.3</version>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <artifactId>maven-clean-plugin</artifactId>
            <version>2.4.1</version>
            <configuration>
                <failOnError>false</failOnError>
                <filesets>                      
                    <fileset>
                        <directory>test-output</directory>
                        <includes>
                            <include>**/*</include>
                        </includes>
                        <followSymlinks>false</followSymlinks>
                    </fileset>
                </filesets>
            </configuration>
        </plugin>
        <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.1</version>
            <configuration>
                <source>1.7</source>
                <target>1.7</target>
            </configuration>
        </plugin>
        <plugin>
            <artifactId>maven-assembly-plugin</artifactId>
            <version>2.2.1</version>
            <configuration>
                <!-- <descriptors>
                    <descriptor>src/main/assembly/assembly_descriptor.xml</descriptor>
                </descriptors> -->
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-scm-plugin</artifactId>
            <version>1.5</version>
            <configuration>
                <!-- change to your username appropriately -->
                <username>sivae7</username> 
                <checkoutDirectory>./webmail_auto_checkout_and_build
                </checkoutDirectory>
                <goals>assembly:assembly</goals>
                <connectionType>developerConnection</connectionType>
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.10</version>

            <!-- Skip the normal tests, we'll run them in the integration-test phase -->
            <configuration>                 
                <skip>false</skip>
                <argLine>-Xmx1024m</argLine>
            </configuration>
        </plugin>
    </plugins>
</build>
```

Note: when I try to run mvn clean install in my command line it runs fine and no error is thrown. In my maven classpath container i could see all jars downloaded , but still in pom fatal error compiling target 1.7 is displayed.

When I run my actual test, it is launching the simulator and performing the test, but none of the clicks are working (no error is thrown for click). I am not sure whether this compilation issue is to do something with this click problem?

Started safari using below lines:
DesiredCapabilities safari = IOSCapabilities.ipad("Safari");
driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), safari);

Kindly help out!!

**Comment by PavithraNavaneeth** [comment]
Sorry, now I could resolve the fatal compilation error and pom.xml is compiled successfully.
But still click is not working.

Here is the error:
21:23:547 WARNING EventFactory.createEvent  TODO
Exception in thread "DefaultMessageHandler-165" org.openqa.selenium.WebDriverException: Error creating an event generated by the webview:{"method":"DOM.childNodeInserted","params":{"node":{"childNodeCount":0,"localName":"iframe","nodeId":194,"nodeValue":"","nodeName":"IFRAME","attributes":["frameborder","0","style","border: 0px; vertical-align: bottom; position: absolute; left: 1px; top: 1px; height: 1px; width: 1px; visibility: hidden; ","src","javascript:\"\""],"nodeType":1},"parentNodeId":159,"previousNodeId":193}}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.wkrdp.events.EventFactory.createEvent(EventFactory.java:33)
    at org.uiautomation.ios.context.BaseWebInspector.onMessage(BaseWebInspector.java:545)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.process(DefaultMessageHandler.java:76)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.access$000(DefaultMessageHandler.java:31)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler$1.run(DefaultMessageHandler.java:64)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.uiautomation.ios.wkrdp.events.EventFactory.createObject(EventFactory.java:45)
    at org.uiautomation.ios.wkrdp.events.EventFactory.createEvent(EventFactory.java:29)
    ... 4 more
Caused by: org.json.JSONException: JSONObject["contentDocument"] not found.
    at org.json.JSONObject.get(JSONObject.java:499)
    at org.json.JSONObject.getJSONObject(JSONObject.java:593)
    at org.uiautomation.ios.wkrdp.events.inserted.ChildIframeInserted.<init>(ChildIframeInserted.java:59)
    ... 10 more

**Comment by PavithraNavaneeth** [comment]
Closing the issue since the initial problem is resolved.
