### ISSUE TITLE
WindowHandles count is not decreased after window is self-closed in simulator.

### ISSUE THREAD

**Issue by zalivakp** [ios-driver/ios-driver#119]
My web application has integration with Facebook authorization.

Test steps:
1. Get WindowHandles.Count (returns 2: Web_1, Native)
2. Click login with Facebook (login window opens, WindowHandles.Count returns 3: Web_1, Web_2, Native)
3. Fill credentials and click login button (Facebook login window closed)
Expected:  WindowHandles.Count should return 2 handles
But was: 3 

That's not synchronization issue. Handles count remains the same till the end of test.

Environment:
Selenium version: 2.34.0 (C# bindings)
ios-driver version: 0.6.2
iPhone Simulator: 6.1

**Comment by freynaud** [comment]
problem somewhere here  + check driver.close()
https://github.com/ios-driver/ios-driver/blob/dev/server/src/main/java/org/uiautomation/ios/wkrdp/WebKitNotificationListener.java#L137

**Comment by zalivakp** [comment]
I've tried driver.close() to check if handles count changes. But found new problem.

## Here's part of my code:

```
private const string UrlPattern = "https://m.facebook";

var menu =  UserBar.OpenAuthMenu();
var countBefore = _driver.WindowHandles.Count;
//Opens new window
menu.FbSignInBtn.Click();

_driver.WaitUntil(p => p.WindowHandles.Count > windowsCount, 20, "3-d Party window didn't open after click.", 3000);
var countAfter = _driver.WindowHandles.Count;

//Switch to window with specific url
foreach (var window in _driver.WindowHandles)
{
    _driver.SwitchTo().Window(window);
    if (_driver.Url.Contains(UrlPattern))
            break;
}

_driver.Close();//throws null exception
_driver.SwitchTo().DefaultContent();
```

## Stack Trace:

System.NullReferenceException : Object reference not set to an instance of an object

at OpenQA.Selenium.RemoteWebDriver.UnpackAndThrowOnError (OpenQA.Selenium.Remote.Response errorResponse)
at OpenQA.Selenium.RemoteWebDriver.Execute (System.String driverCommandToExecute, System.Collections.Generic.Dictionary`2 parameters)
at OpenQA.Selenium.RemoteWebDriver.Close()
at UI.Mobile.Tests.MobileAuthManager.ThirdPartyLogin(System.Action, Int32 windowsCount, Syste.String UrlPattern)
...

## ios-server output:

org.openqa.selenium.WebDriverException: Error processing response.cannot find command for DELETE, /session/11bcce49-7993-4528-a390-9c4bc4896e14/window
...
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
...
at org.uiautomation.ios.communication.WebDriverLikeCommand.getCommand(WebDriverLikeCommand.java:308)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getGenericCommand(WebDriverLikeRequest.java:115)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getVariableValue(WebDriverLikeRequest.java:119)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getSession(WebDriverLikeRequest.java:132)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:150)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)

**Comment by cavaIV** [comment]
Hey!

I've got the same error.

Environment
C#
iOS-driver 0.6.5
Selenium server 2.39

Log
53:48:356 WARNING IOSServlet.getResponse  0ms.  
org.openqa.selenium.WebDriverException: Error processing response.cannot find command for DELETE, /ses
sion/
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_25'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:121)
    at org.uiautomation.ios.server.servlet.IOSServlet.doDelete(IOSServlet.java:69)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:724)
Caused by: org.openqa.selenium.WebDriverException: cannot find command for DELETE, /session/
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.communication.WebDriverLikeCommand.getCommand(WebDriverLikeCommand.java:311)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getGenericCommand(WebDriverLikeRequest.java:115)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getVariableValue(WebDriverLikeRequest.java:119)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getSession(WebDriverLikeRequest.java:132)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:150)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    ... 24 more
