### ISSUE TITLE
Exceptions while authorizing rights

### ISSUE THREAD

**Issue by mohangaradi** [ios-driver/ios-driver#140]
Version of ios-driver: 0.6.1 and 0.6.3

Description: There are exceptions while the iOS app starts executing:

5:43:456 WARNING DefaultCommandListener.stderr  Failed to authorize rights (0x20) with status: -60007.
15:43:458 WARNING DefaultCommandListener.stderr  Failed to authorize rights (0x20) with status: -60007.
15:43:462 WARNING DefaultCommandListener.stderr  2013-09-04 19:15:43.458 instruments[2118:707] Failed to connect to local pid watcher service: (os/kern) failure
15:43:476 WARNING DefaultCommandListener.stderr  Failed to authorize rights (0x20) with status: -60007.
15:49:918 WARNING IOSServlet.getResponse  24079ms.  POST     /session
15:49:956 WARNING IOSServlet.getResponse  1ms.  GET  /session/:sessionId
org.json.JSONException: JSONObject["translation"] not found.
    at org.json.JSONObject.get(JSONObject.java:499)
    at org.json.JSONObject.getBoolean(JSONObject.java:515)
    at org.uiautomation.ios.server.command.uiautomation.LogElementTreeNHandler.<init>(LogElementTreeNHandler.java:54)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.uiautomation.ios.server.CommandMapping.createHandler(CommandMapping.java:277)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:142)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:46)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:724)
15:50:317 WARNING IOSServlet.getResponse  6ms.  
org.openqa.selenium.WebDriverException: Error processing response.bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:121)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:46)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:724)
Caused by: org.openqa.selenium.WebDriverException: bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:164)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    ... 24 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.uiautomation.ios.server.CommandMapping.createHandler(CommandMapping.java:277)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:142)
    ... 25 more
Caused by: org.openqa.selenium.WebDriverException: wrong params
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.command.uiautomation.LogElementTreeNHandler.<init>(LogElementTreeNHandler.java:67)
    ... 31 more
Caused by: org.json.JSONException: JSONObject["attachScreenshot"] not found.
    at org.json.JSONObject.get(JSONObject.java:499)
    at org.json.JSONObject.getBoolean(JSONObject.java:515)
    at org.uiautomation.ios.server.command.uiautomation.LogElementTreeNHandler.<init>(LogElementTreeNHandler.java:63)
    ... 31 more
15:55:508 WARNING IOSServlet.getResponse  30ms. POST     /session/:sessionId/element
15:58:035 WARNING IOSServlet.getResponse  2513ms.   GET  /session/:sessionId/screenshot
15:58:792 WARNING IOSServlet.getResponse  389ms.    GET  /session/:sessionId/screenshot
15:59:069 WARNING IOSServlet.getResponse  101ms.    DELETE   /session/:sessionId

**Comment by freynaud** [comment]
i assume you're trying to remote launch the server. Have you read :
http://stackoverflow.com/questions/11369449/uiautomation-failed-to-authorize-rights-with-status-60007

which seems to be the same thing. Instruments needs special rights to run

**Comment by mohangaradi** [comment]
Yeah that's right..I made the changes as needed. The latter part of the errors with JSONObject is because of using a RemoteIOSDriver instead of a RemoteWebDriver which is still an issue. For now I am using RemoteWebDriver to resolve the issue...Thanks.
