### ISSUE TITLE
Error running ios-driver tests with selenium

### ISSUE THREAD

**Issue by cavaIV** [ios-driver/ios-driver#143]
Hey guys!

I'm running ios-server-0.6.3-jar-with-dependecies.jar on a VM (OSX 10.8.4) and want to execute my C# tests with the simulator.
I'm using Java 7 Update 25.

I exactly followed the setup (http://ios-driver.github.io/ios-driver/setup.html) but when I execute the jar - file it displays some errors:

WARNING AppleLanguage.create null isn't recogniced.Please file a bug on github. You won't be able to start the app in that language.

I start it with the following command:
java -jar ~/Path/to/my/jar/ios-server-0.6.3-jar-with-dependencies.jar -simulator -port 4444

When I try to start my tests MBUnit displays the following error:

Failures
Execute
System.InvalidOperationException: error starting the session:cannot configure simulator
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown (33)
HResult: -2146233079
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) in c:\Projects\WebDriver\trunk\dotnet\src\WebDriver\Remote\RemoteWebDriver.cs:line 1053
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in c:\Projects\WebDriver\trunk\dotnet\src\WebDriver\Remote\RemoteWebDriver.cs:line 846
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) in c:\Projects\WebDriver\trunk\dotnet\src\WebDriver\Remote\RemoteWebDriver.cs:line 814
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) in c:\Projects\WebDriver\trunk\dotnet\src\WebDriver\Remote\RemoteWebDriver.cs:line 89
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities) in c:\Projects\WebDriver\trunk\dotnet\src\WebDriver\Remote\RemoteWebDriver.cs:line 108
   at WebAppRegression.Core.Factories.BrowserFactory.IPhone() in c:\Projekte\QA\WebAppRegression\WebAppV2\WebAppRegression\Core\Factories\BrowserFactory.cs:line 53
   at WebAppRegression.Core.Factories.BrowserFactory.GetBrowser() in c:\Projekte\QA\WebAppRegression\WebAppV2\WebAppRegression\Core\Factories\BrowserFactory.cs:line 44
   at WebAppRegression.Core.PageObject..ctor(String url, Jurisdiction jurisdiction) in c:\Projekte\QA\WebAppRegression\WebAppV2\WebAppRegression\Core\PageObject.cs:line 76

I initialise my webdrive like this:
IWebDriver driver = new RemoteWebDriver(new Uri("http://IP:4444/wd/hub"), DesiredCapabilities.IPhone());

The funny thing is when I start a test the ios-driver doesn't open a simulator but when I start a simulator before executing a test the ios-driver closes the simulator.

**Comment by cavaIV** [comment]
Fixed it
DesiredCapabilities capabilities = DesiredCapabilities.IPhone();
capabilities.SetCapability("language", "en");
IWebDriver driver = new RemoteWebDriver(new Uri("http://hub:port/wd/hub"), capabilities);

capabilities.SetCapability("language", "en");
solved it
