### ISSUE TITLE
java.lang.UnsupportedClassVersionError: 

### ISSUE THREAD

**Issue by davyeng** [ios-driver/ios-driver#146]
I'm having a setup problem with the latest jar ios-server-0.6.3-jar-with-dependencies.jar 

Any clue how to resolve this?

dave$ java -jar ios-server-0.6.3-jar-with-dependencies.jar -aut InternationalMountains.app -port 4444
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/uiautomation/ios/server/IOSServer : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by EliseLebeau** [comment]
You need Java 1.7?

**Comment by nicegraham** [comment]
yeah, you need java 1.7
