### ISSUE TITLE
Not able to register a node on grid hub using ios-server-0.6.3-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by vikram1711** [ios-driver/ios-driver#148]
I am trying to register a node on one of my grid hub.
My grid hub is on one of my windows box.
I am using below command to start the hub as mentioned on http://ios-driver.github.io/ios-driver/scale.html

java -cp ios-server-0.6.3-jar-with-dependencies.jar;selenium-server-standalone-2.33.0.jar org.openqa.grid.selenium.GridLauncher -role hub

and to register a node I am running below command-

java -jar ios-server-0.6.3-jar-with-dependencies.jar -hub http://IP:44444/grid/register -proxy org.uiautomation.ios.grid..IOSRemoteProxy -host IP -port 8088

I see below exception on my MAC-

07:17:908 INFO ApplicationStore.<init>  App archive folder:/Users/kvikram/ios_server/applications
07:17:924 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): false
Inspector: http://0.0.0.0:8088/inspector/
tests can access the server at http://0.0.0.0:8088/wd/hub
server status: http://0.0.0.0:8088/wd/hub/status
Connected devices: http://0.0.0.0:8088/wd/hub/devices/all
Applications: http://0.0.0.0:8088/wd/hub/applications/all
Capabilities: http://0.0.0.0:8088/wd/hub/capabilities/all
Monitoring '/Users/kvikram/ios_server/applications' for new applications
Archived apps /Users/kvikram/ios_server/applications
## Applications :

2013-09-11 21:07:18.278:INFO::jetty-7.x.y-SNAPSHOT
2013-09-11 21:07:18.427:INFO::Started SelectChannelConnector@0.0.0.0:8088
Exception in thread "Thread-3" org.openqa.selenium.WebDriverException: Error sending the registration request.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.grid.RegistrationRequest.registerToHub(RegistrationRequest.java:118)
    at org.uiautomation.ios.server.grid.SelfRegisteringRemote.registerToHub(SelfRegisteringRemote.java:94)
    at org.uiautomation.ios.server.grid.SelfRegisteringRemote.access$000(SelfRegisteringRemote.java:34)
    at org.uiautomation.ios.server.grid.SelfRegisteringRemote$1.run(SelfRegisteringRemote.java:70)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.RuntimeException: Error sending the registration request.
    at org.uiautomation.ios.server.grid.RegistrationRequest.registerToHub(RegistrationRequest.java:115)
    ... 4 more

And below exception on my grid console on windows box-

Sep 11, 2013 9:07:19 PM org.openqa.grid.internal.BaseRemoteProxy getNewInstance
SEVERE: org.uiautomation.ios.grid.IOSRemoteProxy
java.lang.ClassNotFoundException: org.uiautomation.ios.grid.IOSRemoteProxy
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:400)
        at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:87)
        at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.seleniumhq.jetty7.servlet.ServletHolder.handle(ServletHolder.java:565)
        at org.seleniumhq.jetty7.servlet.ServletHandler.doHandle(ServletHandler.java:479)
        at org.seleniumhq.jetty7.server.session.SessionHandler.doHandle(SessionHandler.java:225)
        at org.seleniumhq.jetty7.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.seleniumhq.jetty7.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.seleniumhq.jetty7.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.seleniumhq.jetty7.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.seleniumhq.jetty7.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.seleniumhq.jetty7.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.seleniumhq.jetty7.server.Server.handle(Server.java:349)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
        at org.seleniumhq.jetty7.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:47)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
        at org.seleniumhq.jetty7.http.HttpParser.parseNext(HttpParser.java:857)
        at org.seleniumhq.jetty7.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.seleniumhq.jetty7.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:66)
        at org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:254)
        at org.seleniumhq.jetty7.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Unknown Source)
2013-09-11 21:07:19.264:WARN:osjs.ServletHandler:/grid/register
java.security.InvalidParameterException: Error: org.uiautomation.ios.grid.IOSRemoteProxy
        at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:419)
        at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:87)
        at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.seleniumhq.jetty7.servlet.ServletHolder.handle(ServletHolder.java:565)
        at org.seleniumhq.jetty7.servlet.ServletHandler.doHandle(ServletHandler.java:479)
        at org.seleniumhq.jetty7.server.session.SessionHandler.doHandle(SessionHandler.java:225)
        at org.seleniumhq.jetty7.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.seleniumhq.jetty7.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.seleniumhq.jetty7.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.seleniumhq.jetty7.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.seleniumhq.jetty7.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.seleniumhq.jetty7.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.seleniumhq.jetty7.server.Server.handle(Server.java:349)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
        at org.seleniumhq.jetty7.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:47)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
        at org.seleniumhq.jetty7.http.HttpParser.parseNext(HttpParser.java:857)
        at org.seleniumhq.jetty7.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.seleniumhq.jetty7.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:66)
        at org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:254)
        at org.seleniumhq.jetty7.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Unknown Source)

I am having Xcode version 5.0 on my MAC.

Thanks,
Vikram

**Comment by rkolla** [comment]
I am also getting same problem. how to solve this issue in MAC system?

**Comment by nicegraham** [comment]
Use the latest release

**Comment by vikram1711** [comment]
The latest version available to download is 0.6.3 and I am getting this
problem with the same version.

Thanks,
Vikram

**Comment by nicegraham** [comment]
The latest version is 0.6.5. It's on the releases page in github and on
maven.

**Comment by shashidhargsg** [comment]
I am trying to register a node on one of my grid hub in Win 7

java -cp ios-grid-0.6.6-SNAPSHOT.jar;selenium-server-standalone-2.42.2.jar org.openqa.grid.selenium.GridLauncher -role hub

and to register a node in MAC I am running below command-

java -jar ios-server-0.6.6-jar-with-dependencies.jar -hub http://IP:4444/grid/register -proxy org.uiautomation.ios.grid.IOSRemoteProxy -host IP -port 5555 -beta

I see below exception on my MAC-
Exception in thread "Thread-15" org.openqa.selenium.WebDriverException: Error sending the registration request.

I checked the network firewall its fine

I am using a real device

Please let me know what could be the issue

**Comment by alfetch** [comment]
I also have the exact same problem.. Getting this when trying to register with the following command on the HUB: 

java -jar ios-server-standalone-0.6.6-SNAPSHOT-standalone.jar -hub http://127.0.0.1:4444/grid/register -proxy org.uiautomation.ios.grid.IOSRemoteProxy -host 127.0.0.1 -port 5556

Error: 

51:17:669 INFO StoppableRegisteringRemote$1.run  Starting auto register thread. Will try to register every 5000 ms.
51:17:669 INFO StoppableRegisteringRemote.registerToHub  Registering the node to hub :http://127.0.0.1:4444/grid/register
51:17:724 INFO StoppableRegisteringRemote$1.run  couldn't register this node : Error sending the registration request.

Anyone can help.. Im running on MAC os system... Please

**Comment by Sudhakathi** [comment]
Has anyone found a solution to this? I am running into same problem
Here's what I am doing to start the hub
java -cp ios-grid-plugin-0.6.6-SNAPSHOT.jar:selenium-server-standalone.jar org.openqa.grid.selenium.GridLauncher -role hub

registering node:java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -hub http://10.129.11.144:4444/grid/register -proxy org.uiautomation.ios.grid.IOSRemoteProxy -host 10.129.11.144 -port 5555

Any help is appreciated!!!

**Comment by Ishiro** [comment]
I have the same problem with the 0.6.6-SNAPSHOT versions downloaded from the website.

Has anyone found a fix?

Could it be related to the Java version I use?

On the hub side:
```
$ java -version
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```

Probably not related but on the node side:
```
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by arun290636** [comment]
i am also getting the same error. has anyone found a solution for this?

**Comment by Nesaganesh** [comment]
Any updates on this, I am also facing the same issue.

## HUB

java -cp ios-grid-0.6.6-SNAPSHOT.jar:selenium-server-standalone-2.45.0.jar \org.openqa.grid.selenium.GridLauncher -role hub

## NODE

java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar \ -hub http://192.168.57.120:4444/grid/register \ -proxy org.uiautomation.ios.grid.IOSRemoteProxy \ -host 192.168.57.120 -port 5555

## Error in the hub

ERROR - org.uiautomation.ios.grid.IOSRemoteProxy
java.lang.ClassNotFoundException: org.uiautomation.ios.grid.IOSRemoteProxy
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:260)
    at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:419)
    at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:86)

**Comment by dsuckau** [comment]
I have the same problem on Mac OSX:

```
39:35:264 INFO StoppableRegisteringRemote.registerToHub  Registering the node to hub :http://xxx.local:4444/grid/register
39:35:772 INFO StoppableRegisteringRemote$1.run  couldn't register this node : Error sending the registration request.
```

**Comment by medisetty1129** [comment]
Hi dsuckau

were you able to resolve it ?
