### ISSUE TITLE
Shows blank when I open the inspector url 

### ISSUE THREAD

**Issue by swapnalibhansali** [ios-driver/ios-driver#15]
Here is the exception : 

10:38:231 WARNING IOSSimulatorManager.restoreExiledSDKs  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs doesn't exist.Cannot move folders from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs Make sure the rights are correct (chmod -R +rw ... )
11:59:600 WARNING IOSSimulatorManager.restoreExiledSDKs  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs doesn't exist.Cannot move folders from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs Make sure the rights are correct (chmod -R +rw ... )
java.lang.NullPointerException
    at org.uiautomation.ios.inspector.controllers.SessionGuesserController.canHandle(SessionGuesserController.java:43)
    at org.uiautomation.ios.inspector.IDEServlet.getController(IDEServlet.java:106)
    at org.uiautomation.ios.inspector.IDEServlet.doGet(IDEServlet.java:94)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:722)
13:17:082 WARNING IDEServlet.doGet  null

**Comment by nicegraham** [comment]
has ios-driver opened an application on the simulator? Have you paused the script run, inspector won't work if the test script is still running.

You can ignore the exiled sdk warning unless you're trying to run against an older SDK than your most recently installed one.

**Comment by swapnalibhansali** [comment]
Yes I have. Ran it in debug mode and paused the script and then looked at it. 
The observation I have for now is - 
I created the UI automation build using iphone 6.0 target. 
But when the app is launching its showing me simulator 6.1 in the app status on localhost from browser. 
Is the path different for the app for different simulators ?

**Comment by swapnalibhansali** [comment]
Is there any way for me to tell which simulator it has to open ? 
Its opening 6.1 always.

**Comment by nicegraham** [comment]
it will always open the latest version [6.1] unless the exiled SDKs folder
is available:
http://ios-driver.github.io/ios-driver/faq.html

Then it will be able to shelve the 6.1 sdk and run with an older one [6.0
in your case].

The first thing would be to try that though I don't know if it's the root
of your problem.

mkdir /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs

sudo chmod -R +rw /Applications/Xcode.app/Contents/Developer/Platforms/
iPhoneSimulator.platform/Developer/exiledSDKs

**Comment by swapnalibhansali** [comment]
i added the folder , created a UI automation build with 6.1 tried to execute it in debug mode. 
One more question is - It installs a new build everytime it runs or does it use the same build installed on the simulator ? 

same exception : 

at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:54)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:86)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:131)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:82)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:722)

**Comment by swapnalibhansali** [comment]
I deleted the folder Library/Developer/Xcode/DerivedData/Bizzby-dahgyqiunbzrnahilpofniadttpg/Build/Products/ ... 
Created the build again. 
This time I coudnt get the debug-iphonesimulator directory. 
It just has release directory - 
/Release-iphonesimulator/applications

Is that some error ?

**Comment by nicegraham** [comment]
it should create the folder assuming you have done the profile for
automation option. Are you copying the .app file to a different location?

**Comment by swapnalibhansali** [comment]
yes I am copying to documents folder.

**Comment by nicegraham** [comment]
is inspector still throwing an error for you or has that been resolved by building in 6.1?

**Comment by swapnalibhansali** [comment]
I guess I cant reach the point where its on the screen.
I put a break point after creating the driver object. But its not reaching
that breakpoint at all.
Its crashing before that itself with uiautomation session error

**Comment by nicegraham** [comment]
ok, can you give us the output of http://localhost:5555/wd/hub/status and http://localhost:5555/wd/capabilities/all?

**Comment by swapnalibhansali** [comment]
status output : 
https://gist.github.com/nicegraham/5372731

**Comment by swapnalibhansali** [comment]
HTTP ERROR: 404

Problem accessing /wd/capabilities/all. Reason:

```
Not Found
```

**Comment by nicegraham** [comment]
ouch. That's not normal - it doesn't look like the server is running correctly at all. 

What parameters are you using to launch ios-driver? 
What output do you see in the console when it launches?

**Comment by swapnalibhansali** [comment]
Command : 

java -jar ~/Documents/BizzyIOSAutomation/iosSeverSetup/ios-server-0.6.0.jar -aut ~/Documents/IOSBuilds/Bizzby.app -port 4444

Output  : 

02:30:969 INFO ApplicationStore.<init>  App archive folder:/Users/swapnalibhansali/Library/Developer/Xcode/DerivedData/Bizzby-dahgyqiunbzrnahilpofniadttpg/Build/Products/Release-iphonesimulator/applications
02:31:040 WARNING AppleLocale.findBestLocale  zh_Hans isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
02:32:260 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/swapnalibhansali/Library/Developer/Xcode/DerivedData/Bizzby-dahgyqiunbzrnahilpofniadttpg/Build/Products/Release-iphonesimulator/applications' for new applications
using xcode install : /Applications/Xcode.app
using IOS version 6.1
Archived apps /Users/swapnalibhansali/Library/Developer/Xcode/DerivedData/Bizzby-dahgyqiunbzrnahilpofniadttpg/Build/Products/Release-iphonesimulator/applications
ios >= 6.0. Safari and hybrid apps are supported.

## Applications :

```
CFBundleName=Bizzby,CFBundleVersion=1.0
CFBundleName=Safari,CFBundleVersion=8536.25
CFBundleName=Safari,CFBundleVersion=8536.25
```

2013-04-12 15:02:32.261:INFO::jetty-7.x.y-SNAPSHOT
2013-04-12 15:02:32.323:INFO::Started SelectChannelConnector@0.0.0.0:4444

cannot delete /Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1/Library
cannot delete content and settings folder /Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1
couldn't re-create/Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1
03:21:901 WARNING DefaultCommandListener.stderr  2013-04-12 15:03:21.900 instruments[45856:707] Recording cancelled : At least one target failed to launch; aborting run
03:21:901 WARNING DefaultCommandListener.stderr  Instruments Trace Error : Failed to start trace.

**Comment by swapnalibhansali** [comment]
My code : 
 DesiredCapabilities cap = IOSCapabilities.iphone("Bizzby", "1.0");
    cap.setCapability(IOSCapabilities.SIMULATOR, true);
        cap.setCapability(IOSCapabilities.LANGUAGE, "en");
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://0.0.0.0:4444/wd/hub/"), cap);
       driver.executeScript("UIATarget.delay(1)");

**Comment by nicegraham** [comment]
I haven't seen these errors before:
cannot delete /Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1/Library
cannot delete content and settings folder /Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1
couldn't re-create/Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1

I think you should chmod them to allow all read write access to the iPhone Simulator folder and below.

**Comment by swapnalibhansali** [comment]
Those errors were added when I tried to run the test script and the device was already launched .

**Comment by swapnalibhansali** [comment]
I got this now - 

https://gist.github.com/nicegraham/5372726

**Comment by swapnalibhansali** [comment]
Where do i see the logs of the emulator ? 
I still cant run the code. It crashes at remote webdriver creation..

**Comment by swapnalibhansali** [comment]
In my test code : I have to inclusde selenium stanalone server and ios -driver 0.6.0 thats it right ? 
Nothing else right ?

**Comment by nicegraham** [comment]
the console where you run ios-driver should give you that information. 

yes, but we haven't upgraded to 2.32 yet so make sure it's not a version mismatch, we're still using 2.31.0.

**Comment by swapnalibhansali** [comment]
Now when it launched the app and stopped at the breakpoint. 
When I tried to open inspector it came up with this error : 

https://gist.github.com/nicegraham/5372721

**Comment by nicegraham** [comment]
I'm not sure it has a session - can you post the first couple of lines of your test?

**Comment by swapnalibhansali** [comment]
My code :
DesiredCapabilities cap = IOSCapabilities.iphone("Bizzby", "1.0");
cap.setCapability(IOSCapabilities.SIMULATOR, true);
cap.setCapability(IOSCapabilities.LANGUAGE, "en");
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://0.0.0.0:4444/wd/hub/"), cap);
driver.executeScript("UIATarget.delay(1)"); 
System.out.println("Launched the application"); 

driver.findElements(By.xpath("//UIAButton[@name='Sign In']"));

**Comment by nicegraham** [comment]
if you breakpoint on the driver line:
driver.executeScript("UIATarget.delay(1)"); 

can you confirm that the driver is not null?

at that point if you navigate to:
/wd/hub/sessions do you see anything?

**Comment by swapnalibhansali** [comment]
Thread [main] Suspended exception SessionNotCreatedException  
    Throwables.propagateIfInstanceOf(Throwable, Class<X>) line: 64  
    Throwables.propagateIfPossible(Throwable) line: 84  
    Throwables.propagate(Throwable) line: 159  
    RemoteWebDriver.execute(String, Map<String,?>) line: 563  
    RemoteWebDriver.startSession(Capabilities, Capabilities) line: 216  
    RemoteWebDriver.<init>(CommandExecutor, Capabilities, Capabilities) line: 111  
    RemoteWebDriver.<init>(URL, Capabilities) line: 129 
    Test.main(String[]) line: 24

**Comment by swapnalibhansali** [comment]
When I launch the app , it crashes after sometime. 
Sometime it gives me an error message sometimes it doesnt.  I got this error while debugging the app.

**Comment by swapnalibhansali** [comment]
I put a breakpoint after remote driver creation ,and tried to open  - session from the browser. 
Here is the details exception on ios driver  : 

org.openqa.selenium.WebDriverException: bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.2', java.version: '1.7.0_17'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:151)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:82)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:45)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.uiautomation.ios.server.CommandMapping.createHandler(CommandMapping.java:314)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:129)
    ... 25 more
Caused by: org.openqa.selenium.WebDriverException: Cannot find session  on the sesver.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.2', java.version: '1.7.0_17'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.IOSServerManager.getSession(IOSServerManager.java:173)
    at org.uiautomation.ios.server.command.BaseCommandHandler.<init>(BaseCommandHandler.java:45)
    at org.uiautomation.ios.server.command.BaseNativeCommandHandler.<init>(BaseNativeCommandHandler.java:23)
    at org.uiautomation.ios.server.command.UIAScriptHandler.<init>(UIAScriptHandler.java:30)
    at org.uiautomation.ios.server.command.uiautomation.LogElementTreeNHandler.<init>(LogElementTreeNHandler.java:43)
    ... 31 more
org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: not a valid response 
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.2',

**Comment by nicegraham** [comment]
it looks like the session isn't being created. Looking at the app capabilities and what you're defining they seem to match. https://gist.github.com/nicegraham/5373331

Have you tried launching mobile safari? have you had any success with that?

**Comment by swapnalibhansali** [comment]
I tried this example : 
   DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
    RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), safari);

```
driver.get("http://www.ebay.co.uk/");

System.out.println(driver.getTitle());
driver.quit();
```

It works fine with the setup. 

Are there any app specific settings for the app to accept stuff? Like debug mode or something ? 
I am not very familiar with IOS app settings.

**Comment by swapnalibhansali** [comment]
what does this mean 
42:08:254 WARNING DefaultCommandListener.stderr  2013-04-12 17:42:08.253 ScriptAgent[48936:2e07] +[UIAXElement initialize]: UIAutomation never received kAXAccessibilityLoaded.  Waited 20.02 seconds.

**Comment by nicegraham** [comment]
n
ot beyond the automation profiling:
http://ios-driver.github.io/ios-driver/setup.html#real  you've built it
like that?

**Comment by swapnalibhansali** [comment]
No. I am not testing on the device. I have done the profiling for simulator.

**Comment by nicegraham** [comment]
sorry, I meant the profiling bit:
http://ios-driver.github.io/ios-driver/setup.html#testapp

could you try with the international mountains application from the wiki,
see if that's any better?

**Comment by swapnalibhansali** [comment]
yeah.. it recognizes International mountains , does the click as well. 
But I still couldn't see the inspector. It gave the same error when I tried to go to the inspector URL. 
But at least it reached the next part of the code after driver initialization and did all the actions on the list.

**Comment by nicegraham** [comment]
can you give me the output of the below for you app:
System.out.println(cap.toString());

**Comment by swapnalibhansali** [comment]
Capabilities [{simulator=true, CFBundleName=Bizzby, locale=en_GB, variation=Regular, timeHack=false, device=iphone, CFBundleVersion=1.0, language=en}]

**Comment by nicegraham** [comment]
is there any chance you could share your app?

**Comment by swapnalibhansali** [comment]
no I am afraid :(

**Comment by nicegraham** [comment]
ok, well I don't know why the session isn't being created. It looks like it should match... maybe one of the other guys can think of something.

**Comment by nicegraham** [comment]
I've consulted with my smarter colleagues and without being able to debug the app for you, you'll have to debug it on your side. 

You'll need to download the source code.
Start the server in debug mode assigning the program parameters -host your-ip -port 4444 -aut "your app"

you can put a breakpoint around here for starters:
https://github.com/ios-driver/ios-driver/blob/master/server/src/main/java/org/uiautomation/ios/server/command/uiautomation/NewSessionNHandler.java#L42

you need to see why it's not matching the app and creating the session.

good luck! :)

**Comment by swapnalibhansali** [comment]
Okay will try that. Will keep you posted.

**Comment by swapnalibhansali** [comment]
I got this exception : 

Capabilities [{simulator=true, CFBundleName=Bizzby, locale=en_GB, variation=Regular, timeHack=false, device=iphone, CFBundleVersion=1.0, language=en}]

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x000000010c5158cc, pid=55265, tid=20739

 JRE version: 7.0_17-b02
 Java VM: Java HotSpot(TM) 64-Bit Server VM (23.7-b01 mixed mode bsd-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.dylib+0x25e8cc]

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /Users/swapnalibhansali/Documents/AndroidWorkspace/IOSBizzbyTest/hs_err_pid55265.log

 If you would like to submit a bug report, please visit:
   http://bugreport.sun.com/bugreport/crash.jsp

Logs : 

<terminated>IOSTest [Java Application]  
    <disconnected>IOSTest at localhost:54654  
    <terminated, exit value: 134>/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/bin/java (15 Apr 2013 10:42:38)

**Comment by nicegraham** [comment]
Apparently there is a bug in istruments which means it must match the version on the device. So you can't have instruments version 6.1 and the device running 5.0 for example. Can you verify that this isn't the case in your situation?

**Comment by swapnalibhansali** [comment]
device you mean emulator  ? I am not running the tests on the device

**Comment by nicegraham** [comment]
You didn't provide any context to the most recent errors you posted but they don't list any reference to the ios-driver codebase. Would you be able to try running on a different machine?

**Comment by swapnalibhansali** [comment]
Guess what, I tried running it on the device (iphone) . Did the device setup. 
It worked fine :D :D :D 

Yes I had tried with a different machine with simulator. It didn't work. 

I will debug whats wrong with the simulator as well.

**Comment by swapnalibhansali** [comment]
I created a UI automation profile with device , and used the same app to start ios server but without beta flag. 
And I ran the application on the simulator . 
Do you think is the right way of doing things ? For all the other experiments I used profile created with iphone simulator. This is just a trial. 

Here is what I get as an error : 
cannot delete /Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1/Library
cannot delete content and settings folder /Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1
couldn't re-create/Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1
25:50:282 WARNING DefaultCommandListener.stderr  posix spawn failure; aborting launch (binary == /Users/swapnalibhansali/Documents/BizzyIOSAutomation/DeviceApp/Bizzby.app/Bizzby).
25:50:286 WARNING DefaultCommandListener.stderr  2013-04-15 15:25:50.285 instruments[68121:707] Recording cancelled : At least one target failed to launch; aborting run
25:50:286 WARNING DefaultCommandListener.stderr  Instruments Trace Error : Failed to start trace.

**Comment by nicegraham** [comment]
you're still getting those permissions errors for the settings folder: 
cannot delete /Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1/Library
cannot delete content and settings folder /Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1
couldn't re-create/Users/swapnalibhansali/Library/Application Support/iPhone Simulator/6.1

Can you apply read and write permissions to that folder?

**Comment by swapnalibhansali** [comment]
I added the permission. It still didnt work. 
I finally ran it as Sudo. 

This is what I get now 
39:23:677 WARNING DefaultCommandListener.stderr  posix spawn failure; aborting launch (binary == /Users/swapnalibhansali/Documents/BizzyIOSAutomation/DeviceApp/Bizzby.app/Bizzby).
39:23:681 WARNING DefaultCommandListener.stderr  2013-04-15 15:39:23.681 instruments[68272:707] Recording cancelled : At least one target failed to launch; aborting run
39:23:682 WARNING DefaultCommandListener.stderr  Instruments Trace Error : Failed to start trace.

**Comment by swapnalibhansali** [comment]
Now my iphone 6.1 simulator is crashed and not launching again. 
Not sure if I can reinstall only the simulator :(

**Comment by nicegraham** [comment]
it can be flaky and we've found we've needed to restart the machine sometimes.

**Comment by swapnalibhansali** [comment]
Nope machine restart also didnt help. 
Cant start the simulator at all

**Comment by nicegraham** [comment]
Ok, at this point it looks like an xcode/instruments/simulator issue. I
think you'll have to reinstall maybe... it's really beyond the scope of
ios-driver though.

**Comment by saikrishna321** [comment]
I have the same issue , i really cant find anything on my inspector ??? Need help on this

**Comment by jkeeler** [comment]
I don't know if this helps anyone, but I was having the "cannot delete /Users/*/Library/Application Support/iPhone Simulator/6.1/Library" errors on my system while attempting to automate mobile safari via the python webdriver API.

I first attempted to set the proper permissions on those directories (as others in this thread have done), but that didn't solve the problem.

I then deleted the 6.1 directory (actually just moved it out to a safe place), restarted ios-driver.jar, re-ran my test and the errors went away, instrumentation correctly recreated the 6.1 directory structure. Most importantly my python test worked and are functioning correctly.

I am not an xcode/mobile app developer, so I do not know what those directories are for or what they do, but hopefully this helps someone.

**Comment by dbpfindexp** [comment]
It seems if i add the write permission it works the 1st time but then the folder reverts permissions to just read and execute and throws the exception again.  If i reset and try again it'll again work the 1st time.  Why does it change the permission of the folders everytime?  Is it deleting the folder on restart and trying to always create a new one?

**Comment by sesudhanshu** [comment]
Hi Swapna,

Can you elaborate the steps. how you ran onto device ?
