### ISSUE TITLE
Not able to run test on Safari Simulator 

### ISSUE THREAD

**Issue by saikrishna321** [ios-driver/ios-driver#153]
I tried with the same example from the site , when i run the test i get the below error 

Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.selenium.WebDriverException.setSessionId(Ljava/lang/String;)V
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:160)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:215)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:110)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
    at com.test.IphoneDriver.AutomationScroll.main(AutomationScroll.java:16)

Server jar version is 0.5.0 and i have started the port from command line this way 

java -jar /Users/vidya/Desktop/IOSDriver/ios-server-0.5.0.jar -port 4444
39:12:961 INFO IOSServer.init  
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
using xcode install : /Applications/Xcode.app
using IOS version 6.0
ios >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Safari,CFBundleVersion=8536.25
```

2013-09-20 09:39:13.036:INFO::jetty-7.x.y-SNAPSHOT
2013-09-20 09:39:13.327:INFO::Started SelectChannelConnector@0.0.0.0:4444

**Comment by nicegraham** [comment]
please use 0.6.4 and you'll have to add -simulators flag to the start parameters to enable simulators.
