### ISSUE TITLE
Object arguments for executing JavaScript code

### ISSUE THREAD

**Issue by avaly** [ios-driver/ios-driver#156]
I'm trying to use ios-driver for our functional testing suite which uses a lot of JavaScript helper scripts.

I found an issue in regards to how ios-driver parses the arguments sent to an `execute` command.

Setup: ios-driver 0.6.4 running as a node for Selenium Grid 2.33.0

The test is calling the `execute` method with the following JavaScript code:

``` javascript
document.body.innerHTML = JSON.stringify(arguments);
```

and the following arguments list (1 argument - a JSON object): 

``` javascript
[{
    'foo': 'bar',
    'ham': 123
}]
```

**Actual result:**

The ios-driver log:

```
21:40:829 WARNING IOSServlet.getResponse  0ms.  POST     /session/:sessionId/execute
org.openqa.selenium.WebDriverException: Error processing response.bug.1
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_40'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_40'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:121)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:724)
Caused by: org.openqa.selenium.WebDriverException: bug.1
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_40'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:164)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    ... 24 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at org.uiautomation.ios.context.BaseWebInspector.executeScript(BaseWebInspector.java:266)
    at org.uiautomation.ios.wkrdp.RemoteIOSWebDriver.executeScript(RemoteIOSWebDriver.java:375)
    at org.uiautomation.ios.server.command.web.ExecuteScriptHandler.handle(ExecuteScriptHandler.java:40)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:86)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:144)
    ... 25 more
```

The error message returned by the Selenium Grid:

```
Cannot read property 'ELEMENT' of undefined
```

**Expected result:**

body should contain:

```
{"0":{"foo":"bar","ham":123}}
```

This is correct in Google Chrome via ChromeDriver.

**Comment by avaly** [comment]
According to the JSON Wire Protocol the arguments list can contain any JSON-primitive, array or JSON object.

http://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/execute

**Comment by freynaud** [comment]
Can you try with http://ios-driver-ci.ebaystratus.com/userContent/ios-server-standalone-0.6.6-SNAPSHOT.jar and let me know if you still have this issue ?
