### ISSUE TITLE
What is "bug.handler NI"?

### ISSUE THREAD

**Issue by ghost** [ios-driver/ios-driver#157]
I wished know button click count.
So I wrote code like this
-->
WebElement assertionClick = fit.driver.findElement(By.linkText("label=cnt"));

String cnt = assertionClick.getText(); <-- exception occur
System.out.println("Button Click Test ::"+ cnt +" click! ");

cf. "cnt" is a text label and set there string that a count number when click button.

Exception occured when perform getText() method.

plz help :(

console ::

04:52:239 WARNING IOSServlet.getResponse  60ms. POST     /session/:sessionId/element
04:52:263 WARNING IOSServlet.getResponse  0ms.  
org.openqa.selenium.WebDriverException: Error processing response.bug.handler NI
Build info: version: '2.35.0', revision: '8df0c6bedf70ff9f22c647788f9fe9c8d22210e2', time: '2013-08-17 12:46:41'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.7.0_25'
Driver info: driver.version: unknown
Build info: version: '2.35.0', revision: '8df0c6bedf70ff9f22c647788f9fe9c8d22210e2', time: '2013-08-17 12:46:41'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:121)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:46)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:724)

**Comment by federicoviscomi** [comment]
Hi

could you please report the bug using this template?
http://ios-driver.github.io/ios-driver/bug.html

**Comment by ghost** [comment]
Ok. My version is

"build": {
      "revision": "unknown",
      "time": "unknown",
      "version": "unknown"
    },
    "ios": {"simulatorVersion": "6.1"},
    "java": {"version": "1.7.0_25"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.7.5"
    }

I don't know why this version shows 'unknown'

**Comment by freynaud** [comment]
this means the command is not implemented. There is not getText() for native. Use getAttribute("name") , label or value.
