### ISSUE TITLE
Not able to run test on safari simulator and actual device

### ISSUE THREAD

**Issue by kveerannagari123** [ios-driver/ios-driver#162]
test code is as below:

DesiredCapabilities safari = IOSCapabilities.iphone("Safari");

RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), safari);

 driver.get("http://www.ebay.co.uk/");

 System.out.println(driver.getTitle());
 driver.quit();

Starting the server :

sudo java -jar ios-server-0.6.5-jar-with-dependencies.jar -port 4444 -simulators

Throws below error when running tests on simulator

2013-10-04 15:18:12.913:INFO::jetty-7.x.y-SNAPSHOT
2013-10-04 15:18:12.986:INFO::Started SelectChannelConnector@0.0.0.0:4444
18:26:995 WARNING DefaultCommandListener.stderr  2013-10-04 15:18:26.994 instruments[2586:707] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff75831500
18:26:996 WARNING DefaultCommandListener.stderr  2013-10-04 15:18:26.995 instruments[2586:707] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff75831500
18:26:998 WARNING DefaultCommandListener.stderr  2013-10-04 15:18:26.997 instruments[2586:707] **\* Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-185/Classes/UIAInstrument-Simulator.m:116
18:26:998 WARNING DefaultCommandListener.stderr  2013-10-04 15:18:26.997 instruments[2586:707] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException

When running for actual device 

sudo java -jar ios-server-0.6.5-jar-with-dependencies.jar -port 4444 -beta

Cannot load libimobiledevice-sdk.dylib
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:57)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:112)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:83)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:62)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:66)
Caused by: java.lang.NullPointerException
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.unpack(IMobileDeviceFactory.java:73)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.<clinit>(IMobileDeviceFactory.java:42)
    ... 5 more

**Comment by jasone** [comment]
The simulators portion of this issue appears to be the same as described in https://github.com/ios-driver/ios-driver/issues/158.

**Comment by nicegraham** [comment]
and you can't run safari on real devices - just in the simulator. Also for ios7 we haven't been able to get safari working yet.

**Comment by kveerannagari123** [comment]
I am using XCode 5 with latest simulators, and the real devices with iOS 7. I am not able to run in both the cases. How can I switch to previous version of XCode ? and make it work? Any help is highly appreciated.

**Comment by nicegraham** [comment]
xcode-select -switch

**Comment by kveerannagari123** [comment]
I also tried switching to Xcode 4.5 , but there is an issue in loading the instruments . It throws the error "Unknown error" 
The log:
39:20:106 WARNING DefaultCommandListener.stderr  2013-10-07 17:39:20.105 instruments[1361:707] Recording cancelled : At least one target failed to launch; aborting run
39:20:107 WARNING DefaultCommandListener.stderr  Instruments Trace Error : Failed to start trace.

**Comment by kveerannagari123** [comment]
I am able to run on iOS6 simulator but not on the real device (with iOS 6.1). It throws following error.

Cannot load libimobiledevice-sdk.dylib
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:57)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:112)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:83)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:62)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:66)
Caused by: java.lang.NullPointerException
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.unpack(IMobileDeviceFactory.java:73)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.<clinit>(IMobileDeviceFactory.java:42)
    ... 5 more

Can anybody help me regarding this?

**Comment by naveendnr** [comment]
Hi nicegraham,

is this issue fixed. we got the below issue when we run iOS driver with -beta.

Cannot load libimobiledevice-sdk.dylib
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:57)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:112)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:83)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:62)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:66)
Caused by: java.lang.NullPointerException
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.unpack(IMobileDeviceFactory.java:73)
    at org.libimobiledevice.ios.driver.binding.IMobileDeviceFactory.<clinit>(IMobileDeviceFactory.java:42)

**Comment by nicegraham** [comment]
real devices aren't currenttly supported so you need to remove the -beta flag.

**Comment by naveendnr** [comment]
are there any development is going on for device support. if yes when it will be released. Please let us know. thanx in advance
