### ISSUE TITLE
[Safari] Page is not responsive. WebDriverException: Error processing response.bug.null

### ISSUE THREAD

**Issue by sobhajha** [ios-driver/ios-driver#165]
using: ios-server-0.6.5-jar-with-dependencies.jar
xcode: 4.6.3
selenium: 2.35.0

When interacting with the pages (especially after changing from one page to the other) this error occurs.
What works: set breakpoint, manually go back (in browser) and return to the same page. After this everything starts working again.

Is this a bug?

23:46:771 WARNING IOSServlet.getResponse  1ms.  POST     /session/:sessionId/element
org.openqa.selenium.WebDriverException: Error processing response.bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:121)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:724)
Caused by: org.openqa.selenium.WebDriverException: bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:164)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    ... 24 more
Caused by: java.lang.NullPointerException
    at org.uiautomation.ios.wkrdp.RemoteIOSWebDriver.getDocument(RemoteIOSWebDriver.java:385)
    at org.uiautomation.ios.server.command.web.FindElementHandler.findElement(FindElementHandler.java:83)
    at org.uiautomation.ios.server.command.web.FindElementHandler.handle(FindElementHandler.java:41)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:86)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:144)
    ... 25 more

**Comment by julianhaslinger** [comment]
Are there any news regarding your problem? Were you able to fix this issue? We are currently having the same problem, too.

**Comment by freynaud** [comment]
can you try with https://dl.dropboxusercontent.com/u/24687868/ios-beta/ios-server-0.6.6-SNAPSHOT-jar-with-dependencies.jar and let me know if you still have the issue ?

**Comment by spatchamatla01** [comment]
@freynaud , can you send me the ios-server-0.6.6-snapshot-jar-with-dependencies.jar

**Comment by freynaud** [comment]
http://ios-driver.github.io/ios-driver/ , top right corner
