### ISSUE TITLE
iOS driver does't work with iOS app whose Localizable.strings file is in text format rather than binary

### ISSUE THREAD

**Issue by xuyuansi** [ios-driver/ios-driver#18]
@freynaud,

The Localizable.strings file of my target iOS app is in text format. When I tried to use iOS driver 0.6.0 with the app, I got the following error:

Exception in thread "main" org.openqa.selenium.WebDriverException: error loading content for l10n
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.4', java.version: '1.6.0_41'
Driver info: driver.version: unknown
at org.uiautomation.ios.server.application.APPIOSApplication.loadAllContent(APPIOSApplication.java:168)
at org.uiautomation.ios.server.application.APPIOSApplication.(APPIOSApplication.java:61)
at org.uiautomation.ios.server.application.APPIOSApplication.createFrom(APPIOSApplication.java:470)
at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:129)
at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:88)
at org.uiautomation.ios.server.IOSServer.(IOSServer.java:61)
at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:65)
Caused by: org.openqa.selenium.WebDriverException: Cannot parse info.plist : The given data is no binary property list. Wrong magic bytes: "App.ver
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.4', java.version: '1.6.0_41'
Driver info: driver.version: unknown
at org.uiautomation.ios.utils.PlistFileUtils.read(PlistFileUtils.java:50)
at org.uiautomation.ios.utils.PlistFileUtils.(PlistFileUtils.java:41)
at org.uiautomation.ios.server.application.LanguageDictionary.readContentFromBinaryFile(LanguageDictionary.java:195)
at org.uiautomation.ios.server.application.APPIOSApplication.loadAllContent(APPIOSApplication.java:165)
... 6 more
Caused by: java.lang.Exception: The given data is no binary property list. Wrong magic bytes: "App.ver
at com.dd.plist.BinaryPropertyListParser.doParse(BinaryPropertyListParser.java:86)
at com.dd.plist.BinaryPropertyListParser.parse(BinaryPropertyListParser.java:73)
at com.dd.plist.BinaryPropertyListParser.parse(BinaryPropertyListParser.java:136)
at com.dd.plist.BinaryPropertyListParser.parse(BinaryPropertyListParser.java:149)
at org.uiautomation.ios.utils.PlistFileUtils.read(PlistFileUtils.java:48)
... 9 more

In iOS driver PlistFileUtils.java there is one line of code trying to parse binary files, as shown in "Place A" below.

private Map read(File bplist) {
NSObject object = null;
try {
object = BinaryPropertyListParser.parse(bplist); // <--- Place A
} catch (Exception e) {
throw new WebDriverException("Cannot parse info.plist : " + e.getMessage(), e);
}
ApplicationInfo info = new ApplicationInfo(object);
return info.getProperties();
}

But when I tried to use iOS driver against the iOS app, the line of code throws an exception because the file bplist is not binary.

My non-binary file is in Build/Products/Debug-iphonesimulator/XoomApp.app/en.lproj/Localizable.strings (when I use bash file command to inspect this file, it is :ASCII English text, with very long lines).

It seems that the text format of the target app is also right because the app's localization works well. So maybe iOS driver would like to add support on this case?

Thanks,

Xuyuan

**Comment by nicegraham** [comment]
should be resolved by https://github.com/ios-driver/ios-driver/commit/2b56e9df458e7c5b2ac61430f97debffb2deb99b
