### ISSUE TITLE
unable to launch iOS Simulator for MobileSafari due to org.openqa.selenium.WebDriverException: iPhone incompatible with SDK 7.0

### ISSUE THREAD

**Issue by SurenMohanathas** [ios-driver/ios-driver#188]
I am trying to run some tests with the mobile safari on the iOS7 simulator.  below are my environment setup:
built ios-server-0.6.5-jar-with-dependencies.jar from refactor branch
xcode 5.02
on the seleniium grid with version selenium-server-standalone-2.37.0.jar

----------------------------------------------------------my exception trace---------------------
sudo java -jar ios-server-0.6.5-jar-with-dependencies.jar -hub http://127.0.0.1:4444/grid/register -host 127.0.0.1 -simulators
35:07:644 INFO ApplicationStore.<init>  App archive folder:/Users/smohanat/selenium-node-iOS/applications
35:09:575 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled (enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/smohanat/selenium-node-iOS/applications' for new applications
Archived apps: /Users/smohanat/selenium-node-iOS/applications
Build info: ios-driver 0.6.5 (built:20131216-2129,sha:f556e767821a21284da03c31ea07bba1dafd409d)
Running on: Mac OS X 10.8.5 (x86_64)
Using java: 1.7.0_12-ea
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.0.1, build: 51168
Using iOS version 7.0
iOS >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Safari,CFBundleVersion=8536.25,/var/root/.ios-driver/safariCopies/safari-6.0.app
CFBundleName=Safari,CFBundleVersion=9537.53,/var/root/.ios-driver/safariCopies/safari-7.0.app
```

2013-12-16 21:35:09.644:INFO::jetty-7.x.y-SNAPSHOT
2013-12-16 21:35:09.716:INFO::Started SelectChannelConnector@0.0.0.0:5555
40:31:945 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /var/root/.ios-driver/safariCopies/MobileSafari-7.0.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app
org.openqa.selenium.WebDriverException: iPhone incompatible with SDK 7.0
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_12-ea'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.utils.SimulatorSettings.getSimulateDeviceValue(SimulatorSettings.java:295)
    at org.uiautomation.ios.utils.SimulatorSettings.setVariation(SimulatorSettings.java:211)
    at org.uiautomation.ios.server.simulator.IOSSimulatorManager.setVariation(IOSSimulatorManager.java:194)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.start(InstrumentsApple.java:114)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.start(InstrumentsBackedNativeIOSDriver.java:44)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:92)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:178)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:40)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:722)
45:40:217 WARNING IOSServlet.doDelete  org.openqa.selenium.WebDriverException: Error processing response.cannot find command for DELETE, /session/
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_12-ea'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_12-ea'
Driver info: driver.version: unknown
45:43:494 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /var/root/.ios-driver/safariCopies/MobileSafari-7.0.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app
org.openqa.selenium.WebDriverException: iPhone incompatible with SDK 7.0
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_12-ea'
Driver info: driver.version: IOSDualDriver

**Comment by SurenMohanathas** [comment]
I was able to get the iOS7 simulator with mobileSafari working with th ios-driver built from the refactor branch.  below is exactly what i did.

sudo chmod 666 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator*.sdk/Applications/MobileSafari.app/Info.plist 
java -jar selenium-server-standalone-2.37.0.jar -host 127.0.0.1 -role hub -timeout 30

rm -rf ~/.ios-driver/
sudo chmod -R a+rw /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app
sudo chmod a+rw /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications
java -jar ios-server-0.6.5-jar-with-dependencies.jar -hub http://127.0.0.1:4444/grid/register -host 127.0.0.1 -simulators

DesiredCapabilities safariIphone = IOSCapabilities.iphone("Safari");
safariIphone.setCapability(IOSCapabilities.SIMULATOR, true);
safariIphone.setCapability("variation", "Retina4");
safariIphone.setCapability(IOSCapabilities.LANGUAGE, "en");
safariIphone.setCapability(IOSCapabilities.LOCALE, "en_US");

**Comment by spatchamatla01** [comment]
@surenAKA 

i tried the above, but seeing the below error
org.openqa.selenium.WebDriverException: Cannot find /instruments_no_delay/5.1/55044/instruments.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.extractFromJar(InstrumentsNoDelayLoader.java:91)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.extract(InstrumentsNoDelayLoader.java:75)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.<init>(InstrumentsNoDelayLoader.java:43)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.getInstance(InstrumentsNoDelayLoader.java:53)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.getInstrumentsClient(InstrumentsApple.java:210)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.createInstrumentCommand(InstrumentsApple.java:177)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.<init>(InstrumentsApple.java:87)
    at org.uiautomation.ios.server.services.InstrumentsFactory.getInstruments(InstrumentsFactory.java:48)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.<init>(InstrumentsBackedNativeIOSDriver.java:33)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:104)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:233)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:45)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)
36:17:299 SEVERE IOSServlet.getResponse  POST:/session
    body:{"desiredCapabilities":{"simulator":true,"variation":"Retina4","CFBundleName":"Safari","locale":"en_US","timeHack":false,"device":"iphone","language":"en"}}  in 1034ms
36:17:303 WARNING IOSServlet.doPost  org.openqa.selenium.WebDriverException: Error processing response.bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
