### ISSUE TITLE
throw "java.lang.RuntimeException: java.lang.reflect.InvocationTargetException"

### ISSUE THREAD

**Issue by CandyHe** [ios-driver/ios-driver#200]
Hi, when I ran cases on ios simulator via remote grid, it often throws  InvocationTargetException. It didn't raised every time. Is there anyone has met this exception? Looking forward to your help. Many thanks!

hub:
java -jar selenium-server-standalone-2.39.0.jar -role hub

node:
java -jar ios-server-0.6.5-jar-with-dependencies.jar -hub http://10.32.98.7:4444/grid/register -host autoosx009 -port 5555 -simulators -sessionTimeout 360

My code is as follow:

switch (cfg.getBrowser()) {
        case IPhone:
        case IPad:
            driver = (WebDriver) Class
                    .forName(
                                        "com.ebay.maui.driver.web.factory.RemoteIOSBaseDriver")
                    .getConstructor(URL.class, DesiredCapabilities.class)
                    .newInstance(url, capability);
            break;

public class RemoteIOSBaseDriver extends RemoteIOSDriver{

```
public RemoteIOSBaseDriver(URL url,DesiredCapabilities capability){
    super(url,(IOSCapabilities)capability);
}
```

}

The exception shows:

Driver info: com.ebay.maui.driver.web.factory.RemoteIOSBaseDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.<init>(RemoteIOSDriver.java:87)
    at com.ebay.maui.driver.web.factory.RemoteIOSBaseDriver.<init>(RemoteIOSBaseDriver.java:16)

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at com.ebay.maui.driver.web.factory.RemoteDriverFactory.createWebDriver(RemoteDriverFactory.java:97)

**Comment by federicoviscomi** [comment]
could you write the whole stack trace and the code of cfg, url and capability?
i am trying to reproduce this issue but i get a different error:

Caused by: java.lang.ClassCastException: org.openqa.selenium.remote.DesiredCapabilities cannot be cast to org.uiautomation.ios.IOSCapabilities
    at com.ebay.maui.driver.web.factor.RemoteIOSBaseDriver.<init>(RemoteIOSBaseDriver.java:20)

which is inside the constructor of RemoteIOSBaseDriver

**Comment by freynaud** [comment]
are you still seeing the issue with http://ios-driver-ci.ebaystratus.com/userContent/ios-server-standalone-0.6.6-SNAPSHOT.jar
