### ISSUE TITLE
Cannot create session?

### ISSUE THREAD

**Issue by skyzyx** [ios-driver/ios-driver#209]
After staring at this for a few hours, I'm stumped. What might I be doing wrong?
- OS X Mavericks 10.9.2 seed
- Xcode 5.1 β4 with iOS Simulator 7.1 β4
- ios-driver built from source, today, from the `dev` branch

``` sh
org.openqa.selenium.WebDriverException: Cannot find /instruments_no_delay/5.1/55030.2/instruments.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.extractFromJar(InstrumentsNoDelayLoader.java:91)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.extract(InstrumentsNoDelayLoader.java:75)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.<init>(InstrumentsNoDelayLoader.java:43)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.getInstance(InstrumentsNoDelayLoader.java:53)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.getInstrumentsClient(InstrumentsApple.java:210)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.createInstrumentCommand(InstrumentsApple.java:177)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.<init>(InstrumentsApple.java:87)
    at org.uiautomation.ios.server.services.InstrumentsFactory.getInstruments(InstrumentsFactory.java:48)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.<init>(InstrumentsBackedNativeIOSDriver.java:33)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:104)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:233)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:45)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)
45:31:671 SEVERE IOSServlet.getResponse  POST:/session
    body:{"desiredCapabilities":{"platform":"mac","ignoreZoomSetting":"false","browserVersion":"9","browserName":"iphone","deviceType":"iphone","selenium-version":"2.31.0","name":"Behat Test","browser":"iphone","deviceOrientation":"portrait","max-duration":"300","version":"7.1"},"requiredCapabilities":[]}  in 3339ms
45:31:711 WARNING IOSServlet.doPost  org.openqa.selenium.WebDriverException: Error processing response.bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
45:31:721 WARNING IOSServlet.doPost  org.openqa.selenium.WebDriverException: Error processing response.cannot find command for POST, /session/url
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
45:31:790 WARNING IOSServlet.doDelete  org.openqa.selenium.WebDriverException: Error processing response.cannot find command for DELETE, /session
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'
Driver info: driver.version: unknown
```

**Comment by nxqamar** [comment]
I also did build off of dev branch and i am getting the same error. I have replaced following files with the ones from this build
ios-server-0.6.5-jar-with-dependencies.jar
ios-server-0.6.5.jar (in my maven repository dependency dir)
ios-client-0.6.5.jar (in my maven repository dependency dir)

```
new-host:ios-driver nxq$ java -jar ios-server-0.6.5-jar-with-dependencies.jar -port 4242 -simulators
13:38:016 INFO ApplicationStore.<init>  App archive folder:/opt/ios-driver/applications
13:38:971 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled (enabled by -simulators flag): true
Inspector: http://0.0.0.0:4242/inspector/
Tests can access the server at http://0.0.0.0:4242/wd/hub
Server status: http://0.0.0.0:4242/wd/hub/status
Connected devices: http://0.0.0.0:4242/wd/hub/devices/all
Applications: http://0.0.0.0:4242/wd/hub/applications/all
Capabilities: http://0.0.0.0:4242/wd/hub/capabilities/all
Monitoring '/opt/ios-driver/applications' for new applications
Archived apps: /opt/ios-driver/applications
Build info: ios-driver 0.6.5 (built:20140127-1749,sha:48e821b212dee4f497a3cb4aa6c58beb5fe7d39d)
Running on: Mac OS X 10.8.5 (x86_64)
Using java: 1.7.0_45
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.0.1, build: 51168
Using iOS version 7.0.3
iOS >= 6.0. Safari and hybrid apps are supported.

aaplications (formatted for comment)

CFBundleName=Safari,CFBundleVersion=9537.53,/Users/nxquser/.ios-driver/safariCopies/safari-7.0.3.app
2014-01-27 18:13:39.061:INFO::jetty-7.x.y-SNAPSHOT
2014-01-27 18:13:39.143:INFO::Started SelectChannelConnector@0.0.0.0:4242
14:59:205 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/nxquser/.ios-driver/safariCopies/MobileSafari-7.0.3.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app
org.openqa.selenium.WebDriverException: iPhone variation incompatible with SDK 7.0.3, a compatible variation is Retina4
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.utils.SimulatorSettings.getSimulateDeviceValue(SimulatorSettings.java:254)
    at org.uiautomation.ios.utils.SimulatorSettings.setVariation(SimulatorSettings.java:166)
    at org.uiautomation.ios.server.simulator.IOSSimulatorManager.setVariation(IOSSimulatorManager.java:194)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.start(InstrumentsApple.java:122)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.start(InstrumentsBackedNativeIOSDriver.java:44)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:105)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:233)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:45)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)
15:00:587 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/nxquser/.ios-driver/safariCopies/MobileSafari-7.0.3.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app
org.openqa.selenium.WebDriverException: iPhone variation incompatible with SDK 7.0.3, a compatible variation is Retina4
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_45'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.utils.SimulatorSettings.getSimulateDeviceValue(SimulatorSettings.java:254)
    at org.uiautomation.ios.utils.SimulatorSettings.setVariation(SimulatorSettings.java:166)
    at org.uiautomation.ios.server.simulator.IOSSimulatorManager.setVariation(IOSSimulatorManager.java:194)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.start(InstrumentsApple.java:122)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.start(InstrumentsBackedNativeIOSDriver.java:44)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:105)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:233)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:45)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)

```

**Comment by nxqamar** [comment]
Not sure what is this referring to

```
org.openqa.selenium.WebDriverException: iPhone variation incompatible with SDK 7.0.3, a compatible variation is Retina4
```

**Comment by skyzyx** [comment]
@nxqamar: Your issue looks just like the one that's causing Travis to fail. https://travis-ci.org/ios-driver/ios-driver/builds/17521034

Mine appears to be related to Mavericks + Xcode 5 + iOS Simulator 7.1.

**Comment by freynaud** [comment]
@skyzyx  supported instruments versions : https://github.com/ios-driver/ios-driver/tree/dev/server/src/main/resources/instruments_no_delay
( xcode 5.0.2 has instruments 5.0.1 )
I wasn't planning on supporting beta version in ios-driver. Any reason we should ?

@nxqamar please try not to add comments for an unrelated issue.Your stacktrace seems to imply you're trying to launch a combination of simulator / device that doesn't exist.IOS7 can only be run on Retina display. Try with DeviceVariation.iPhoneRetina

**Comment by nxqamar** [comment]
@skyzyx  Thanks for the pointer.
@freynaud Sorry for the comments noise. I have removed unrelated comments as a standalone yet detailed issue [here](https://github.com/ios-driver/ios-driver/issues/211). Thanks for the reply.

**Comment by skyzyx** [comment]
@freynaud: I didn't know that only certain, explicit versions of Xcode were supported. It would be helpful if this were documented somewhere on the project website. :)

I'll re-install the older version of Xcode and give it another try. Thanks!

**Comment by freynaud** [comment]
@skyzyx  we accept pull request for the project, incl. doc :)

@skyzyx it's not ios-driver per say. To remove a delay in instruments, we use 
https://github.com/facebook/instruments-without-delay
This is built on top of the instruments binaries. I think it is safer to rebuild for new versions of instruments and be sure it works, rather than having cryptic errors with new binaries.

If you need a new feature no released in the current ios-driver, compiling the facebook project should be straight forward.

**Comment by ainthek** [comment]
Sorry but reading this discussion I really do not understand reasonable solution.
I have maverics, I have some version of Xcode:
get the error just with variation:
/instruments_no_delay/5.1/55044/instruments

org.openqa.selenium.WebDriverException: Cannot find /instruments_no_delay/5.1/55044/instruments.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_45'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.extractFromJar(InstrumentsNoDelayLoader.java:91)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.extract(InstrumentsNoDelayLoader.java:75)
    at org.uiautomation.ios.server.simulator.InstrumentsNoDelayLoader.<init>(InstrumentsNoDelayLoader.java:43)

WHAT SHALL I DO ?

**Comment by khallbec** [comment]
I have this problem also.

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Cannot find /instruments_no_delay/5.1.1/55045/instruments.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_51'

Selendroid was so easy to use. I want to switch from monkey talk to iOS-driver, but I can't if this happens.

Help?
I'll switch once it is usable.

**Comment by sglebs** [comment]
I had to run the bleeding edge to make this instruments problem go away:

git clone git@github.com:ios-driver/ios-driver.git
cd ios-driver/
git submodule init
git submodule update
mvn package -DskipTests
cp server/target/ios-server-standalone-0.6.6-SNAPSHOT-e1bb7351e221c753ae72895cbd509337ace395a5-jar-with-dependencies.jar ~/Downloads/ios-driver/ios-server-standalone-0.6.6-SNAPSHOT.jar

Then run:

java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut UICatalog.app -port 4444

I ran it like this form the client (FitNesse):

!define PROTOCOL {http}
!define url {${PROTOCOL}://localhost:5555/wd/hub}

!define TEST_SYSTEM {slim} 
!path ./dependencies/*

!define slim.timeout {90}

|import|
|com.xebia.incubator.xebium|

|library |
|selenium driver fixture |

| script |
|start browser |{"remote": "${url}", "device" : "iphone", "language": "en", "locale": "en_US", "CFBundleName": "UICatalog", "simulator": "true", "variation":"iPhone5s", "instruments": "true"} |on url    ||
|stop browser |

It does open the simulator now. The problem I am having now is that it opens the simulator multiple times, and the HTTP reply never comes. FitNess complains of a reply timeout. I am investigating that now.

**Comment by JoolsCaesar** [comment]
I was facing this problem so I got the bleeding edge version of ios-driver (as @sglebs suggested) and this led to me seeing issue #334
