### ISSUE TITLE
Can't get ios-driver to work with simulator

### ISSUE THREAD

**Issue by valnub** [ios-driver/ios-driver#217]
I did the following:

1.) Start up ios-server:

```
$ java -jar ios-server-0.6.5-jar-with-dependencies.jar -port 5555 -simulators
16:39:412 INFO ApplicationStore.<init>  App archive folder:/Users/valmar/Downloads/applications
16:40:492 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
16:40:970 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
16:40:991 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
16:41:058 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
tests can access the server at http://0.0.0.0:5555/wd/hub
server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/valmar/Downloads/applications' for new applications
Archived apps /Users/valmar/Downloads/applications
using xcode install : /Applications/Xcode.app
using IOS version 7.0
ios >= 6.0. Safari and hybrid apps are supported.

Applications:
    CFBundleName=Safari,CFBundleVersion=9537.53

2014-02-13 16:16:41.059:INFO::jetty-7.x.y-SNAPSHOT
2014-02-13 16:16:41.186:INFO::Started SelectChannelConnector@0.0.0.0:5555
```

2.) Fire up simulator:

```
open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app &
```

3.) Create my selenium test:

``` java
public static void main(String[] args) throws Exception {
    DesiredCapabilities caps = IOSCapabilities.iphone();
    caps.setCapability(IOSCapabilities.SIMULATOR, true);
    RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), caps);

    driver.get("http://www.google.com");

    System.out.println(driver.getTitle());
    driver.quit();
}
```

4.) ... and all I get is this exception:

```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: {simulator=true, timeHack=false, variation=Regular, locale=en_GB, CFBundleName=Safari, device=iphone, language=en}not available. Available are [Simulator]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Command duration or timeout: 625 milliseconds
Build info: version: '2.39.0', revision: 'ff23eac', time: '2013-12-16 16:12:12'
System info: host: 'tacbook13.local', ip: '172.20.10.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
    at MobSelTest.main(MobSelTest.java:21)
Caused by: org.openqa.selenium.SessionNotCreatedException: {simulator=true, timeHack=false, variation=Regular, locale=en_GB, CFBundleName=Safari, device=iphone, language=en}not available. Available are [Simulator]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Build info: version: '2.39.0', revision: 'ff23eac', time: '2013-12-16 16:12:12'
System info: host: 'tacbook13.local', ip: '172.20.10.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:54)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:86)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:144)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)
```

What's wrong? I have no idea how to debug this.

**Comment by freynaud** [comment]
what version of xcode do you use ? some xcode 5.0 had issues. 5.0.2 works best for me

**Comment by valnub** [comment]
Hi, I am on xcode 5.0.2

**Comment by valnub** [comment]
I ran some more attempts and in server console output I now see this when I try to connect to the ios-server via Selenium (Java):

```
46:49:567 WARNING DefaultCommandListener.stderr  2014-02-14 10:46:49.566 instruments[3011:507] -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff7a931db0
46:49:568 WARNING DefaultCommandListener.stderr  2014-02-14 10:46:49.567 instruments[3011:507] Exception during preparation: -[__NSCFConstantString isEqualToNumber:]: unrecognized selector sent to instance 0x7fff7a931db0
46:49:571 WARNING DefaultCommandListener.stderr  2014-02-14 10:46:49.569 instruments[3011:507] *** Assertion failure in -[UIAInstrument _startAgentForApp:withPID:], /SourceCache/AutomationInstrument/AutomationInstrument-1000/Classes/UIAInstrument-Simulator.m:116
46:49:572 WARNING DefaultCommandListener.stderr  2014-02-14 10:46:49.570 instruments[3011:507] Automation Instrument ran into an exception while trying to run the script.  NSInternalInconsistencyException
```

And this when I try to manually call the server in the browser (via http://0.0.0.0:5555/wd/hub):

```
50:11:200 WARNING IOSServlet.getResponse  2ms.  
org.openqa.selenium.WebDriverException: Error processing response.cannot find command for GET, /
org.openqa.selenium.WebDriverException: Error processing response.cannot find command for GET, /
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:121)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:121)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:46)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:46)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)
    at java.lang.Thread.run(Thread.java:744)
Caused by: org.openqa.selenium.WebDriverException: cannot find command for GET, /
Caused by: org.openqa.selenium.WebDriverException: cannot find command for GET, /
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.7.0_51'
Driver info: driver.version: unknown
Driver info: driver.version: unknown
    at org.uiautomation.ios.communication.WebDriverLikeCommand.getCommand(WebDriverLikeCommand.java:311)
    at org.uiautomation.ios.communication.WebDriverLikeCommand.getCommand(WebDriverLikeCommand.java:311)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getGenericCommand(WebDriverLikeRequest.java:115)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getGenericCommand(WebDriverLikeRequest.java:115)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getVariableValue(WebDriverLikeRequest.java:119)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getVariableValue(WebDriverLikeRequest.java:119)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getSession(WebDriverLikeRequest.java:132)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getSession(WebDriverLikeRequest.java:132)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:150)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:150)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    ... 24 more
```

**Comment by freynaud** [comment]
Can you try http://ios-driver-ci.ebaystratus.com/userContent/ios-server-standalone-0.6.6-SNAPSHOT.jar
and update to xcode 5.1 and let me know if the issue still appear ?

In create the selenium test, it should be 
 DesiredCapabilities caps = IOSCapabilities.iphone("Safari");
