### ISSUE TITLE
cannot start iOS-server due to java.lang.NullPointerException

### ISSUE THREAD

**Issue by jerdine** [ios-driver/ios-driver#218]
"build": {
      "revision": "120cf4311807e2e137e519f4c4877cf6340d0cbc",
      "time": "20130927-1435",
      "version": "0.6.5"
    },
    "ios": {"simulatorVersion": "7.0"},
    "java": {"version": "1.7.0_51"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.9"
    }

Run this: java -jar ios-server-0.6.5-jar-with-dependencies.jar -port 5555 -simulators 

This error is generated:

28:10:246 INFO ApplicationStore.<init>  App archive folder:/Users/{folder}/applications
Exception in thread "main" java.lang.NullPointerException
    at org.uiautomation.ios.server.application.LanguageDictionary.getL10NFiles(LanguageDictionary.java:86)
    at org.uiautomation.ios.server.application.APPIOSApplication.loadAllContent(APPIOSApplication.java:159)
    at org.uiautomation.ios.server.application.APPIOSApplication.<init>(APPIOSApplication.java:65)
    at org.uiautomation.ios.server.application.APPIOSApplication.findSafariLocation(APPIOSApplication.java:299)
    at org.uiautomation.ios.server.IOSServer.copyOfSafari(IOSServer.java:204)
    at org.uiautomation.ios.server.IOSServer.addSimulatorDetails(IOSServer.java:190)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:145)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:83)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:62)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:66)

**Comment by freynaud** [comment]
Can you try with the latest version and let me know if you still have the issue ?
http://ios-driver-ci.ebaystratus.com/userContent/ios-server-standalone-0.6.6-SNAPSHOT.jar

**Comment by marcysutton** [comment]
I still have this problem with that version.
