### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: coudln't find the about:blank button after 3 retries.

### ISSUE THREAD

**Issue by ainthek** [ios-driver/ios-driver#223]
<pre>
java -jar bin/osx/ios-server-standalone-custom-build.jar -port 4444
12:41:449 INFO ApplicationStore.<init>  App archive folder:/Users/user/workspaces/web-test/applications
12:42:171 INFO IOSServer.initDriver
Beta features enabled (enabled by -beta flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:4444/inspector/
Tests can access the server at http://0.0.0.0:4444/wd/hub
Server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/user/workspaces/web-test/applications' for new applications
Archived apps: /Users/user/workspaces/web-test/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140311-1651,sha:fb8461c6971bbe7498273fae251d210664913812)
Running on: Mac OS X 10.9.2 (x86_64)
Using java: 1.7.0_45
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.1, build: 55044
Using iOS version 7.1
iOS >= 6.0. Safari and hybrid apps are supported.

Applications :
---------------
    CFBundleName=Safari,CFBundleVersion=9537.53,/Users/user/.ios-driver/safariCopies/safari-7.1.app

2014-03-11 19:12:42.221:INFO::jetty-7.x.y-SNAPSHOT
2014-03-11 19:12:42.284:INFO::Started SelectChannelConnector@0.0.0.0:4444
18:02:859 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/user/.ios-driver/safariCopies/MobileSafari-7.1.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app
18:07:306 WARNING DefaultCommandListener.stderr  /var/folders/cs/7zzbk12j0k14ykd00r62l3jc   2014-03-11 19:18:07.306 ScriptAgent[1481:2f07] CLTilesManagerClient: initialize, sSharedTilesManagerClient
18:07:307 WARNING DefaultCommandListener.stderr  /var/folders/cs/7zzbk12j0k14ykd00r62l3jc   2014-03-11 19:18:07.306 ScriptAgent[1481:2f07] CLTilesManagerClient: init
18:07:307 WARNING DefaultCommandListener.stderr  /var/folders/cs/7zzbk12j0k14ykd00r62l3jc   2014-03-11 19:18:07.306 ScriptAgent[1481:2f07] CLTilesManagerClient: reconnecting, 0x10a823570
org.openqa.selenium.SessionNotCreatedException: coudln't find the about:blank button after 3 retries.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_45'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.server.services.IOSDualDriver.forceWebViewToReloadManually(IOSDualDriver.java:152)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:115)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:231)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:82)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:49)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)
</pre>

**Comment by freynaud** [comment]
do you have the blank page with only the about:blank button or the one with Disney etc bookmarks ?

**Comment by apomerans** [comment]
I have the same issue. Sometimes it loads about:blank page right away, other times it loads about:blank after getting my testUrl and failing as:

org.openqa.selenium.SessionNotCreatedException: coudln't find the about:blank button after 3 retries.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_51'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.server.services.IOSDualDriver.forceWebViewToReloadManually(IOSDualDriver.java:152)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:115)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:235)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:82)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:49)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:744)

Help?

**Comment by gobim** [comment]
Facing the same issue. Have any one fixed this issue? i have loaded simulator with blank page or with only the about:blank button or the one with Disney etc bookmarks or sometimes its suddenly quit often before safari launch

I have started server with
 java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -port 4444

Using below java code
    DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
        safari.setCapability(IOSCapabilities.SIMULATOR, true);
        safari.setCapability("simulatorVersion", "7.0.3");
        safari.setCapability("sdkVersion", "7.0.3");
          safari.setCapability("variation", "Retina4");
          RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5544/wd/hub"), safari);
          driver.get("http://hp.mobileweb.ebay.co.uk/home");
          WebElement search = driver.findElement(By.id("srchDv"));
          search.sendKeys("ipod");
          search.submit();

this will be ended with org.openqa.selenium.SessionNotCreatedException: failed starting after 3retries.Final wait was 60
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_55'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.7.0_55'
Driver info: driver.version: unknown
....................

In terminal received the below error:

Instruments : Instruments Accepted Command
02:26:849 WARNING DefaultCommandListener.stderr  /var/folders/61/7n0c9s_j1cnf31gj40hk5298   Instruments : Preparing To Start Trace
02:26:849 WARNING DefaultCommandListener.stderr  /var/folders/61/7n0c9s_j1cnf31gj40hk5298   Instruments : Starting Instrument(s)
02:47:287 WARNING InstrumentsApple.start  instruments crashed (20 SEC)
02:49:084 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
02:49:950 INFO InstrumentsApple.moveMobileSafariAppOutOfInstallDir  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/labuser/.ios-driver/safariCopies/MobileSafari-7.0.3.app /Applications/Xcode 2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app

**Comment by freynaud** [comment]
Do you still see the issue with the latest build after upgrading to xcode 5.1 ?
http://ios-driver-ci.ebaystratus.com/userContent/ios-server-standalone-0.6.6-SNAPSHOT.jar

**Comment by vishwanathvodeyar1** [comment]
Hi Freynaud

Even I'm  facing this issue. Yes we see this issue with the Xcode 5.1. Please post the work around for this problem as many people are facing up with this issue

**Comment by jigtest** [comment]
Hi @freynaud,
I am also facing this issue. I am using Xcode 6.3.2 and built jar file after cloning from the repository.
I even tried and increased the timeout to 60 secs but it is not working. The browser doesn't open up even though the iPhone simulator launches.
Kindly help me out as I am stuck with this problem for quite some time now.

Thanks.
