### ISSUE TITLE
Same CFBundleVersion for different safari versions ?

### ISSUE THREAD

**Issue by ainthek** [ios-driver/ios-driver#227]
<pre>
Somehow after downgrading Xcode and reinstalling simulators I have ended up with browsers (simulators):
Applications :
---------------
    CFBundleName=Safari,CFBundleVersion=8536.25,/Users/user/.ios-driver/safariCopies/safari-6.1.app
    CFBundleName=Safari,CFBundleVersion=9537.53,/Users/user/.ios-driver/safariCopies/safari-7.0.3.app
    CFBundleName=Safari,CFBundleVersion=9537.53,/Users/user/.ios-driver/safariCopies/safari-7.1.app

and after running against this server I end up with:

1:58:811 WARNING ApplicationCrashListener.hasApplicationCrashed  log from crash 2014-03-11 22:11:57 +0000 Fail: The target application appears to have died
Exception in thread "Thread-99" org.openqa.selenium.WebDriverException: error waiting for [kill, -9, 4857] to finish.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_45'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.utils.Command.waitFor(Command.java:113)
    at org.uiautomation.ios.utils.Command.executeAndWait(Command.java:59)
    at org.uiautomation.ios.utils.ClassicCommands.kill(ClassicCommands.java:204)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.stop(InstrumentsApple.java:173)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.stop(InstrumentsBackedNativeIOSDriver.java:53)
    at org.uiautomation.ios.server.services.IOSDualDriver.stop(IOSDualDriver.java:51)
    at org.uiautomation.ios.server.ServerSideSession.stop(ServerSideSession.java:240)
    at org.uiautomation.ios.server.ServerSideSession.sessionHasCrashed(ServerSideSession.java:211)
    at org.uiautomation.ios.utils.ApplicationCrashListener.hasApplicationCrashed(ApplicationCrashListener.java:45)
    at org.uiautomation.ios.utils.ApplicationCrashListener.stdout(ApplicationCrashListener.java:33)
    at org.uiautomation.ios.utils.Command.add(Command.java:160)
    at org.uiautomation.ios.utils.Command.access$200(Command.java:27)
    at org.uiautomation.ios.utils.Command$2.run(Command.java:137)
Caused by: java.lang.InterruptedException
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:503)
    at java.lang.UNIXProcess.waitFor(UNIXProcess.java:210)
    at org.uiautomation.ios.utils.Command.waitFor(Command.java:111)
    ... 12 more

</pre>

**Comment by freynaud** [comment]
what version of xcode are you running now ? ( you should run 5.1 ).
It's normal to have multiple safari with the same version. You can have multiple SDK version with the same safari build inside.

**Comment by darraghgrace** [comment]
No activity on this issue for 2 months so i'm going to close. Please re-open if you are still having problems
