### ISSUE TITLE
Problem running in real device

### ISSUE THREAD

**Issue by vinsguru** [ios-driver/ios-driver#255]
Hi,

I am running a very simple test to Launch Safari & open "http://www.ebay.co.uk/"
I am able to run successfully on IOS simulator with IOS driver -ios-server-standalone-0.6.6-SNAPSHOT.jar

But the same test is not working on real device.

I am starting the server like this

java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -beta -aut /Users/qalab/Documents/workspace/IOS/app/InternationalMountains.app -port 5555

It is able to identify the connected device.
http://0.0.0.0:5555/wd/hub/devices/all - shows my device info

"
iPad3,3 IOS:7.1.1(UGONZR8’s iPad)
Device info:

name: UGGGGG8’s iPad
id: 4fe329b5c01GGGGGGGG7c8f69d48f7ce
type: ipad
build: 11D201
product: iPad3,3
SDK: 7.1.1
Applications:

com.pearsoned.BOSS"

This is the code

```
       DesiredCapabilities safari = IOSCapabilities.ipad("Safari");
   safari.setCapability(IOSCapabilities.SIMULATOR, false); 
    RemoteWebDriver driver=null;
    try {
        driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), safari);
    } catch (MalformedURLException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }

    driver.get("http://www.ebay.co.uk/");

    System.out.println(driver.getTitle());
    driver.quit();
```

However it throws an exception that desired app not found.!!

Is it because of IOS 7.1.1??

Any idea on how to resolve this error?

**Comment by leo-13** [comment]
I'm getting the same issue. Here is the description of the error:
Caused by: org.openqa.selenium.SessionNotCreatedException: desired app not found on server: {simulator=false, timeHack=false, variation=Regular, locale=en_GB, CFBundleName=Safari, device=ipad, language=en}.
    Available apps: [com.apple.mobilesafari::8536.25, CFBundleName=Safari,CFBundleVersion=9537.53,/Users/FollettTester/.ios-driver/safariCopies/safari-7.1.app]

Checked on iOS 6 as well - same problem. Can anyone please look into this?

**Comment by richard-stowe** [comment]
Can you try changing:

``` java
DesiredCapabilities safari = IOSCapabilities.ipad("Safari");
```

to:

``` java
DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
```

Even though you are running tests on an iPad.

Also, IOS-Driver cannot currently launch Safari so there is a prerequisite that it is already open on the device. I believe this is currently being addressed by the dev team.

Here is a snippet of code that works perfectly for me (the device is an iPad 2):

``` java
 IOSCapabilities capabilities = IOSCapabilities.iphone("Safari");
 capabilities.setCapability(IOSCapabilities.SIMULATOR, false);
 capabilities.setCapability(IOSCapabilities.UUID, "be90b4d6fc95c0218e047040f708f0abb08492b9");
 capabilities.setCapability("javascriptEnabled", true);

RemoteIOSDriver webDriver = new RemoteIOSDriver(new URL("http://10.30.9.48:5555/wd/hub"), capabilities);

 try {
     webDriver.get("http://www.google.com/");
 } catch (Exception e) {
     e.printStackTrace();
 } finally {
     webDriver.quit();
 }
```

**Comment by leo-13** [comment]
Thank you! It worked. the important thing is UUID, cause it doesn't start without it. It would be nice to have all this information somewhere in the documentation.

**Comment by venkateshseerapu** [comment]
Hi Richard,
I am trying to open the safari browser by itself when running the script, but it doesn't. When i opened the safari browser and run the script it works. Could you please help in this issue.. 
Venkatesh

**Comment by jigtest** [comment]
Hi,
The Safari browser opens but google.com is not opened (i.e. only about:blank page is displayed). The following code (as suggested by @richard-stowe ) on a real device (iPhone 6 plus) is used:

IOSCapabilities capabilities = IOSCapabilities.iphone("Safari");
capabilities.setCapability(IOSCapabilities.SIMULATOR, false);
capabilities.setCapability(IOSCapabilities.UUID, "UUID-of-device");
capabilities.setCapability("javascriptEnabled", true);
RemoteIOSDriver webDriver=null;
try {
    webDriver = new RemoteIOSDriver(new URL("http://localhost:4444/wd/hub"), capabilities);
} catch (MalformedURLException e1) {
    // TODO Auto-generated catch block
    e1.printStackTrace();
}
try {
    webDriver.get("http://www.google.com/");
 } catch (Exception e) {
    e.printStackTrace();
} finally {
    webDriver.quit();
}

The following error is displayed:

Exception in thread "main" org.openqa.selenium.WebDriverException: is Safari started and with the focus ? 
Command duration or timeout: 22.43 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Etix-Developments-Mac-mini.local', ip: '192.168.10.157', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_45'
Driver info: org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.<init>(RemoteIOSDriver.java:94)
    at iosTesting.Test2.main(Test2.java:18)

Any help solving this error would be appreciated.
Hey @venkateshseerapu  could you share the code you used to run it on real device?

Thanks.
