### ISSUE TITLE
instruments crashed (20 SEC) iOS Driver

### ISSUE THREAD

**Issue by OmerObaid** [ios-driver/ios-driver#258]
Hey,
Im following this tutorial: http://ios-driver.github.io/ios-driver/?page=native

when i run my JAVA code simulator start and after few seconds  this happen 
55:31:832 WARNING InstrumentsApple.start  instruments crashed (20 SEC)
55:32:654 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
55:39:253 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000   Instruments : template : file://localhost/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
55:40:014 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000   Instruments : Plugin Search Paths (
55:40:014 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000       "/var/root/Library/Application Support/Instruments/PlugIns",
55:40:015 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000       "/Library/Application Support/Instruments/PlugIns",
55:40:015 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000       "/Applications/Xcode.app/Contents/Developer/usr/PlugIns",
55:40:015 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000       "/Applications/Xcode.app/Contents/Developer/usr/bin/PlugIns",
55:40:015 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000       "/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns",
55:40:016 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000       "/Applications/Xcode.app/Contents/Developer/Library/Instruments/PlugIns",
55:40:016 WARNING DefaultCommandListener.stderr  /var/folders/zz/zyxvpxvq6csfxvn_n0000000       "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Instruments/PlugIns"

my JAVA code is:

public class UiAutoMation {

```
public static void main(String[] args) throws MalformedURLException {
    // TODO Auto-generated method stub
    System.out.println("Hello Omer");

    DesiredCapabilities cap = IOSCapabilities.iphone("InternationalMountains", "1.1");
    // start the application
    RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), cap);

    // check that the 9 mountains of the app are there.
    List<WebElement> cells = driver.findElements(By.className("UIATableCell"));
```

//      Assert.assertEquals(9,cells.size());

```
    // get the 1st mountain
    WebElement first = cells.get(0);
    first.click();
```

}

Any suggestions why this is happening 

Regards,
Omer Obaid.

**Comment by freynaud** [comment]
can you confirm that both xcode and instruments are closed when this error happens ?

**Comment by Jijovkm** [comment]
I also face through the same problem.. when i run the internationalmountains.app, it works fine. But i build internationalmountains from the source code given by apple and run it faces the above issue. yes i closed the xcode and instruments...

**Comment by Jijovkm** [comment]
46:59:880 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/ushus/Automation/applications' for new applications
Archived apps: /Users/ushus/Automation/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140512-1111,sha:3200431291ad1b53ecb4d539dfde6e56e44a212d)
Running on: Mac OS X 10.8.5 (x86_64)
Using java: 1.7.0_55
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.1.1, build: 55045
Using iOS version 7.1
iOS >= 6.0. Safari and hybrid apps are supported.

## Applications :

```
CFBundleName=InternationalMountains,CFBundleVersion=1.1,/Users/Automation/InternationalMountains.app
CFBundleName=Safari,CFBundleVersion=8536.25,/Users/.ios-driver/safariCopies/safari-6.0.app
CFBundleName=Safari,CFBundleVersion=9537.53,/Users/.ios-driver/safariCopies/safari-7.1.app
```

2014-05-23 11:46:59.948:INFO::jetty-7.x.y-SNAPSHOT
2014-05-23 11:47:00.065:INFO::Started SelectChannelConnector@0.0.0.0:5555
20
47:31:883 WARNING InstrumentsApple.start  instruments crashed (20 SEC)
47:31:936 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
48:14:965 WARNING InstrumentsApple.start  instruments crashed (40 SEC)
48:15:016 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 40sec):Didn't get the capability back.Most likely, instruments crashed at startup.
49:18:068 WARNING InstrumentsApple.start  instruments crashed (60 SEC)
49:18:115 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 60sec):Didn't get the capability back.Most likely, instruments crashed at startup.
org.openqa.selenium.SessionNotCreatedException: failed starting after 3retries.Final wait was 80
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'MacBook-Pro.local', ip: '192.168.243.114', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_55'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:62)

**Comment by freynaud** [comment]
Can you check that you don't have any process "sim_" or "instruments_" left over ?

When you build, you should build for testing. Product > Profile is howI generated the app that works for you

**Comment by Jijovkm** [comment]
HI freynaud, I build the app using Product-> Profile and allow instruments to run process. After that i Copy the .app file using xcode (show in finder) and pasted in preferred location. and i quit xcode, simulator and instruments. Then using the terminal i execute

java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut testapp.app -port 5555

In terminal result was:

50:52:245 INFO ApplicationStore.<init>  App archive folder:/Users/Automation/applications
50:54:138 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/ushus/Automation/applications' for new applications
Archived apps: /Users/ushus/Automation/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140512-1111,sha:3200431291ad1b53ecb4d539dfde6e56e44a212d)
Running on: Mac OS X 10.8.5 (x86_64)
Using java: 1.7.0_55
Using Xcode install: /Applications/Xcode.app
Using instruments: version:5.1.1, build: 55045
Using iOS version 7.1
iOS >= 6.0. Safari and hybrid apps are supported.

## Applications :

```
CFBundleName=Bike,CFBundleVersion=2.1,/Users/Automation/testapp.app
CFBundleName=Safari,CFBundleVersion=8536.25,/Users/.ios-driver/safariCopies/safari-6.0.app
CFBundleName=Safari,CFBundleVersion=9537.53,/Users/.ios-driver/safariCopies/safari-7.1.app
```

2014-05-23 14:50:54.207:INFO::jetty-7.x.y-SNAPSHOT
2014-05-23 14:50:54.334:INFO::Started SelectChannelConnector@0.0.0.0:5555

And i exceute the Java Code 

```
    DesiredCapabilities cap = IOSCapabilities.iphone("testapp", "2.1");
    cap.setCapability(IOSCapabilities.SIMULATOR, true);
    cap.setCapability(IOSCapabilities.LANGUAGE, "en");
     RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), cap);
    System.out.println(driver.getTitle());
    System.out.println("Driver Started");
```

Result in terminal was

51:30:657 WARNING InstrumentsApple.start  instruments crashed (20 SEC)
51:30:707 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
52:13:742 WARNING InstrumentsApple.start  instruments crashed (40 SEC)
52:13:790 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 40sec):Didn't get the capability back.Most likely, instruments crashed at startup.
53:16:811 WARNING InstrumentsApple.start  instruments crashed (60 SEC)
53:16:858 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 60sec):Didn't get the capability back.Most likely, instruments crashed at startup.
org.openqa.selenium.SessionNotCreatedException: failed starting after 3retries.Final wait was 80
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'ushustechs-MacBook-Pro.local', ip: '192.168.243.114', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_55'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:62)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:151)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:82)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:745)

Please help me for this
I am using Xode 5.1.1, Mac OSX 10.8.5

**Comment by lolemouine** [comment]
I tried : 
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut /Users/testautomation/Documents/whateverisyourapp.app -port 7777 -newSessionTimeoutSec 60

It gives more time for the app to open, but my application opens partially until it fails after 10 sec from my poiint of view. 

What could be the error in my case ?

**Comment by Jijovkm** [comment]
What was the error raised in the terminal??

**Comment by samirdambhe** [comment]
I am facing the same issue  
this is what is get on terminal. 

2015-02-19 12:49:14.711:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2015-02-19 12:49:14.763:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0 <mailto:SelectChannelConnector@0.0.0.0>:4444
49:49:492 INFO APPIOSApplication.canRun The application doesn't have any content files. Localization related features won't be available.
50:12:778 WARNING InstrumentsCommandLine.start instruments crashed (20 SEC)
50:12:809 WARNING NewSessionNHandler.safeStart Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
50:12:846 WARNING NewSessionNHandler.safeStart app has crashed at startup :normal
50:12:847 INFO APPIOSApplication.canRun The application doesn't have any content files. Localization related features won't be available.

**Comment by samirdambhe** [comment]
I am facing the same issue

this is what is get on terminal.

2015-02-19 12:49:14.711:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2015-02-19 12:49:14.763:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0 SelectChannelConnector@0.0.0.0:4444
49:49:492 INFO APPIOSApplication.canRun The application doesn't have any content files. Localization related features won't be available.
50:12:778 WARNING InstrumentsCommandLine.start instruments crashed (20 SEC)
50:12:809 WARNING NewSessionNHandler.safeStart Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
50:12:846 WARNING NewSessionNHandler.safeStart app has crashed at startup :normal
50:12:847 INFO APPIOSApplication.canRun The application doesn't have any content files. Localization related features won't be available.
