### ISSUE TITLE
getting started docs

### ISSUE THREAD

**Issue by tcurdt** [ios-driver/ios-driver#259]
Great - so I have the server running but now what?

If someone could write up (or link to) some docs on getting started with ios-driver - that would be fantastic.

**Comment by SGDSmith** [comment]
Have you downloaded WebDriver? 
Do you have maven installed on your machine?

I would start off with the Native app guide here: http://ios-driver.github.io/ios-driver/?page=native#debugElement

**Comment by tcurdt** [comment]
What's WebDriver? I only want to test a native app.

I have maven installed but couldn't figure out from the docs if java is really the only language to write the tests. Looks like it - except for loading UIAutomation scripts.

There is no test runner infrastructure? Just plain `void main`?

Is there a demo project somewhere?

**Comment by SGDSmith** [comment]
You can write tests using any of the Selenium WebDriver Language bindings (as far as I know). 

If you are OK with using JAVA then I would do the following:
1. Download the iOS-driver snapshot   (Not sure how up to date the one on the homepage is, you may wish to build it yourself using maven... Let me know if you need to know how to do this).
2. Download the sample app file  InternationalMountains.app
3. Start the server in the terminal by executing the following:    java -jar {path to ios-driver} -aut {path to app}  -port {desired port}
4. Copy the sample code from this page http://ios-driver.github.io/ios-driver/?page=native  and paste it in to whichever editor/IDE you wish to use (I use Eclipse but anything should do)

---

If using Eclipse and Java then just do the following:
- Create a new Java Project
- Add an External JAR to the Build Path of the project  (add your ios-server jar file)
- Create a java class and paste the code from the page listed above
- Import the necessary classes (may need to import jUnit or TestNG for the Assert in the code)

Sample code is below:
package src; 

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.Augmenter;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.uiautomation.ios.*;
import org.testng.Assert;

public class iOSTest {

public static void main(String[] args) throws MalformedURLException {
    // create a selenium desiredCapabilities object with the right values.
    DesiredCapabilities cap = IOSCapabilities.iphone("InternationalMountains", "1.1");
    // start the application
    RemoteWebDriver driver = new RemoteWebDriver(new URL("http://0.0.0.0:4444/wd/hub"), cap);

```
// check that the 9 mountains of the app are there.
List<WebElement> cells = driver.findElements(By.className("UIATableCell"));
Assert.assertEquals(9,cells.size());


// get the 1st mountain
WebElement first = cells.get(0);
first.click();

// take a screenshot using the normal selenium api.
TakesScreenshot screen =(TakesScreenshot)new Augmenter().augment(driver);
File ss = new File("screenshot.png");
screen.getScreenshotAs(OutputType.FILE).renameTo(ss);
System.out.println("screenshot take :"+ss.getAbsolutePath());

// access the content
By selector = By.xpath("//UIAStaticText[contains(@name,'climbed')]");
WebElement text = driver.findElement(selector);
System.out.println(text.getAttribute("name"));

//Return to the Main Menu
WebElement menu1 = driver.findElement(By.xpath("//UIAButton[@name='Mountains']"));
menu1.click();
try {
    Thread.sleep(10000);
} catch (InterruptedException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}

//get the 2nd mountain
WebElement second = cells.get(1);
second.click();

try {
    Thread.sleep(1000);
} catch (InterruptedException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}

//Return to the Main Menu
WebElement menu2 = driver.findElement(By.xpath("//UIAButton[@label='Mountains']"));
menu2.click();
System.out.println("Pressed the second navigation button");
try {
    Thread.sleep(10000);
} catch (InterruptedException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}

// end the test
driver.quit();
```

}
}

Start the ios-driver sever on port 4444 (or modify the above code) and then run the class and see what happens. The iOS simulator should open and the test should press a few of the buttons in the app.

**Comment by tcurdt** [comment]
Thanks a lot for the details. While I am capable of writing java code I so not want to write the tests in it :) (Do you do that?)

Never used Selenium before myself but sounds like when I start the ios-driver I should be able to connect with any Selenium client? Like e.g. the one from ruby?

http://stackoverflow.com/questions/3603373/how-do-i-use-selenium-with-ruby

Another option could be to write a java wrapper that delegates the actual tests to some scripting language of choice I guess.

**Comment by SGDSmith** [comment]
I come from more of a android background so yes I write my tests using JAVA.

I believe you could use the Ruby Selenium bindings if you wish to do so. Not sure if this would work (I don't really know any ruby) but https://gist.github.com/knorrium/7915988 seems to be an iOS-driver ruby example

**Comment by tcurdt** [comment]
Hm. Seems like the ios-driver build is broken.
Which branch should I use if I want to get an updated snapshot jar?

**Comment by tcurdt** [comment]
Because right now checking http://localhost:4444/wd/hub/status I don't see what's listed here: http://ios-driver.github.io/ios-driver/?page=setup but instead

```
{"message":"bug.-1\nBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'\nSystem info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_06'\nDriver info: driver.version: unknown","screen":null,"cause":{"message":"-1","screen":null,"class":"java.lang.ArrayIndexOutOfBoundsException","stackTrace":[{"fileName":"ArrayList.java","lineNumber":371,"className":"java.util.ArrayList","methodName":"elementData"},{"fileName":"ArrayList.java","lineNumber":384,"className":"java.util.ArrayList","methodName":"get"},{"fileName":"ClassicCommands.java","lineNumber":149,"className":"org.uiautomation.ios.utils.ClassicCommands","methodName":"getDefaultSDK"},{"fileName":"ServerStatusNHandler.java","lineNumber":57,"className":"org.uiautomation.ios.server.command.uiautomation.ServerStatusNHandler","methodName":"handle"},{"fileName":"BaseCommandHandler.java","lineNumber":104,"className":"org.uiautomation.ios.server.command.BaseCommandHandler","methodName":"handleAndRunDecorators"},{"fileName":"IOSServlet.java","lineNumber":151,"className":"org.uiautomation.ios.server.servlet.IOSServlet","methodName":"getResponse"},
```

**Comment by tcurdt** [comment]
Got the latest dev version to build but http://ios-driver.github.io/ios-driver/?page=setup still seems out of date.

**Comment by tcurdt** [comment]
Why is `known device` empty?

```
[remote server] org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler(NewSessionNHandler.java):75:in `handle': {locale=en_GB, CFBundleName=MyApp, device=iphone, language=en, version=7.1} no devices available. (Selenium::WebDriver::Error::WebDriverError)
    Known devices: []
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_06'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.7.0_06'
Driver info: driver.version: unknown (org.openqa.selenium.SessionNotCreatedException)
    from [remote server] org.uiautomation.ios.server.command.BaseCommandHandler(BaseCommandHandler.java):104:in `handleAndRunDecorators'
    from [remote server] org.uiautomation.ios.server.servlet.IOSServlet(IOSServlet.java):151:in `getResponse'
    from [remote server] org.uiautomation.ios.server.servlet.IOSServlet(IOSServlet.java):82:in `process'
    from [remote server] org.uiautomation.ios.server.servlet.IOSServlet(IOSServlet.java):57:in `doPost'
    from [remote server] javax.servlet.http.HttpServlet(HttpServlet.java):727:in `service'
    from [remote server] javax.servlet.http.HttpServlet(HttpServlet.java):820:in `service'
    from [remote server] org.eclipse.jetty.servlet.ServletHolder(ServletHolder.java):533:in `handle'
    from [remote server] org.eclipse.jetty.servlet.ServletHandler(ServletHandler.java):475:in `doHandle'
    from [remote server] org.eclipse.jetty.server.session.SessionHandler(SessionHandler.java):224:in `doHandle'
    from [remote server] org.eclipse.jetty.server.handler.ContextHandler(ContextHandler.java):920:in `doHandle'
    from [remote server] org.eclipse.jetty.servlet.ServletHandler(ServletHandler.java):403:in `doScope'
    from [remote server] org.eclipse.jetty.server.session.SessionHandler(SessionHandler.java):184:in `doScope'
    from [remote server] org.eclipse.jetty.server.handler.ContextHandler(ContextHandler.java):856:in `doScope'
    from [remote server] org.eclipse.jetty.server.handler.ScopedHandler(ScopedHandler.java):117:in `handle'
    from [remote server] org.eclipse.jetty.server.handler.HandlerList(HandlerList.java):47:in `handle'
    from [remote server] org.eclipse.jetty.server.handler.HandlerWrapper(HandlerWrapper.java):114:in `handle'
    from [remote server] org.eclipse.jetty.server.Server(Server.java):352:in `handle'
    from [remote server] org.eclipse.jetty.server.HttpConnection(HttpConnection.java):596:in `handleRequest'
    from [remote server] org.eclipse.jetty.server.HttpConnection$RequestHandler(HttpConnection.java):1066:in `content'
    from [remote server] org.eclipse.jetty.http.HttpParser(HttpParser.java):805:in `parseNext'
    from [remote server] org.eclipse.jetty.http.HttpParser(HttpParser.java):218:in `parseAvailable'
    from [remote server] org.eclipse.jetty.server.HttpConnection(HttpConnection.java):426:in `handle'
    from [remote server] org.eclipse.jetty.io.nio.SelectChannelEndPoint(SelectChannelEndPoint.java):510:in `handle'
    from [remote server] org.eclipse.jetty.io.nio.SelectChannelEndPoint(SelectChannelEndPoint.java):34:in `access$000'
    from [remote server] org.eclipse.jetty.io.nio.SelectChannelEndPoint$1(SelectChannelEndPoint.java):40:in `run'
    from [remote server] org.eclipse.jetty.util.thread.QueuedThreadPool$2(QueuedThreadPool.java):450:in `run'
    from [remote server] java.lang.Thread(Thread.java):722:in `run'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/response.rb:51:in `assert_ok'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/bridge.rb:634:in `raw_execute'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/bridge.rb:99:in `create_session'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/bridge.rb:68:in `initialize'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/common/driver.rb:33:in `new'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/common/driver.rb:33:in `for'
    from /Users/tcurdt/.gem/ruby/2.1.1/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver.rb:67:in `for'
    from test.rb:12:in `<main>'
```
