### ISSUE TITLE
How to start ipad simulator

### ISSUE THREAD

**Issue by asabhijitshelar** [ios-driver/ios-driver#261]
Hi,
I am sucessfully run iphone code from windows machine to mac machine in iPhone simulator. I need to run same code for iPad Simulator.

Java code on windows machine

// create a selenium desiredCapabilities object with the right values.
    // DesiredCapabilities cap = IOSCapabilities.iphone("InternationalMountains", "1.1");
        DesiredCapabilities cap = DesiredCapabilities.ipad();
        cap.setCapability(IOSCapabilities.BUNDLE_NAME,"InternationalMountains");
        cap.setCapability(IOSCapabilities.BUNDLE_VERSION,"1.1");
        cap.setCapability(CapabilityType.BROWSER_NAME, "ios");  
        cap.setCapability(CapabilityType.PLATFORM, "MAC");  
        cap.setCapability(IOSCapabilities.DEVICE, DeviceType.ipad);
        cap.setCapability(IOSCapabilities.SIMULATOR, true);
        //cap.setCapability("app","/Users/mac/Projects/InternationalMountains.app");
    // start the application
    driver = new RemoteWebDriver(new URL("http://192.168.1.28:5555/wd/hub"), cap);

I have started server on mac
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut InternationalMountains.app

How to start iPad simulator and run tests. This code works for iPhone but not for iPad. Any one Please help

uts-macs-Mac-mini:Projects mac$ java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut InternationalMountains.app
02:40:464 INFO ApplicationStore.<init>  App archive folder:/Users/mac/Projects/applications
true
02:40:519 WARNING AppleLanguage.create  crazy-language isn't recognized. Please file a bug on github. You won't be able to start the app in that language.
02:41:506 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/mac/Projects/applications' for new applications
Archived apps: /Users/mac/Projects/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140326-1201,sha:69eb457e39da8babb88070a47009ab8dceba0c6d)
Running on: Mac OS X 10.8.3 (x86_64)
Using java: 1.7.0_55
Using Xcode install: /Applications/Xcode.app
Using instruments: version:4.5, build: 46000
Using iOS version 6.1
iOS >= 6.0. Safari and hybrid apps are supported.
## Applications :

 CFBundleName=InternationalMountains,CFBundleVersion=1.1,/Users/mac/Projects/InternationalMountains.app
 CFBundleName=Safari,CFBundleVersion=8536.25,/Users/mac/.ios-driver/safariCopies/safari-6.1.app

2014-05-16 18:02:41.886:INFO::jetty-7.x.y-SNAPSHOT
2014-05-16 18:02:41.982:INFO::Started SelectChannelConnector@0.0.0.0:5555
org.openqa.selenium.SessionNotCreatedException: desired app not found on server: {platform=MAC, browserName=ios, simulator=true, locale=en_GB, CFBundleName=InternationalMountains, device=ipad, CFBundleVersion=1.1, version=}.
    Available apps: [CFBundleName=InternationalMountains,CFBundleVersion=1.1,/Users/mac/Projects/InternationalMountains.app, CFBundleName=Safari,CFBundleVersion=8536.25,/Users/mac/.ios-driver/safariCopies/safari-6.1.app]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_55'
Driver info: driver.version: unknown
 at org.uiautomation.ios.server.IOSServerManager.findAndCreateInstanceMatchingApplication(IOSServerManager.java:161)
 at org.uiautomation.ios.server.ServerSideSession.<init>(ServerSideSession.java:91)
 at org.uiautomation.ios.server.IOSServerManager.createSession(IOSServerManager.java:137)
 at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:81)
 at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:49)
 at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
 at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
 at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:81)
 at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:56)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
 at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
 at org.eclipse.jetty.server.Server.handle(Server.java:352)
 at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
 at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
 at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
 at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
 at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
 at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
 at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
 at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
 at java.lang.Thread.run(Thread.java:745)

I have already search but that solution is for real device. Is it problem with this InternationalMountains.app file or for other apps also

**Comment by bijoyv** [comment]
Can you please check if InternationalMountain application is built to run in iPad also

**Comment by mach6** [comment]
please follow up on @bijoyv comment and re-open if needed.
