### ISSUE TITLE
getCurrentUrl for a webview throws NullPointerException when the page is transitioning

### ISSUE THREAD

**Issue by waltercacau** [ios-driver/ios-driver#268]
Version: Built from the dev branch at commit dcba05ab55f3debbc7fb7246c9eeb86f53b83f7b

Context: In some of my tests containing a webview, I wait for the URL to change to a particular expected URL. Fairly often the getCurrentUrl call just throws a NullPointerException.

The following is the output printed out by the iOS Driver standalone java server when this happens:

```
Driver info: driver.version: RemoteIOSWebDriver. Retrying ...
org.uiautomation.ios.wkrdp.WebKitSeemsCorruptedException: Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '[REDACTED]', ip: '[REDACTED]', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.3', java.version: '1.7.0_55'
Driver info: driver.version: RemoteIOSWebDriver
    at org.uiautomation.ios.wkrdp.BaseWebInspector.retrieveDocumentAndCheckReady(BaseWebInspector.java:108)
    at org.uiautomation.ios.wkrdp.BaseWebInspector.getDocument(BaseWebInspector.java:78)
    at org.uiautomation.ios.wkrdp.BaseWebInspector.getDocument(BaseWebInspector.java:72)
    at org.uiautomation.ios.wkrdp.BaseWebInspector.getCurrentUrlOnce(BaseWebInspector.java:157)
    at org.uiautomation.ios.wkrdp.BaseWebInspector.getCurrentUrl(BaseWebInspector.java:143)
    at org.uiautomation.ios.drivers.RemoteIOSWebDriver.getCurrentUrl(RemoteIOSWebDriver.java:224)
    at org.uiautomation.ios.command.web.GetURL.handle(GetURL.java:31)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:103)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse(IOSServlet.java:151)
    at org.uiautomation.ios.servlet.IOSServlet.process(IOSServlet.java:82)
    at org.uiautomation.ios.servlet.IOSServlet.doGet(IOSServlet.java:47)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:745)
```

Any ideas? I am still investigating and will post any findings.

Thanks,

Walter

**Comment by waltercacau** [comment]
This seems to be the culprit: [RemoteIOSWebDriver#getCurrentUrl catch block](https://github.com/ios-driver/ios-driver/blob/dcba05ab55f3debbc7fb7246c9eeb86f53b83f7b/server/src/main/java/org/uiautomation/ios/drivers/RemoteIOSWebDriver.java#L226)

At some point during the getCurrentUrl call, the wkrdp BaseWebInspector throws a WebKitSeemsCorruptedException. This should theoretically trigger a restart of iOS Driver webkit related classes (see [BaseCommandHandler#handleAndRunDecorators](https://github.com/ios-driver/ios-driver/blob/dcba05ab55f3debbc7fb7246c9eeb86f53b83f7b/server/src/main/java/org/uiautomation/ios/command/BaseCommandHandler.java#L104)). But it does not because getCurrentUrl catches all exceptions and doesn't rethrow them. There seems to be some other methods in RemoteIOSWebDriver.java that do the same and therefore could be affected by this behavior (e.g. forward and refresh).

Removing the catch block solves the problem for me. What do you think? Should this catch block be preserved, removed, or modified to rethrow just this particular exception?

**Comment by Ragnaroek** [comment]
I'm also getting a NPE in the getCurrentUrl call:

java.lang.NullPointerException
    at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:315)
    at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:73)
    at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:61)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
    at geb.Browser.go(Browser.groovy:394)
    at geb.Browser$go.call(Unknown Source)
    at geb.Page.to(Page.groovy:184)
