### ISSUE TITLE
Issue in running automation test case using appium on real devices

### ISSUE THREAD

**Issue by sesudhanshu** [ios-driver/ios-driver#284]
Hi I used below code to run my test on ios device. I am using appium.app to pass all the capabilities to run the tests on real devices.

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("device","iPhone");
capabilities.setCapability("platformName","iOS");
capabilities.setCapability("platformVersion","7.1");
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
driver.get("http://www.google.com");

I keep getting below exception ;
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: spawn ENOENT) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 263 milliseconds
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'pun-srivasts-m.ds.ad.adp.com', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at MobileAndroidTest.testHoldenMobile(MobileAndroidTest.java:129)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

![screen shot 2014-08-29 at 11 00 31 pm](https://cloud.githubusercontent.com/assets/8521010/4093872/f9f17ea2-2fa1-11e4-94f8-d59dbe725e17.png)

![screen shot 2014-08-29 at 11 01 49 pm](https://cloud.githubusercontent.com/assets/8521010/4093883/128a4a70-2fa2-11e4-8f69-a56fbb54f842.png)

**Comment by sesudhanshu** [comment]
Also when i check http://localhost:4723/wd/hub/session. get below message

{"status":13,"value":"ERROR running Appium command: Cannot read property 'capabilities' of null"}
