### ISSUE TITLE
IOS8 Xcode 6 beta7 support 

### ISSUE THREAD

**Issue by mdiwakar** [ios-driver/ios-driver#286]
I see current support for Xcode on ios-server is till Support for Xcode 5.1.1, please add IOS8  Xcode 6 beta 7

I see a branch created for Xcode6 
https://github.com/facebook/instruments-without-delay/tree/fix-xcode-6

**Comment by mmmulani** [comment]
hey, I merged that branch back onto the dev branch last week.
You should be able to use Xcode 6 with ios-driver, though I found it was too slow to use normally.

**Comment by mdiwakar** [comment]
Thanks  I will check and update

**Comment by mdiwakar** [comment]
I am getting the following error 
35:45:644 WARNING NewSessionNHandler.safeStart  app has crashed at startup :normal
35:50:036 INFO IOSSafariSimulatorManager.copySafariToAllowInstallByInstruments  temporarily moving MobileSafari out of the install directory, if you need to restore it yourself use:
$ cp -rf /Users/hudson/.ios-driver/safariCopies/MobileSafari-8.0.app /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/Applications/MobileSafari.app
36:06:298 WARNING NewSessionNHandler.safeStart  Error starting the session.session created but application size=2.It should be 1. Do you have multiple tabs opened ?

**Comment by ChrisGoodnight** [comment]
I get the same error 
36:06:298 WARNING NewSessionNHandler.safeStart Error starting the session.session created but application size=2.It should be 1. Do you have multiple tabs opened ?
 Works on Xcode 5.1

**Comment by devkumar314** [comment]
I am getting the same issue.
I am using xCode 6.
Any Help?  How i can make it work....

**Comment by bijoyv** [comment]
Can you please try the latest code from dev branch, and update if it is an issue still

**Comment by azaytsev** [comment]
@bijoyv It's still an issue. I'm currently using xCode6 and latest code from dev and 7 out of 10 times I'll see this error message

**Comment by mdiwakar** [comment]
I am not getting the earlier mentioned error now, however it seems application is crashing. is anyone able to run tests on IOS 8?

Beta features enabled (enabled by -real flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:4444/inspector/
Tests can access the server at http://0.0.0.0:4444/wd/hub
Server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring 'applications' for new applications
Archived apps: /Users/hudson/ios-driver/server/applications
Build info: running from source located at: /Users/hudson/ios-driver
Running on: Mac OS X 10.9.5 (x86_64)
Using java: 1.7.0_51
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.1, build: 56160
Using iOS version 8.1
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
    CFBundleName=UICatalog,CFBundleVersion=2.10,/Users/hudson/ios-driver/server/target/test-classes/sampleApps/UICatalog.app
    CFBundleName=UICatalog,CFBundleVersion=2.10,/Users/hudson/ios-driver/server/target/test-classes/sampleApps/UICatalogiPad.app
    CFBundleName=Geocoder,CFBundleVersion=1.2,/Users/hudson/ios-driver/server/target/test-classes/sampleApps/Geocoder.app
    CFBundleName=InternationalMountains,CFBundleVersion=1.1,/Users/hudson/ios-driver/server/target/test-classes/sampleApps/InternationalMountains.app
    CFBundleName=testNoContent,CFBundleVersion=1.0,/Users/hudson/ios-driver/server/target/test-classes/sampleApps/testNoContent.app
    CFBundleName=PPNQASampleApp,CFBundleVersion=1.0,/Users/hudson/ios-driver/server/target/test-classes/sampleApps/PPNQASampleApp.app
    CFBundleName=Safari,CFBundleVersion=600.1.4,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/Applications/MobileSafari.app
2014-10-28 17:23:59.948:INFO:oejs.Server:jetty-8.1.14.v20131031
2014-10-28 17:24:00.025:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4444
24:10:138 WARNING ApplicationCrashMonitor.hasApplicationCrashed  log from crash 2014-10-29 00:24:10 +0000 Fail: The target application appears to have died
24:10:158 WARNING InstrumentsCommandLine.stop  couldn't kill 1766
24:44:443 WARNING InstrumentsCommandLine.start  instruments crashed (40 SEC)
24:44:485 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
24:44:486 WARNING NewSessionNHandler.safeStart  app has crashed at startup :crash
24:52:135 WARNING ApplicationCrashMonitor.hasApplicationCrashed  log from crash 2014-10-29 00:24:52 +0000 Fail: The target application appears to have died
24:52:153 WARNING InstrumentsCommandLine.stop  couldn't kill 1850

**Comment by sandeepnagra** [comment]
I get following error with XCODE 6.1 & iOS 8.1

06:31:586 INFO ApplicationStore.<init>  App archive folder:/Users/sandeep.singh/Desktop/iOS-driver/applications
06:31:632 FINE IOSServer.p  version:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560
06:31:632 FINE IOSServer.p  Beta features enabled (enabled by -real flag): false
06:31:632 FINE IOSServer.p  Simulator enabled : true
06:31:633 FINE IOSServer.p  Inspector: http://0.0.0.0:3001/inspector/
06:31:633 FINE IOSServer.p  Tests can access the server at http://0.0.0.0:3001/wd/hub
06:31:634 FINE IOSServer.p  Server status: http://0.0.0.0:3001/wd/hub/status
06:31:634 FINE IOSServer.p  Connected devices: http://0.0.0.0:3001/wd/hub/devices/all
06:31:634 FINE IOSServer.p  Applications: http://0.0.0.0:3001/wd/hub/applications/all
06:31:635 FINE IOSServer.p  Capabilities: http://0.0.0.0:3001/wd/hub/capabilities/all
06:31:635 FINE IOSServer.p  Monitoring '/Users/sandeep.singh/Desktop/iOS-driver/applications' for new applications
06:31:636 FINE IOSServer.p  Archived apps: /Users/sandeep.singh/Desktop/iOS-driver/applications
06:31:636 FINE IOSServer.p  Build info: ios-driver 0.6.6-SNAPSHOT (built:20141009-1559,sha:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560)
06:31:636 FINE IOSServer.p  Running on: Mac OS X 10.9.5 (x86_64)
06:31:637 FINE IOSServer.p  Using java: 1.7.0_71
06:31:637 FINE IOSServer.p  Using Xcode install: /Applications/Xcode.app
06:31:637 FINE IOSServer.p  Using instruments: version:6.1, build: 56160
06:31:637 FINE IOSServer.p  Using iOS version 8.1
06:34:116 FINE IOSServer.p  iOS >= 6.0. Safari and hybrid apps are supported.
06:34:116 FINE IOSServer.p  Applications :
06:34:116 FINE IOSServer.p      CFBundleName=Safari,CFBundleVersion=9537.53,/Users/sandeep.singh/.ios-driver/safariCopies/safari-7.1.app
06:34:117 FINE IOSServer.p      CFBundleName=Safari,CFBundleVersion=600.1.4,/Users/sandeep.singh/.ios-driver/safariCopies/safari-8.1.app
06:49:302 INFO NewSessionNHandler.safeStart  The server cannot run Capabilities [{platform=MAC, cssSelectorsEnabled=false, CFBundleIdentifier=com.apple.mobilesafari, javascriptEnabled=true, nativeEvents=false, locale=en_GB, CFBundleName=Safari, variation=iPhone5s, device=iphone, rotatable=false, takesScreenshot=false, sdkVersion=8.1, version=}] at the moment.org.uiautomation.ios.application.APPIOSApplication cannot be cast to org.uiautomation.ios.application.IPAApplication
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'macloaner002mc-l.local', ip: '192.168.22.164', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_71'
Driver info: driver.version: unknown
07:05:728 INFO NewSessionNHandler.safeStart  The server cannot run Capabilities [{platform=MAC, cssSelectorsEnabled=false, CFBundleIdentifier=com.apple.mobilesafari, javascriptEnabled=true, nativeEvents=false, locale=en_GB, CFBundleName=Safari, variation=Retina, device=ipad, rotatable=false, takesScreenshot=false, sdkVersion=8.1, version=}] at the moment.org.uiautomation.ios.application.APPIOSApplication cannot be cast to org.uiautomation.ios.application.IPAApplication
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'macloaner002mc-l.local', ip: '192.168.22.164', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_71'
Driver info: driver.version: unknown

**Comment by bijoyv** [comment]
I'm able to run moble safari applications 50% of the times, when the internet connection is very good with iOS 8.1 and xcode 6.1
I was using the simulator everytime
@sandeepnagra
Do you have any real device attached when trying this (if so, is it with latest update of software), I'm curious on the way it selects an app that ends with .ipa instead of .app

**Comment by ChrisGoodnight** [comment]
I was able to get things working using xcode 6.1 and os7.1 on an actual device and simulator after building with the latest ios-driver dev code.  However, at the request of our developer I upgraded the device to OS 8.1 (which is irreversible!) and now I get 

Selenium::WebDriver::Error::UnknownError: session created but application size=3.It should be 1. Do you have multiple tabs opened ? (org.openqa.selenium.WebDriverException)

The jar's output

> java -jar ios-server-standalone-0.6.6-SNAPSHOT-ad6762adff7fcdbf38dd4c8d9b9fd62d62f125cc-jar-with-dependencies.jar -beta -port 5555

54:38:356 INFO ApplicationStore.<init>  App archive folder:/Users/user/Downloads/applications
version:ad6762adff7fcdbf38dd4c8d9b9fd62d62f125cc
Beta features enabled (enabled by -real flag): true
Simulator enabled : true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring 'xxxxxxxxxxxxxx'
Archived apps: xxxxxxxxxx
Build info: ios-driver 0.6.6-SNAPSHOT (built:2014-11-12T23:05:57Z,sha:ad6762adff7fcdbf38dd4c8d9b9fd62d62f125cc)
Running on: Mac OS X 10.9.5 (x86_64)
Using java: 1.7.0_71
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.1, build: 56160
Using iOS version 8.1
54:39:327 INFO DeviceStore.onDeviceAdded  new device detected (126650254872bc9fc56be8d92a12e2398aa01425) QA iPad Mini
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
    CFBundleName=Safari,CFBundleVersion=600.1.4,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/Applications/MobileSafari.app
2014-11-13 08:54:39.554:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2014-11-13 08:54:39.647:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:5555
54:39:967 INFO DeviceStore.onDeviceAdded  device QA iPad Mini = safari 600.1.4
55:19:965 INFO APPIOSApplication.canRun  The application doesn't have any content files. Localization related features won't be available.
Cannot parse line (is it a full line ?)
Cannot parse line (is it a full line ?)
55:32:079 WARNING NewSessionNHandler.safeStart  Error starting the session.session created but application size=3.It should be 1. Do you have multiple tabs opened ?

Driver info: driver.version: IOSDualDriver
Exception in thread "DefaultMessageHandler-5" org.openqa.selenium.WebDriverException: You need to call register and connect first.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
'x86_64', os.version: '10.9.5', java.version: '1.7.0_71'
Driver info: driver.version: RemoteIOSWebDriver
    at org.uiautomation.ios.wkrdp.internal.WebKitRemoteDebugProtocol.attachToPage(WebKitRemoteDebugProtocol.java:128)
    at org.uiautomation.ios.drivers.RemoteIOSWebDriver.connect(RemoteIOSWebDriver.java:221)
    at org.uiautomation.ios.drivers.RemoteIOSWebDriver.switchTo(RemoteIOSWebDriver.java:213)
    at org.uiautomation.ios.wkrdp.WebKitNotificationListener.onMessage(WebKitNotificationListener.java:125)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.process(DefaultMessageHandler.java:78)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.access$000(DefaultMessageHandler.java:37)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler$1.run(DefaultMessageHandler.java:66)
55:32:143 WARNING WebKitRemoteDebugProtocol$1.run  listener threadjava.lang.IllegalStateException: stopped
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.handle(DefaultMessageHandler.java:60)
    at org.uiautomation.ios.wkrdp.internal.RealDeviceProtocolImpl.read(RealDeviceProtocolImpl.java:71)
    at org.uiautomation.ios.wkrdp.internal.WebKitRemoteDebugProtocol$1.run(WebKitRemoteDebugProtocol.java:74)
    at java.lang.Thread.run(Thread.java:745)

55:32:183 WARNING NewSessionNHandler.safeStart  app has crashed at startup :normal
Cannot parse line (is it a full line ?)Nov 13 08:55:25 QA-iPad-Mini com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-320.2.89
Cannot parse line (is it a full line ?) [522] <Warning>: debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-320.2.89
Cannot parse line (is it a full line ?)  for arm64.
Cannot parse line (is it a full line ?)Nov 13 08:55:25 QA-iPad-Mini com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-320.2.89
Cannot parse line (is it a full line ?) [522] <Warning>: Connecting to com.apple.debugserver service...
Cannot parse line (is it a full line ?)Nov 13 08:55:25 QA-iPad-Mini com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-320.2.89
Cannot parse line (is it a full line ?) [522] <Warning>: Got a connection, waiting for process information for launching or attaching.
Cannot parse line (is it a full line ?)Nov 13 08:55:26 QA-iPad-Mini com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-320.2.89
Cannot parse line (is it a full line ?) [524] <Warning>: debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-320.2.89
Cannot parse line (is it a full line ?)  for arm64.
Cannot parse line (is it a full line ?)Nov 13 08:55:26 QA-iPad-Mini com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-320.2.89
Cannot parse line (is it a full line ?) [524] <Warning>: Connecting to com.apple.debugserver service...
Cannot parse line (is it a full line ?)Nov 13 08:55:26 QA-iPad-Mini com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-320.2.89
Cannot parse line (is it a full line ?) [524] <Warning>: Got a connection, waiting for process information for launching or attaching.
Cannot parse line (is it a full line ?) ========================
Cannot parse line (is it a full line ?) ASL is here to serve you
Cannot parse line (is it a full line ?)Nov 13 08:55:27 QA-iPad-Mini com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-320.2.89
Cannot parse line (is it a full line ?) [524] <Warning>: About to launch process for bundle ID: com.apple.mobilesafari

**Comment by bijoyv** [comment]
Are you getting similar responses when you have only simulator (no real device attached)?

**Comment by ChrisGoodnight** [comment]
Simulator works ok.  Just really really slow and fails about 50% of the time.  Device always fails.  Frustrating because it worked fine with iOs 7.1

**Comment by jsfeng11111** [comment]
I also meet the same issue working in read device. iOS 8.1 and xcode 6.1

Selenium::WebDriver::Error::UnknownError: session created but application size=3.It should be 1. Do you have multiple tabs opened ? (org.openqa.selenium.WebDriverException)

is there any solutions now ?

**Comment by phoebusliang** [comment]
Same issue when I test Mobile Safari with iOS 8.1 on real devices, It works one iOS 7.1.2.

**Comment by matthewdunn** [comment]
We are also experiencing the same issue on Real devices for Safari on IOS 8.1

**Comment by mmmulani** [comment]
there are no current solutions and I do not believe anyone is actively working on one.

we need someone to fix the issues related to: Xcode 6 + iOS 8 + Safari.
if you would like to submit a Pull Request to add support for this, I would be happy to review it.

**Comment by KaustavSaikia** [comment]
Is the fix available now?

I upgaded IOS from IOS 7 to IOS 8.1 and now all my existing tests are failing. I am able to start the server but after that nothing is working. Its throwing below error:- 

38:59:658 INFO IOSServer.initDriver  
Beta features enabled (enabled by -beta flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:4444/inspector/
Tests can access the server at http://0.0.0.0:4444/wd/hub
Server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/kaustav/Documents/workspace/gecapital/applications' for new applications
Archived apps: /Users/kaustav/Documents/workspace/gecapital/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20140515-1656,sha:)
Running on: Mac OS X 10.9.5 (x86_64)
Using java: 1.7.0_55
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.1, build: 56160
Using iOS version 8.1
iOS >= 6.0. Safari and hybrid apps are supported.

## Applications :

```
CFBundleName=Safari,CFBundleVersion=600.1.4,/Users/kaustav/.ios-driver/safariCopies/safari-8.1.app
```

2015-02-17 17:38:59.917:INFO::jetty-7.x.y-SNAPSHOT
2015-02-17 17:38:59.976:INFO::Started SelectChannelConnector@0.0.0.0:4444
2015-02-17 17:38:59 INFO  iOSConfig:93 - ios server started. http://localhost:4444/wd/hub
2015-02-17 17:38:59 INFO  iOSConfig:115 - Running Test on emulator
2015-02-17 17:38:59 INFO  iOSConfig:119 - Launching iphone
2015-02-17 17:38:59 INFO  iOSConfig:149 - Launching IOSCapabilities with SIMULATOR as true
org.openqa.selenium.WebDriverException: expected 1 result for automation on instruments -s , got []
Build info: version: '2.42.0', revision: '5e824302019c86eae9c8c3ca9155e7307b410cf8', time: '2014-05-24 09:48:41'
System info: host: 'cmf-tl90.local', ip: '3.234.232.114', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_55'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.utils.ClassicCommands.getAutomationTemplate(ClassicCommands.java:113)
    at org.uiautomation.ios.server.simulator.InstrumentsApple.<init>(InstrumentsApple.java:87)
    at org.uiautomation.ios.server.services.InstrumentsFactory.getInstruments(InstrumentsFactory.java:60)
    at org.uiautomation.ios.server.InstrumentsBackedNativeIOSDriver.<init>(InstrumentsBackedNativeIOSDriver.java:33)
    at org.uiautomation.ios.server.services.IOSDualDriver.start(IOSDualDriver.java:104)
    at org.uiautomation.ios.server.ServerSideSession.start(ServerSideSession.java:235)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:85)
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:52)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:104)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:151)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:82)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:745)

Earlier these tests were working fine with IOS 7. 

I tried executing the ios-selenium-tests project too from github but its also not working, its launching the simulator and getting the below:-
Running on: Mac OS X 10.9.5 (x86_64)
Using java: 1.7.0_55
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.1, build: 56160
Using iOS version 8.1
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
    CFBundleName=Safari,CFBundleVersion=600.1.4,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/Applications/MobileSafari.app
2015-02-17 17:43:43.064:INFO:oejs.Server:jetty-8.1.14.v20131031
2015-02-17 17:43:43.067:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4444
44:06:912 WARNING InstrumentsCommandLine.start  instruments crashed (20 SEC)
44:06:969 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
44:06:994 WARNING NewSessionNHandler.safeStart  app has crashed at startup :normal
44:43:089 INFO NewSessionNHandler.safeStart  The server cannot run Capabilities [{simulator=true, CFBundleName=Safari, locale=en_GB, variation=iPhoneRetina_4inch, timeHack=false, device=iphone, language=en, instruments=true}] at the moment.{simulator=true, timeHack=false, variation=iPhoneRetina_4inch, locale=en_GB, CFBundleName=Safari, device=iphone, language=en, instruments=true} no devices available.
    Known devices: [Simulator[(sdks=[8.1])in use by ios-driver]]

Please help on this issue.
