### ISSUE TITLE
Use of org.json incompatible with latest Selenium code

### ISSUE THREAD

**Issue by greg-dennis** [ios-driver/ios-driver#301]
Selenium replaced its uses of org.json with gson in this revision:
https://code.google.com/p/selenium/source/detail?r=2997a70d5872ff1f228a833f062ea32af05dca6b

That breaks ios-driver pretty seriously. Now attempts to find elements result in a ClassCastException:

```
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {class=org.json.JSONObject, hCode=1526533815}
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
...
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
```

**Comment by freynaud** [comment]
do you have a use case to reproduce ? 
Are you mixing the server that has the old selenium with the new libs ?

**Comment by greg-dennis** [comment]
I'm building ios-driver using selenium from head. Any attempt to find on the page should result in this exception. I'll put together a test case for you if that would help.

**Comment by greg-dennis** [comment]
I hacked our internal copy of ios-driver to fix this. I added a dependency of ios-driver on gson, and right before line [106 of IOSServlet.java](https://github.com/ios-driver/ios-driver/blob/dev/server/src/main/java/org/uiautomation/ios/servlet/IOSServlet.java#L106) I added

```
 if (resp.getValue() instanceof JSONObject) {
  resp.setValue(new JsonParser().parse(resp.getValue().toString()));
}
```

This converts response values of type org.json.JSONObject to ones of type com.google.gson.JsonElement, which is the only type now supported by Selenium.

I don't think this is the "right" fix, though. I would prefer if the ios-driver server responded in a way that did not depend upon that particular json implementation used by Selenium.

**Comment by jderrien** [comment]
I can reproduce this problem with the Grid plugin (ios-grid-plugin-0.6.6-SNAPSHOT.jar) and Selenium 2.44.

It works with Selenium 2.43.1.

**Edit:**
Anyway, issue #324 was helpful to quickfix my issue, by also loading ios-server-standalone-0.6.6-SNAPSHOT.jar:

```
java -cp ios-grid-plugin-0.6.6-SNAPSHOT.jar:ios-server-standalone-0.6.6-SNAPSHOT.jar:selenium-server-standalone-2.44.0.jar org.openqa.grid.selenium.GridLauncher -role hub
```

**Comment by krmahadevan** [comment]
@mach6 
If no one has got to it, let me see if I can give this a try.

**Comment by DINESHMOHAN** [comment]
Same exception with Selenium 2.44. I have to use 2.43.1 now
