### ISSUE TITLE
Issue launching from selenium-webdriver node.js binding

### ISSUE THREAD

**Issue by grawk** [ios-driver/ios-driver#303]
I've modified the standard selenium-webdriver sample code to attempt to run some tests on the iOS simulator:

``` javascript
var webdriver = require('selenium-webdriver');
var SeleniumServer = require('selenium-webdriver/remote').SeleniumServer;
var driver = new webdriver.Builder().
    withCapabilities(webdriver.Capabilities.iphone()).
    usingServer(getServer()).
    build();
function getServer() {
    var serverUrl;
    var serverProps = {
        "args": ["-aut", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app"],
        "port": 4444
    }
    var server = new SeleniumServer('/usr/local/bin/ios-server-standalone-0.6.6-SNAPSHOT.jar', serverProps);
            server.start();
            serverUrl = server.address();

    return serverUrl;
}
driver.get('http://www.google.com');
driver.findElement(webdriver.By.name('q')).sendKeys('webdriver');
driver.findElement(webdriver.By.name('btnG')).click();
driver.wait(function() {
    return driver.getTitle().then(function(title) {
        return title === 'webdriver - Google Search';
    });
}, 1000);

driver.quit();

```

The result of attempting to run this node.js file is:

``` bash
$ node standalone.js 

/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
      throw error;
            ^
SessionNotCreatedError: The server cannot run Capabilities [{platform=MAC, CFBundleIdentifier=com.apple.mobilesafari, CFBundleName=Safari, locale=en_GB, variation=Retina4, device=iphone, sdkVersion=7.1}] at the moment.org.uiautomation.ios.application.APPIOSApplication cannot be cast to org.uiautomation.ios.application.IPAApplication
    at new bot.Error (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24
    at /Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at Builder.build (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/builder.js:294:22)
    at Object.<anonymous> (/Users/medelman/src/_nemo/o/nemo-mobile-example/standalone.js:6:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I can run the server directly via the command line as so:

``` bash
java -jar /usr/local/bin/ios-server-standalone.jar -aut "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app"
```

I'm not sure what is going on. I suppose it's something in the selenium-webdriver "remote" code? But as far as I can tell it's simply launching a child process with the same arguments as when I provide on the command line.

Any idea what's going on here? Version of selenium-webdriver I'm using is 2.42.1, but I also attempted to use 2.44.0 with the same result.

Thanks for any info.

**Comment by grawk** [comment]
Addendum: actually it seems the server does start fine, it's when the webdriver commands attempt to access the server that the server complains about capabilities. So I have removed the SeleniumServer class as a culprit. Please see the altered nodejs script:

``` javascript
var webdriver = require('selenium-webdriver');
var driver = new webdriver.Builder().
    withCapabilities(webdriver.Capabilities.iphone()).
    usingServer('http://0.0.0.0:5555/wd/hub').
    build();
console.log('caps', webdriver.Capabilities.iphone());
//above outputs: caps { caps_: { browserName: 'iPhone', platform: 'MAC' } }
driver.get('http://www.google.com');
driver.findElement(webdriver.By.name('q')).sendKeys('webdriver');
driver.findElement(webdriver.By.name('btnG')).click();
driver.wait(function() {
    return driver.getTitle().then(function(title) {
        return title === 'webdriver - Google Search';
    });
}, 1000);

driver.quit();

```

I first start the server in a separate shell prompt:

``` bash
$ java -jar /usr/local/bin/ios-server-standalone.jar -aut "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app"
```

Then attempt to run the standalone.js file:

``` bash
$ node standalone.js
/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
      throw error;
            ^
SessionNotCreatedError: The server cannot run Capabilities [{platform=MAC, CFBundleIdentifier=com.apple.mobilesafari, CFBundleName=Safari, locale=en_GB, variation=Retina4, device=iphone, sdkVersion=7.1}] at the moment.org.uiautomation.ios.application.APPIOSApplication cannot be cast to org.uiautomation.ios.application.IPAApplication
    at new bot.Error (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24
    at /Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /Users/medelman/src/_nemo/o/nemo-mobile-example/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
```

Now I'm thinking maybe my version of the simulator is incompatible with 0.6.6-SNAPSHOT?

**Comment by grawk** [comment]
After poking around for other examples, it seems that the capabilities object provided by `webdriver.Capabilities.iphone()` is insufficient for ios-driver to open the simulator and safari. In addition to what that method returns, the object must have: `{"simulator": true}`

With this, I am able to launch the simulator via ios-driver
