### ISSUE TITLE
not able to launch the simulator while while ruuning the code from eclipse.

### ISSUE THREAD

**Issue by ashutoshhello** [ios-driver/ios-driver#314]
I have followed the step from http://ios-driver.github.io/ios-driver/?page=safari.
I want to test or open the link (http://www.ebay.co.uk/) but the simulator is not launching.
Please let me know what extra configuration i need to do for the test or to launch the simulator in MAC.
Getting connection timed out exception.

followed the below steps.
1. 
$xcodeVersion=`xcode-select --print-path`
$sudo chmod a+rw "$xcodeVersion/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications"
$sudo chmod -R a+rw "$xcodeVersion/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/Applications/MobileSafari.app"

2.
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -port 5555
1. Run the below code.
   public static void main(String[] args) throws Exception {
   DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
   RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), safari);
   
   driver.get("http://www.ebay.co.uk/");
   
   System.out.println(driver.getTitle());
   driver.quit();
   }

**Comment by bijoyv** [comment]
can you recheck the response on http://localhost:4444/wd/hub/status

if you are using latest xcode, the simulator/sdk version might be different, if it is still not launching, can you post the console output of eclipse

**Comment by ashutoshhello** [comment]
Hi  bijoy,
the http://localhost:4444/wd/hub/status response is coming correct. We are using iOS sdk 7 and xcode 5.1.1 and iOS OSX 10.8.5 but the simulator is not opening, actually I do not know after 
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -port 5555 giving this command automatically the simulator will be launched or we need some extra configuration. Please help. Please explain me the details setup again and the env details so that i will corss check, whether i missed something.

**Comment by bijoyv** [comment]
simulator should be launched when you run the eclipse code 
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), IOSCapabilities.iphone("Safari"));

if it is not launching then, you are supposed to get error hints from both consoles where running the program and java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -port 5555

don't need any further configuration to run the sample

**Comment by vmytsyk** [comment]
I did the same, but i have error:
Cannot find /instruments_no_delay/6.2/56702/instruments

All console output:
<pre><code>
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: The server cannot run Capabilities [{simulator=true, instruments=true, timeHack=false, language=en, sdkVersion=8.2, CFBundleIdentifier=com.apple.mobilesafari, locale=en_GB, device=iphone, CFBundleName=Safari, variation=iPhone5s}] at the moment.Cannot find /instruments_no_delay/6.2/56702/instruments.
Command duration or timeout: 10.58 seconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'Mac-Admin.local', ip: '192.168.137.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at FirstTest.NewTest.main(NewTest.java:12)
Caused by: org.openqa.selenium.SessionNotCreatedException: The server cannot run Capabilities [{simulator=true, instruments=true, timeHack=false, language=en, sdkVersion=8.2, CFBundleIdentifier=com.apple.mobilesafari, locale=en_GB, device=iphone, CFBundleName=Safari, variation=iPhone5s}] at the moment.Cannot find /instruments_no_delay/6.2/56702/instruments.
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'Mac-Admin.local', ip: '192.168.137.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:101)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:55)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:110)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse(IOSServlet.java:158)
    at org.uiautomation.ios.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.servlet.IOSServlet.doPost(IOSServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
</pre></code>

**Comment by bijoyv** [comment]
please refer issue https://github.com/ios-driver/ios-driver/issues/326

**Comment by mach6** [comment]
please re-open, if needed
