### ISSUE TITLE
Can't run simulation in ios-driver

### ISSUE THREAD

**Issue by vmytsyk** [ios-driver/ios-driver#326]
I can't run simulation in ios-driver. I use examples, but when I get exceptions. =(
What's wrong?

1) Checking settings:

<pre><code>xcode-select -p
/Applications/Xcode-Beta.app/Contents/Developer

gcc --version
Configured with: --prefix=/Applications/Xcode-Beta.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
</code></pre>

2) Run ios-driver: java -jar ios-server-0.6.5-jar-with-dependencies.jar -port 5555 -simulators
<pre><code>
10:34:960 INFO ApplicationStore.<init>  App archive folder:/Users/admin/Documents/workspace/applications
10:34:980 WARNING AppleLanguage.create  crazy-language isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
10:35:287 WARNING AppleLanguage.create  fr_CA isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
10:35:367 WARNING AppleLanguage.create  hi isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
10:35:530 WARNING AppleLanguage.create  no isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
10:35:795 WARNING AppleLanguage.create  zh_CN isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
10:35:808 WARNING AppleLanguage.create  zh_HK isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
10:35:821 WARNING AppleLanguage.create  zh_TW isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
10:35:838 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): false
Simulator enabled ( enabled by -simulators flag): true
Inspector: http://0.0.0.0:5555/inspector/
tests can access the server at http://0.0.0.0:5555/wd/hub
server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/admin/Documents/workspace/applications' for new applications
Archived apps /Users/admin/Documents/workspace/applications
using xcode install : /Applications/Xcode-Beta.app
using IOS version 8.2
ios >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=InternationalMountains,CFBundleVersion=1.1
CFBundleName=UICatalog,CFBundleVersion=2.10
CFBundleName=Safari,CFBundleVersion=600.1.4
```

2014-11-20 17:10:35.839:INFO::jetty-7.x.y-SNAPSHOT
2014-11-20 17:10:35.907:INFO::Started SelectChannelConnector@0.0.0.0:5555
</pre></code>

3) My code:
<pre><code>
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import junit.framework.Assert;

import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.Augmenter;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.uiautomation.ios.IOSCapabilities;

public class Test {

```
public static void main(String[] args) throws Exception {
    DesiredCapabilities caps = IOSCapabilities.iphone();
    caps.setCapability(IOSCapabilities.SIMULATOR, true);
    RemoteWebDriver driver = new RemoteWebDriver(new URL("http://0.0.0.0:5555/wd/hub"), caps);

    driver.get("http://www.google.com");

    System.out.println(driver.getTitle());
    driver.quit();
}
```

}
</pre></code>

4) Exception:
<pre><code>Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: {simulator=true, CFBundleName=Safari, device=iphone, version=, platform=MAC}not available. Available are [Simulator]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
Command duration or timeout: 506 milliseconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'Mac-Admin.local', ip: '192.168.137.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at FirstTest.Test.main(Test.java:24)
Caused by: org.openqa.selenium.SessionNotCreatedException: {simulator=true, CFBundleName=Safari, device=iphone, version=, platform=MAC}not available. Available are [Simulator]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'Mac-Admin.local', ip: '192.168.137.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:54)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:86)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:144)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:745)</pre></code>

**Comment by vmytsyk** [comment]
Tried ios-0.6.6
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -port 5555
The same code:
<pre><code>
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import junit.framework.Assert;

import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.Augmenter;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.uiautomation.ios.IOSCapabilities;

public class Test {

```
public static void main(String[] args) throws Exception {
    DesiredCapabilities caps = IOSCapabilities.iphone();
    caps.setCapability(IOSCapabilities.SIMULATOR, true);
    RemoteWebDriver driver = new RemoteWebDriver(new URL("http://0.0.0.0:5555/wd/hub"), caps);

    driver.get("http://www.google.com");

    System.out.println(driver.getTitle());
    driver.quit();
}
```

}
</pre></code>

And I can see another error:
<pre><code>
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: The server cannot run Capabilities [{simulator=true, sdkVersion=8.2, CFBundleIdentifier=com.apple.mobilesafari, locale=en_GB, CFBundleName=Safari, device=iphone, version=, platform=MAC, variation=iPhone5s}] at the moment.Cannot find /instruments_no_delay/6.2/56702/instruments.
Command duration or timeout: 1.05 seconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'Mac-Admin.local', ip: '192.168.137.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at FirstTest.Test.main(Test.java:24)
Caused by: org.openqa.selenium.SessionNotCreatedException: The server cannot run Capabilities [{simulator=true, sdkVersion=8.2, CFBundleIdentifier=com.apple.mobilesafari, locale=en_GB, CFBundleName=Safari, device=iphone, version=, platform=MAC, variation=iPhone5s}] at the moment.Cannot find /instruments_no_delay/6.2/56702/instruments.
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'Mac-Admin.local', ip: '192.168.137.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:101)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:55)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:110)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse(IOSServlet.java:158)
    at org.uiautomation.ios.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.servlet.IOSServlet.doPost(IOSServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
</pre></code>

**Comment by vmytsyk** [comment]
Downloaded https://github.com/facebook/instruments-without-delay 
And ran ./build.sh test 
It works. 
How can I show to server where instruments are placed to run my java code?

**Comment by bijoyv** [comment]
ios-driver currently support upto Xcode version 6.1 (I'm seeing 6.2 is in beta now), can you check with Xcode version 6.1

**Comment by vmytsyk** [comment]
Oh my, guy, you are a life saver! I spent on this problem for 2 days, I even couldn't sleep!
Thanks!!!
