### ISSUE TITLE
Session isn't created and WARNING ApplicationCrashMonitor.hasApplicationCrashed

### ISSUE THREAD

**Issue by vmytsyk** [ios-driver/ios-driver#328]
I’ve started using ios-driver. Yesterday I was able to run and use ios-driver for Safari simulation. Thanx @bijoyv for help.

Now, I’m gonna run application test, but when I try to run my code, the simulator launches and crashes.

I followed the instructions http://ios-driver.github.io/ios-driver/?page=native but it can’t help me. =(

Also, I don’t understand why a session isn’t created, after running ios-server I go to http://0.0.0.0:4444/inspector/ and it redirects to http://0.0.0.0:4444/inspector/session/null/home

I guess, my goal is getting a session and then my code will work well. What I’m doing wrong?

Run ios-server:
<code>java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut applications/InternationalMountains.app/ -port 4444</code>

<pre><code>
02:52:502 INFO ApplicationStore.<init>  App archive folder:/Users/admin/Documents/workspace/applications
02:52:543 WARNING AppleLanguage.create  crazy-language isn't recognized. Please file a bug on github. You won't be able to start the app in that language.
version:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560
Beta features enabled (enabled by -real flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:4444/inspector/
Tests can access the server at http://0.0.0.0:4444/wd/hub
Server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/admin/Documents/workspace/applications' for new applications
Archived apps: /Users/admin/Documents/workspace/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20141009-1559,sha:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560)
Running on: Mac OS X 10.10 (x86_64)
Using java: 1.8.0_25
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.1, build: 56160
Using iOS version 8.1
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
    CFBundleName=InternationalMountains,CFBundleVersion=1.1,/Users/admin/Documents/workspace/applications/InternationalMountains.app
    CFBundleName=Safari,CFBundleVersion=600.1.4,/Users/admin/.ios-driver/safariCopies/safari-8.1.app
2014-11-22 01:02:53.403:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2014-11-22 01:02:53.461:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4444
02:53:463 WARNING AppleLanguage.create  crazy-language isn't recognized. Please file a bug on github. You won't be able to start the app in that language.

</code></pre>

My code:

<pre><code>

      public static void main(String[] args) throws MalformedURLException {
            // create a selenium desiredCapabilities object with the right values.
            DesiredCapabilities cap = IOSCapabilities.iphone("InternationalMountains", "1.1");
            // start the application
            RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), cap);

            // take a screenshot using the normal selenium api.
            TakesScreenshot screen =(TakesScreenshot)new Augmenter().augment(driver);
            File ss = new File("screenshot.png");
            screen.getScreenshotAs(OutputType.FILE).renameTo(ss);
            System.out.println("screenshot take :"+ss.getAbsolutePath());

            // access the content
            By selector = By.xpath("//UIAStaticText[contains(@name,'climbed')]");
            WebElement text = driver.findElement(selector);
            System.out.println(text.getAttribute("name"));

            // end the test
            driver.quit();
    }

</code></pre>

The terminal shows:

<pre><code>
14:07:658 WARNING ApplicationCrashMonitor.hasApplicationCrashed  log from crash 2014-11-21 23:14:07 +0000 Fail: The target application appears to have died
14:07:679 WARNING InstrumentsCommandLine.stop  couldn't kill 1825
14:22:154 WARNING InstrumentsCommandLine.start  instruments crashed (20 SEC)
14:22:189 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 20sec):Didn't get the capability back.Most likely, instruments crashed at startup.
14:22:189 WARNING NewSessionNHandler.safeStart  app has crashed at startup :crash
14:39:489 WARNING ApplicationCrashMonitor.hasApplicationCrashed  log from crash 2014-11-21 23:14:39 +0000 Fail: The target application appears to have died
14:39:496 WARNING InstrumentsCommandLine.stop  couldn't kill 1899
15:16:042 WARNING InstrumentsCommandLine.start  instruments crashed (40 SEC)
15:16:072 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 40sec):Didn't get the capability back.Most likely, instruments crashed at startup.
15:16:072 WARNING NewSessionNHandler.safeStart  app has crashed at startup :crash
15:24:032 WARNING ApplicationCrashMonitor.hasApplicationCrashed  log from crash 2014-11-21 23:15:24 +0000 Fail: The target application appears to have died
15:24:036 WARNING InstrumentsCommandLine.stop  couldn't kill 1967
16:19:595 WARNING InstrumentsCommandLine.start  instruments crashed (60 SEC)
16:19:627 WARNING NewSessionNHandler.safeStart  Instruments failed to start in the allocated time ( 60sec):Didn't get the capability back.Most likely, instruments crashed at startup.
16:19:628 WARNING NewSessionNHandler.safeStart  app has crashed at startup :crash
</code></pre>

The error:

<pre><code>
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: failed starting after 3 retries.Final wait was 80
Command duration or timeout: 141.66 seconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'Mac-Admin.local', ip: '192.168.137.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at FirstTest.InterMountains.main(InterMountains.java:24)
Caused by: org.openqa.selenium.SessionNotCreatedException: failed starting after 3 retries.Final wait was 80
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'Mac-Admin.local', ip: '192.168.137.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:64)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:110)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse(IOSServlet.java:158)
    at org.uiautomation.ios.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.servlet.IOSServlet.doPost(IOSServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
</code></pre>

**Comment by bijoyv** [comment]
seems like there is some problem to load the InternationalMountains, may be you build it using xcode and test it by invoking simulator from xcode, if that works well, use the built version for testing

**Comment by azaytsev** [comment]
The sample InternationalMountain app doesn't seem compatible with XCode 6/IOS 8. Try downloading the source code for it here (https://developer.apple.com/library/ios/samplecode/InternationalMountains/Listings/InternationalMountains_RootViewController_m.html) and compiling with your XCode version

**Comment by mach6** [comment]
please re-open and update if rebuilding the app does not help

**Comment by jsfeng111** [comment]
hello bijoyv,  azaytsev   @bijoyv  @azaytsev 

I still in trouble after rebuilding the app. I download the source code from the link in the above comment and comply with my Xcode version(open the xcodeproj file --> Product --> Profile --> Automation ).But a error display after I run the command:

DongdeMacBook-Pro:automation dong$ java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut Mountains1209.app -port 4444
49:52:068 INFO ApplicationStore.<init>  App archive folder:/Users/dong/Downloads/automation/applications
49:52:117 SEVERE IOSServer.main  cannot start ios-driver server.org.openqa.selenium.WebDriverException: Error loading content for l10n
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DongdeMacBook-Pro.local', ip: '9.125.64.91', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.application.APPIOSApplication.loadDictionaries(APPIOSApplication.java:181)
    at org.uiautomation.ios.application.APPIOSApplication.<init>(APPIOSApplication.java:79)
    at org.uiautomation.ios.application.APPIOSApplication.createFrom(APPIOSApplication.java:584)
    at org.uiautomation.ios.IOSServer.initDriver(IOSServer.java:137)
    at org.uiautomation.ios.IOSServer.init(IOSServer.java:117)
    at org.uiautomation.ios.IOSServer.start(IOSServer.java:261)
    at org.uiautomation.ios.IOSServer.main(IOSServer.java:104)
Caused by: org.openqa.selenium.WebDriverException: In /Users/dong/Downloads/automation/Mountains1209.app/en.lproj/Main.strings: Cannot parse /Users/dong/Downloads/automation/Mountains1209.app/en.lproj/Main.strings: Expected '{' or '(' or '/' but found '"'
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DongdeMacBook-Pro.local', ip: '9.125.64.91', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.8.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.utils.PlistFileUtils.read(PlistFileUtils.java:42)
    at org.uiautomation.ios.utils.PlistFileUtils.<init>(PlistFileUtils.java:33)
    at org.uiautomation.ios.application.LanguageDictionary.readContentFromBinaryFile(LanguageDictionary.java:75)
    at org.uiautomation.ios.application.APPIOSApplication.loadDictionaries(APPIOSApplication.java:178)
    ... 6 more
Caused by: java.text.ParseException: Expected '{' or '(' or '/' but found '"'
    at com.dd.plist.ASCIIPropertyListParser.expect(ASCIIPropertyListParser.java:211)
    at com.dd.plist.ASCIIPropertyListParser.parse(ASCIIPropertyListParser.java:328)
    at com.dd.plist.ASCIIPropertyListParser.parse(ASCIIPropertyListParser.java:89)
    at com.dd.plist.ASCIIPropertyListParser.parse(ASCIIPropertyListParser.java:77)
    at com.dd.plist.ASCIIPropertyListParser.parse(ASCIIPropertyListParser.java:64)
    at com.dd.plist.PropertyListParser.parse(PropertyListParser.java:94)
    at org.uiautomation.ios.utils.PlistFileUtils.read(PlistFileUtils.java:38)
    ... 9 more

My Xcode/SDK version is 6.1/8.1. 
I don't know how to solve the problem. Is there anything wrong when rebuilding and complying?  Waiting for you help and thanks in advance !!

**Comment by azaytsev** [comment]
@jsfeng111 Can you please pull down the ios-driver source code and compile it using 'mvn clean package -DskipTests'. I see this issue has already been fixed before (https://github.com/ios-driver/ios-driver/issues/18) but the fix may not be included in the jar that is posed on the website.

The compiled jar will be located under server/target/

**Comment by azaytsev** [comment]
@jsfeng111 Also, don't know if this will helps but here is the international mountains app I compiled using the source code provided. I works for me with both sdk 5.1 and 6.1

http://dropcanvas.com/iset4

**Comment by jsfeng11111** [comment]
@azaytsev Wow it work successfully now. i use the build you provide and no error appear when I deploy the app. it's so cool. Thanks a lot for your help !

But i don't know why the international mountains app i rebuild has something wrong to parse.My steps is as below:
1. Download the source code from https://developer.apple.com/library/ios/samplecode/InternationalMountains/Listings/InternationalMountains_RootViewController_m.html
2. Click the xcodeproj file and open international mountains app 
3. Product --> Profile
4. Find the release-app

Is there anything wrong? I'm really looking forward to your reply.

**Comment by cyoung27** [comment]
@azaytsev
I'm having the same issue, but have not been successful after re-compiling from the source. Could you provide your build again (link is expired) so I can see if it works for me as well? xcode 6.1.1/iOS7.1
Thanks!

To add to this, I can successfully compile and launch the app through xcode, but once i try to start the server, it fails with a similar error as jsfeng11111 has.

**Comment by azaytsev** [comment]
https://sites.google.com/site/iosdrivermountains/Mountains.zip?attredirects=0&d=1

**Comment by cyoung27** [comment]
Thank you!!
