### ISSUE TITLE
Cannot start iPad simulator 

### ISSUE THREAD

**Issue by jiangyycdl** [ios-driver/ios-driver#338]
Hi,
I met a problem when starting a iPad simulator.

I finished the basic steps for the safari in the following link:
http://ios-driver.github.io/ios-driver/?page=safari

When I ran command in the terminal: java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar

then the output of http://localhost:5555/wd/hub/status as below:

{
  "class": "org.openqa.selenium.remote.Response",
  "hCode": 86026454,
  "sessionId": null,
  "state": null,
  "status": 0,
  "value": {
    "build": {
      "revision": "663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560",
      "time": "20141009-1559",
      "version": "0.6.6-SNAPSHOT"
    },
    "ios": {"simulatorVersion": "7.1"},
    "java": {"version": "1.8.0_25"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.9.4"
    },
    "state": "success",
    "supportedApps": [{
      "CFBundleDevelopmentRegion": "English",
      "CFBundleDisplayName": "Safari",
      "CFBundleExecutable": "MobileSafari",
      "CFBundleIcons": {"CFBundlePrimaryIcon": {
        "CFBundleIconFiles": [
          "icon-spotlight~ipad.png",
          "icon-table~ipad.png",
          "icon-about~ipad.png",
          "icon-table~ipad.png",
          "icon-spotlight@2x.png",
          "icon-table@2x.png",
          "icon~ipad.png",
          "icon-about@2x.png",
          "icon@2x~iphone.png",
          "icon@2x~ipad.png"
        ],
        "UIPrenderedIcon": true
      }},
      "CFBundleIdentifier": "com.apple.mobilesafari",
      "CFBundleInfoDictionaryVersion": "6.0",
      "CFBundlePackageType": "APPL",
      "CFBundleShortVersionString": "7.0",
      "CFBundleSignature": "????",
      "CFBundleSupportedPlatforms": ["iPhoneSimulator"],
      "CFBundleURLTypes~ipad": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleURLTypes~iphone": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "Radar URL",
          "CFBundleURLSchemes": [
            "rdar",
            "radar"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleURLTypes~ipod": [
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "Web App URL",
          "CFBundleURLSchemes": ["webclip"]
        },
        {
          "CFBundleURLName": "Web site URL",
          "CFBundleURLSchemes": [
            "http",
            "https"
          ]
        },
        {
          "CFBundleURLName": "Radar URL",
          "CFBundleURLSchemes": [
            "rdar",
            "radar"
          ]
        },
        {
          "CFBundleURLName": "FTP URL",
          "CFBundleURLSchemes": ["ftp"]
        },
        {
          "CFBundleURLName": "Web Search URL",
          "CFBundleURLSchemes": ["x-web-search"]
        },
        {
          "CFBundleURLIsPrivate": true,
          "CFBundleURLName": "MobileSafari Tab URL",
          "CFBundleURLSchemes": ["com-apple-mobilesafari-tab"]
        }
      ],
      "CFBundleVersion": "9537.53",
      "DTPlatformName": "iphonesimulator",
      "DTSDKName": "iphonesimulator7.1",
      "LSRequiresIPhoneOS": true,
      "MallocBehavior": {"NanoAllocator": false},
      "SBMatchingApplicationGenres": [
        "Productivity",
        "Utilities"
      ],
      "SBUsesNetwork": 3,
      "SafariProductVersion": "7.0",
      "UIApplicationDisableLegacyAutorotationKey": true,
      "UIBackgroundModes": [
        "audio",
        "continuousFallback"
      ],
      "UIBackgroundStyle~iphone": "UIBackgroundStyleDarkBlur",
      "UIDeviceFamily": [1],
      "UIHasPrefs": true,
      "UIStatusBarTintParameters": {"UINavigationBar": {"Style": "UIBarStyleDefault"}},
      "UISupportedInterfaceOrientations": [
        "UIInterfaceOrientationPortrait",
        "UIInterfaceOrientationLandscapeLeft",
        "UIInterfaceOrientationLandscapeRight"
      ],
      "UISupportedInterfaceOrientations~ipad": [
        "UIInterfaceOrientationPortrait",
        "UIInterfaceOrientationLandscapeLeft",
        "UIInterfaceOrientationLandscapeRight",
        "UIInterfaceOrientationPortraitUpsideDown"
      ],
      "UIViewControllerBasedStatusBarAppearance": true,
      "applicationPath": "/Users/reach/.ios-driver/safariCopies/safari-7.1.app",
      "device": "iphone",
      "deviceAlt": [
        "iphone",
        "ipod"
      ],
      "device_Alt": [
        "iphone",
        "ipad"
      ],
      "instruments": true,
      "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=2134756163"},
      "sdkVersion": "7.1",
      "sdkVersion_alt": ["7.1"],
      "simulator": true,
      "supportedLanguages": [
        "ar",
        "ca",
        "cs",
        "da",
        "de",
        "el",
        "en",
        "en-GB",
        "es",
        "fi",
        "fr",
        "he",
        "hr",
        "hu",
        "id",
        "it",
        "ja",
        "ko",
        "ms",
        "nl",
        "no",
        "pl",
        "pt",
        "pt-PT",
        "ro",
        "ru",
        "sk",
        "sv",
        "th",
        "tr",
        "uk",
        "vi",
        "zh-CN",
        "zh-TW"
      ],
      "timeHack": false
    }]
  }
}

So when I used the code for iPhone simulator, it works:
public static void main(String[] args) throws MalformedURLException {
        DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), safari);
        driver.get("http://www.ebay.co.uk/");

```
    System.out.println(driver.getTitle());
    driver.quit();
```

}

But when I changed the code for iPad:
public static void main(String[] args) throws MalformedURLException {
        DesiredCapabilities safari = IOSCapabilities.ipad("Safari");
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), safari);
        driver.get("http://www.ebay.co.uk/");

```
    System.out.println(driver.getTitle());
    driver.quit();
```

}

It failed:

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: The server cannot run Capabilities [{simulator=true, instruments=true, timeHack=false, language=en, locale=en_GB, device=ipad, CFBundleName=Safari}] at the moment.desired app not found on server: {simulator=true, instruments=true, timeHack=false, language=en, locale=en_GB, device=ipad, CFBundleName=Safari}.
Command duration or timeout: 220 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'adsl-172-10-1-110.dsl.sndg02.sbcglobal.net', ip: '172.10.1.110', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.4', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at debug.EE.main(EE.java:15)
Caused by: org.openqa.selenium.SessionNotCreatedException: The server cannot run Capabilities [{simulator=true, instruments=true, timeHack=false, language=en, locale=en_GB, device=ipad, CFBundleName=Safari}] at the moment.desired app not found on server: {simulator=true, instruments=true, timeHack=false, language=en, locale=en_GB, device=ipad, CFBundleName=Safari}.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'adsl-172-10-1-110.dsl.sndg02.sbcglobal.net', ip: '172.10.1.110', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.4', java.version: '1.8.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:101)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:55)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:110)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse(IOSServlet.java:158)
    at org.uiautomation.ios.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.servlet.IOSServlet.doPost(IOSServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Dsa12345** [comment]
Hey...same issue here...
Could anyone update on this ASAP...

**Comment by kumaravel-jayakumar** [comment]
@jiangyycdl What version of Xcode are you using? If it is 5.1.1 can you try with Xcode version 6.1?
