### ISSUE TITLE
WebDriverLikeCommand Error after registering successfully on hub

### ISSUE THREAD

**Issue by rdissertori** [ios-driver/ios-driver#34]
Hello @nicegraham 

regarding the issue on my topic "Question about Selenium Grid (Hub) integration on Jenkins":
thank you for the patch you provided, I can now successfully see the node registered on the hub.

Sadly I seem to  get a followup-error:

at org.uiautomation.ios.communication.WebDriverLikeCommand.getCommand(WebDriverLikeCommand.java:300)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getGenericCommand(WebDriverLikeRequest.java:115)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getVariableValue(WebDriverLikeRequest.java:119)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getSession(WebDriverLikeRequest.java:132)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:137)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:82)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:45)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:722)

any hints about that?

**Comment by nicegraham** [comment]
not really, can you give me more details? The stacktrace looks like its missing the top of the message. At what stage do you get the error?

**Comment by rdissertori** [comment]
Well this was the whole error output (and yes its strange because it seems like it's missing the top)

But nevermind - I wasn't setting up the Junit Tests properly to match the capabilities in a correct way.
Which I just did right now and it seems this error message is gone with that.

Still having other problems like forwarding to DISPLAY issues from Jenkins to the Mac, but thats non-related to the ios-driver. For now I'm very satisfied with the results and it looks like I'm on the verge of achieving what I wanted
