### ISSUE TITLE
Error forwarding the new session new session request for webdriver should contain a location header with the session

### ISSUE THREAD

**Issue by rdissertori** [ios-driver/ios-driver#35]
updated so theres only one issue per thread:

whenever I start my junit test on jenkins (hub) I receive the error

```
org.openqa.selenium.WebDriverException: Error forwarding the new session new session request for webdriver should contain a location header with the session.
Command duration or timeout: 171 milliseconds
Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:53:56'
System info: os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.6.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:187)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
    at ecx.io.qs.selenium.tests.TestIphone.setUp(TestIphone.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

I suspect it has something to do with
http://code.google.com/p/selenium/source/browse/java/server/src/org/openqa/grid/internal/TestSession.java?r=fecf74aee85e9f8bf2a16174420504d37723c345&spec=svnbc1dba867ee457554a3413198a1ee595ef223191
at Method updateHubIfNewWebDriverSession (the only method returning such a message) receiving an empty Location header

I also had a look at the ios-driver module server
at org.uiautomation.ios.server.servlet.IOSServlet
the only location the responseHeader for "location" beeing set.

Just for testing reason I commented out the IF-clause and repackaged the files.
After doing so I still got some exception, but it was different from the one before. So I suspect it has to do something about this code block receiving that mentioned errormessage.

**Comment by freynaud** [comment]
please try to write 1 separate issue per github issue. It makes triaging easier.
1) can you try again, it should be fixed. The wrong casting should be gone now.

**Comment by freynaud** [comment]
2) can you try running a plain grid hub, without jenkins and let me know if you have the same issue

**Comment by nicegraham** [comment]
Myself and nirvdrum are seeing that error too

**Comment by freynaud** [comment]
@nicegraham which one ? error 1 or the hub issue ?

**Comment by nicegraham** [comment]
@freynaud the location header problem. @nirvdrum said he was getting out every third test on Friday

**Comment by rdissertori** [comment]
Thank you for the feedback - I've updated this thread and split up the issues to one per thread.
I will have a look at this at the start of next week, when I'm back at the office and keep you guys updated about this.
Should I get the latest version from github before testing it apart from jenkins?

**Comment by freynaud** [comment]
yes.

checkout the dev branch, and mvn install -DskipTests=true will generate you
the ios-server jar.
You can get interactive support on IRC, #ios-driver on freenode.
thanks,
François

On Fri, May 10, 2013 at 12:32 PM, Roman Dissertori <notifications@github.com

**Comment by nicegraham** [comment]
@nirvdrum committed some changes which have resolved the location header for the most part for us:
https://github.com/ios-driver/ios-driver/commit/d3797f21535f26788857107d33de260d8247a814

**Comment by rdissertori** [comment]
update: I have tested the new dev sources without jenkins integration (which I had to do so anyways because a collegue has to deploy critical stuff from there)
using the wd/hub directly seems to work perfectly (!!) for my junit test

I will tell you about the results tomorrow when I'm able to use jenkins again.
I have another issue regarding the "-beta" flag but I will open up an extra ticket for that.

**Comment by rdissertori** [comment]
Hello,

I've now tested it on Jenkins it seems to work now with the latest version(!!) though I didnt have time to use the -beta flag, which is irrelevant for the communication jenkins <=> macos I suppose.
I will not close this ticket until I've tested this with the -beta flag on, but it looks very promising :)

regards @rdissertori

**Comment by nicegraham** [comment]
you don't need -beta unless you're testing real devices, either way the -beta thing is a different issue so I'll close this for now.

**Comment by nicegraham** [comment]
we're seeing this very regularly on our grid still. @darraghgrace is working on it now

**Comment by nicegraham** [comment]
we were seeing this more often because we were running native apps which was where the primary issue was. Problem has been resolved by https://github.com/ios-driver/ios-driver/compare/99dc118996d7...5682ec51df4d

thanks @darraghgrace!

**Comment by avaly** [comment]
I seem to be running into this same problem. I am running ios-driver 0.6.3 as a Selenium Node with the `-simulators` argument. The Selenium Grid server is running 2.33.0 and registers the ios-driver instance as a node.

When trying to start a test from node.js using the `wd` library with the browserName set to `iPhone`, the Selenium Grid outputs this log:

```
INFO: Trying to create a new session on test slot {platform=MAC, simulator=true, browserName=iPhone, maxInstances=1, timeHack=false, variation=Regular, locale=en_GB, CFBundleName=Safari, device=iphone, language=en}
```

While the test client receives the following exception message:

``` javascript
{
     message: 'Error forwarding the new session new session request for webdriver should contain a location header with the session.',
     class: 'org.openqa.grid.common.exception.GridException',
     stackTrace: [/*... long list of stack trace...*/]
}
```

I have tried the same process with the ios-driver 0.6.4, but ran into the same result.
