### ISSUE TITLE
WebDriverException: is Safari started and with the focus ?

### ISSUE THREAD

**Issue by manoharreddyporeddy** [ios-driver/ios-driver#369]
Hi all,
1. I have built the ios-server jar from default DEV branch source code
   Trying to run test on safari on Real device with below source code given on website:
2. Code is from website:
   public static void main(String[] args) throws Exception {
   DesiredCapabilities safari = IOSCapabilities.iphone("Safari");
   RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:5555/wd/hub"), safari);
   driver.get("http://www.ebay.co.uk/");
   System.out.println(driver.getTitle());
   driver.quit();
   }

3.
My Config:
MacOSX 10.10.3 (14D131)
Java: 1.8
iPhone 5s (real device) - iOS Version 8.2(12D508)
Xcode versions 6.1, 6.2 & 6.3

4.
I am getting below error:
       WebDriverException: is Safari started and with the focus ?

Actually
the Safari opens
and then closes
after few seconds
just when this exception occurs

Detailed error is below
Can anyone help? Or, let me know how I can contribute to solve this bug.

When i searched its coming from showWarning() function of RemoteIOSWebDriver.java file
can be seen at below link
https://github.com/ios-driver/ios-driver/search?utf8=%E2%9C%93&q=is+Safari+started+and+with+the+focus

Thank you

---

XCode6.1

Exception in thread "main" org.openqa.selenium.WebDriverException: is Safari started and with the focus ? 
Command duration or timeout: 17.34 seconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'mayank-iMac.local', ip: '192.168.116.99', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.<init>(RemoteIOSDriver.java:94)
    at com.innopark.pkg1.Cls1.device(Cls1.java:49)
    at com.innopark.pkg1.Cls1.main(Cls1.java:35)
Caused by: org.openqa.selenium.WebDriverException: is Safari started and with the focus ? 
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'mayank-iMac.local', ip: '192.168.116.99', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.drivers.RemoteIOSWebDriver.showWarning(RemoteIOSWebDriver.java:122)
    at org.uiautomation.ios.drivers.RemoteIOSWebDriver.start(RemoteIOSWebDriver.java:113)
    at org.uiautomation.ios.drivers.IOSDualDriver.getRemoteWebDriver(IOSDualDriver.java:198)
    at org.uiautomation.ios.drivers.IOSDualDriver.start(IOSDualDriver.java:130)
    at org.uiautomation.ios.ServerSideSession.start(ServerSideSession.java:306)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:98)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:56)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:110)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse(IOSServlet.java:158)
    at org.uiautomation.ios.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.servlet.IOSServlet.doPost(IOSServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)

---

XCode6.2

Exception in thread "main" org.openqa.selenium.WebDriverException: is Safari started and with the focus ? 
Command duration or timeout: 21.74 seconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'mayank-iMac.local', ip: '192.168.116.99', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.<init>(RemoteIOSDriver.java:94)
    at com.innopark.pkg1.Cls1.device(Cls1.java:49)
    at com.innopark.pkg1.Cls1.main(Cls1.java:35)
Caused by: org.openqa.selenium.WebDriverException: is Safari started and with the focus ? 
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'mayank-iMac.local', ip: '192.168.116.99', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.drivers.RemoteIOSWebDriver.showWarning(RemoteIOSWebDriver.java:122)
    at org.uiautomation.ios.drivers.RemoteIOSWebDriver.start(RemoteIOSWebDriver.java:113)
    at org.uiautomation.ios.drivers.IOSDualDriver.getRemoteWebDriver(IOSDualDriver.java:198)
    at org.uiautomation.ios.drivers.IOSDualDriver.start(IOSDualDriver.java:130)
    at org.uiautomation.ios.ServerSideSession.start(ServerSideSession.java:306)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:98)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:56)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:110)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse(IOSServlet.java:158)
    at org.uiautomation.ios.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.servlet.IOSServlet.doPost(IOSServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)

---

XCode6.3

Exception in thread "main" org.openqa.selenium.WebDriverException: is Safari started and with the focus ? 
Command duration or timeout: 27.19 seconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'mayank-iMac.local', ip: '192.168.116.99', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.<init>(RemoteIOSDriver.java:94)
    at com.innopark.pkg1.Cls1.device(Cls1.java:49)
    at com.innopark.pkg1.Cls1.main(Cls1.java:35)
Caused by: org.openqa.selenium.WebDriverException: is Safari started and with the focus ? 
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'mayank-iMac.local', ip: '192.168.116.99', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: driver.version: IOSDualDriver
    at org.uiautomation.ios.drivers.RemoteIOSWebDriver.showWarning(RemoteIOSWebDriver.java:122)
    at org.uiautomation.ios.drivers.RemoteIOSWebDriver.start(RemoteIOSWebDriver.java:113)
    at org.uiautomation.ios.drivers.IOSDualDriver.getRemoteWebDriver(IOSDualDriver.java:198)
    at org.uiautomation.ios.drivers.IOSDualDriver.start(IOSDualDriver.java:130)
    at org.uiautomation.ios.ServerSideSession.start(ServerSideSession.java:306)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.safeStart(NewSessionNHandler.java:98)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:56)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:110)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse(IOSServlet.java:158)
    at org.uiautomation.ios.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.servlet.IOSServlet.doPost(IOSServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)

**Comment by raldred** [comment]
Same here with real iPhone 4 on 6.1.3, xcode 6.1.1.
Work fine on my real iPad 2 also on 6.1.3

**Comment by jigtest** [comment]
Hey,
I am also facing with the same issue. The browser starts but then the error is displayed.
I am trying to run tests on real device - iPhone 6 plus and Xcode is 6.2.
@pgmreddy and @raldred :- Were you able to solve this problem?

Any help would be really appreciated.

**Comment by manoharreddyporeddy** [comment]
What I found is below:
1. If I use OS with 8+ version, it does not run
2. If I use OS with 7.1 version, it does run -- with many crashes, but after having sleeps in the code I was able to run few

then we lost interest in the iOS automation, we do all automated for Desktop & Android, but for iOS we do manual, for now.

Later one of us, have to read the code and fix these small issues.
You will note that
- the delay issue related fixes are already in one of the branches/ forks of this project, just dint get enough time to take in those fixes
- ideally these fixes are checked-in in the forks long back, and shud have gone into main branch that you & me are using, by now
- but looks like the original owners have in no intension to take in these fixes, or help or guide this community.
- of course I am talking about 2 months back situation, around Mar 2014 time.

**Comment by jigtest** [comment]
@pgmreddy Thanks a lot for a quick detailed reply.
So is it the problem of Safari browser or ios-driver? I was trying to run tests on chrome browser on iPhone but was not able to get the appropriate capabilities to run it. Have you tried on any other browser or is it even possible to run on any other browser than Safari?

**Comment by manoharreddyporeddy** [comment]
Sure, I'm glad I was able to help.
- It is not problem with Safari- ios-driver is created by us, the community, though I and you have not been writing anything it, which is what I proposed- since ios-driver is not by Apple, but by us, there are few bugs, these need to be fixed as can be seen by forks of it- or, we can fix in our application that uses ios-driver, instead of ios-driver, by inserting delays between statements, this looks a bit correct, since it depends on which website you are testing, if you have jQuery website, it is slow, so it makes sense to keep sleeps in our application that uses ios-driver, however ios-driver does not give proper user friendly formatted messages, this can be fixed.
  Apps can be- Native- Web, or- Hybrid (Web control in a Native app wrapper)
  On Android:#1. we use ChromeDriver to run tests on Chrome browser on Android, it requires Android Studio (tools in it)
  On iOS (iPhone, etc.)#1 It can be used for all above apps#2 For Web, it supports Safari browser, as per their documentation. I am not sure if it can test Chrome browser too. But you shouldnt worry about Chrome I think, people mainly use Safari on iOS.#3 We never ran Chrome on iOS, due to browser statistics we had at that time#4 I believe, you should follow some or all parts of #1 of "On Android" section above, to run on Chrome browser "on iOS"
  Hope that helps.
  Date: Thu, 25 Jun 2015 14:07:23 -0700

**Comment by jigtest** [comment]
Yes, sleeps did help me sometimes while running on iPhone simulator and yes people mostly use safari browser on iOS but was just thinking of an alternative option. Anyways thank you for helping me out.

**Comment by manoharreddyporeddy** [comment]
Perfect.
Alternative for iOS, you could do the below:
1. Find the difference between simulator & real device, on iPhone. If there is not much there is not much to test in an automated wayFor few (assumption, you can confirm) things that does work exactly as real device, 1. you can do automated with sleeps or old real device, or 2. do manual
2. You can Hybrid (Web control in actual app), if that browser is different from Safari. For Android, it was different (I think) before Kitkat, i.e. a bit earlier there were 2 browsers for Android, "Stock Android browser" & "Chrome browser" were different.
3. You can try, what I said for Chrome on iOS.
I lost interest to tryBut like I could helpIf you tried any of the above, let us know the results, you could help someone else. Thanks.
Date: Thu, 2 Jul 2015 08:11:37 -0700

**Comment by KunalKathrotia** [comment]
@pgmreddy you said that delay issue related fixes are already in one of the branch of this project, can you tell exactly which branch/fork?

**Comment by manoharreddyporeddy** [comment]
There are many more branches than they were earlier.It is possible some branches were deleted, I could not find one parse.
Branches can be graphical seen, also on who fixed whatSee at:  https://github.com/ios-driver/ios-driver/network
Hope that helps. Else let me know, I will dig into my project and suggest where exactly the sleeps are required.
Date: Mon, 6 Jul 2015 05:51:59 -0700

**Comment by KunalKathrotia** [comment]
@pgmreddy Thanks for your reply. I've already tried to explore that fix on that link you are talking about but couldn't find any. And without any knowledge of iOS-driver putting sleeps randomly in the code doesn't make any sense, So it will be great if you can point the exact place where that sleep thing works. Thanks again.

**Comment by manoharreddyporeddy** [comment]
Sure, I will.Because I need extract sleeps in my old code & find them on ios-driver too, I will revert in 2 days, right now a bit busy writing casino game server. Thanks for your patience.
Date: Mon, 6 Jul 2015 22:02:06 -0700

**Comment by KunalKathrotia** [comment]
@pgmreddy Thanks no problem. BTW it seems it was the issue with some settings which were required and not enabled on the phone. we found that there are two things which required in order to resolve this issue and it's working.
1. We have turned the web inspector on in safari setting, and
2. DeveloperDiskImage.dmg image file need to be mount in iPhone before running iOS-driver.

**Comment by adataylor** [comment]
Were those the only two fixes you made, or were there others? Experiencing the same error with the latest build, attempting to run on both simulator and physical device.

**Comment by KunalKathrotia** [comment]
Yes these were the only fixes we have made. The first setting is easy, for the second one keep the iPhone usb connected and run the XCode with updated version. This is necessary for the first time only because XCode will push the debug server in iPhone and than iOS driver will be able to detect the device.
