### ISSUE TITLE
ios-driver node problem: cannot register a node to a running grid hub

### ISSUE THREAD

**Issue by moofnbg** [ios-driver/ios-driver#390]
Hi guys,
i need your help. I want to add ios driver as a node of a running grid hub. 
I proceed as described on the site: https://ios-driver.github.io/ios-driver/?page=scaling

Step 1:
I have a windows7 machine where i start the grid hub with the following command:

$java -cp "ios-grid-0.6.6-SNAPSHOT.jar;selenium-server-standalone-2.47.1.jar" org.openqa.grid.selenium.GridLauncher -role hub

That ist ok. The Grid hub goes up and is running:
INFO - Nodes should register to http://10.51.18.26:4444/grid/register
INFO - Selenium Grid hub is up and running

Step 2: 
I want to add a ios driver on a MacBookPro as a node. I proceed with the following command:
$java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -hub http://10.51.18.26:4444/grid/register -proxy org.uiautomation.ios.grid.IOSRemoteProxy -host 10.51.16.171 -port 5555

-> that is the output on the MAC:

lpnb1499:iosdriver online$ java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -hub http://10.51.18.26:4444/grid/register -proxy org.uiautomation.ios.grid.IOSRemoteProxy -host 10.51.16.171 -port 5555
17:13:111 INFO ApplicationStore.<init>  App archive folder:/Users/online/development/iosdriver/applications
version:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560
Beta features enabled (enabled by -real flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:5555/inspector/
Tests can access the server at http://0.0.0.0:5555/wd/hub
Server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/online/development/iosdriver/applications' for new applications
Archived apps: /Users/online/development/iosdriver/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20141009-1559,sha:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560)
Running on: Mac OS X 10.10.3 (x86_64)
Using java: 1.8.0_51
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.3, build: 57536
Using iOS version 8.3
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
    CFBundleName=Safari,CFBundleVersion=600.1.4,/Users/online/.ios-driver/safariCopies/safari-8.3.app
2015-08-12 15:17:13.878:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2015-08-12 15:17:13.930:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:5555
17:14:093 INFO StoppableRegisteringRemote.startRegistrationProcess  using the json request : {"capabilities":[{"NSLocationWhenInUseUsageDescription":"Websites you visit may request your location.","CFBundleDevelopmentRegion":"English","UIBackgroundStyle":"UIBackgroundStyleDarkBlur","SBUsesNetwork":3,"CFBundleURLTypes~ipod":[{"CFBundleURLName":"Web App URL","CFBundleURLSchemes":["webclip"],"CFBundleURLIsPrivate":true},{"CFBundleURLName":"Web site URL","CFBundleURLSchemes":["http","https"]},{"CFBundleURLName":"Radar URL","CFBundleURLSchemes":["rdar","radar"]},{"CFBundleURLName":"FTP URL","CFBundleURLSchemes":["ftp"]},{"CFBundleURLName":"Web Search URL","CFBundleURLSchemes":["x-web-search"]},{"CFBundleURLName":"MobileSafari Tab URL","CFBundleURLSchemes":["com-apple-mobilesafari-tab"],"CFBundleURLIsPrivate":true}],"CFBundleIdentifier":"com.apple.mobilesafari","SBMatchingApplicationGenres":["Productivity","Utilities"],"LSRequiresIPhoneOS":true,"CFBundleExecutable":"MobileSafari","instruments":true,"SafariProductVersion":"8.0","supportedLanguages":["ar","ca","cs","da","de","el","en","en-GB","es","fi","fr","fr-CA","he","hi","hr","hu","id","it","ja","ko","ms","nl","no","pl","pt","pt-PT","ro","ru","sk","sv","th","tr","uk","vi","zh-CN","zh-HK","zh-TW"],"MPSupportsExternallyPlayableContent":true,"CFBundlePackageType":"APPL","CFBundleURLTypes~ipad":[{"CFBundleURLName":"Web App URL","CFBundleURLSchemes":["webclip"],"CFBundleURLIsPrivate":true},{"CFBundleURLName":"Web site URL","CFBundleURLSchemes":["http","https"]},{"CFBundleURLName":"FTP URL","CFBundleURLSchemes":["ftp"]},{"CFBundleURLName":"Web Search URL","CFBundleURLSchemes":["x-web-search"]},{"CFBundleURLName":"MobileSafari Tab URL","CFBundleURLSchemes":["com-apple-mobilesafari-tab"],"CFBundleURLIsPrivate":true}],"CFBundleSupportedPlatforms":["iPhoneSimulator"],"simulator":true,"CFBundleDisplayName":"Safari","timeHack":false,"NSUserActivityTypes":["NSUserActivityTypeBrowsingWeb"],"UIViewControllerBasedStatusBarAppearance":true,"UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight","UIInterfaceOrientationPortraitUpsideDown"],"resources":{"CFBundleIconFile":"/wd/hub/resources/hash=-2111658072"},"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"CFBundleInfoDictionaryVersion":"6.0","CFBundleSignature":"????","DTSDKName":"iphonesimulator8.3","UIStatusBarTintParameters":{"UINavigationBar":{"Style":"UIBarStyleDefault"}},"CFBundleVersion":"600.1.4","applicationPath":"/Users/online/.ios-driver/safariCopies/safari-8.3.app","deviceAlt":["iphone","ipod","ipad"],"UIDeviceFamily":[1,2],"device_Alt":["iphone","ipad"],"UIApplicationDisableLegacyAutorotationKey":true,"UIBackgroundModes":["audio","continuousFallback"],"CFBundleShortVersionString":"8.0","sdkVersion_alt":["8.3"],"sdkVersion":"8.3","CFBundleIcons":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["icon-about@2x.png","icon-about@3x~iphone.png","icon-about~ipad.png","icon-spotlight@2x.png","icon-spotlight@3x~iphone.png","icon-spotlight~ipad.png","icon-table@2x.png","icon-table@3x~iphone.png","icon-table~ipad.png","icon@2x~ipad.png","icon@2x~iphone.png","icon@3x~iphone.png","icon~ipad.png"],"UIPrenderedIcon":true}},"MallocBehavior":{"NanoAllocator":false},"UIHasPrefs":true,"DTPlatformName":"iphonesimulator","device":"iphone","CFBundleURLTypes~iphone":[{"CFBundleURLName":"Web App URL","CFBundleURLSchemes":["webclip"],"CFBundleURLIsPrivate":true},{"CFBundleURLName":"Web site URL","CFBundleURLSchemes":["http","https"]},{"CFBundleURLName":"Radar URL","CFBundleURLSchemes":["rdar","radar"]},{"CFBundleURLName":"FTP URL","CFBundleURLSchemes":["ftp"]},{"CFBundleURLName":"Web Search URL","CFBundleURLSchemes":["x-web-search"]},{"CFBundleURLName":"MobileSafari Tab URL","CFBundleURLSchemes":["com-apple-mobilesafari-tab"],"CFBundleURLIsPrivate":true}]}],"configuration":{"proxy":"org.uiautomation.ios.grid.IOSRemoteProxy","remoteHost":"http://10.51.16.171:5555","hubHost":"10.51.18.26","maxSession":1,"registerCycle":5000,"hubPort":4444,"register":true},"class":"org.openqa.grid.common.RegistrationRequest"}
17:14:096 INFO StoppableRegisteringRemote$1.run  Starting auto register thread. Will try to register every 5000 ms.
17:14:096 INFO StoppableRegisteringRemote.registerToHub  Registering the node to hub :http://10.51.18.26:4444/grid/register
17:14:148 INFO StoppableRegisteringRemote$1.run  couldn't register this node : Error sending the registration request.
17:19:165 INFO StoppableRegisteringRemote.registerToHub  Registering the node to hub :http://10.51.18.26:4444/grid/register
17:19:174 INFO StoppableRegisteringRemote$1.run  couldn't register this node : Error sending the registration request.
^C2015-08-12 15:17:25.002:INFO:oejsh.ContextHandler:stopped o.e.j.s.ServletContextHandler{/,null}
2015-08-12 15:17:25.003:INFO:oejsh.ContextHandler:stopped o.e.j.s.ServletContextHandler{/static,null}

And this is the output on the Windows (grid hub):
15:16:10.856 WARN - Max instance not specified. Using default = 1 instance
2015-08-12 15:16:10.857:WARN:osjs.ServletHandler:/grid/register
java.security.InvalidParameterException: Error: org/json/JSONException
        at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:432)
        at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:86)
        at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.seleniumhq.jetty7.servlet.ServletHolder.handle(ServletHolder.java:565)
        at org.seleniumhq.jetty7.servlet.ServletHandler.doHandle(ServletHandler.java:479)
        at org.seleniumhq.jetty7.server.session.SessionHandler.doHandle(SessionHandler.java:225)
        at org.seleniumhq.jetty7.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.seleniumhq.jetty7.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.seleniumhq.jetty7.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.seleniumhq.jetty7.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.seleniumhq.jetty7.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.seleniumhq.jetty7.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.seleniumhq.jetty7.server.Server.handle(Server.java:349)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
        at org.seleniumhq.jetty7.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:47)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
        at org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
        at org.seleniumhq.jetty7.http.HttpParser.parseNext(HttpParser.java:857)
        at org.seleniumhq.jetty7.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.seleniumhq.jetty7.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:66)
        at org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:254)
        at org.seleniumhq.jetty7.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Unknown Source)

PLEASE help me. I don't have no more idea how to proceed :-(
Google says also nothing i could use as a solution for my problem.

**Comment by moofnbg** [comment]
Can you help me?

**Comment by DanielSmedegaardBuus** [comment]
I'm seeing the same thing (java.security.InvalidParameterException: Error: org/json/JSONException). This is with both the hub and node running on OS X 10.11, though. Java 8.

**Comment by DanielSmedegaardBuus** [comment]
Doesn't seem to be a Selenium server version issue. I tried a few older versions, notably 2.43.1 (which was the stable one at the time the ios plug 0.6.6-SNAPSHOT was built) which gives a `java.security.InvalidParameterException: Error: org/uiautomation/ios/grid/StatusToCapabilitiesService` error which indicates lack of support(?) and 2.44.0 (which would be the unstable version at the time), which errors out with the same JSON error as 2.49.0 does...

**Comment by abacaj** [comment]
I'm replying to this because I had the same exact issue. @moofnbg, @DanielSmedegaardBuus

### The problem:

The build version of `ios-grid-plugin-0.6.6` seems to be incompatible with the version of `selenium-server-standalone-2.47.1` that is using a different version of `org-json`. This issue is dependency conflicts across class paths, i.e whoever built this didn't really test it - or isn't being kept up to date.

### Solution:
1. Download version 2.4.4 of the grid - https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
2. Launch grid with this command:
   `java -cp ios-grid-plugin-0.6.6-SNAPSHOT.jar:ios-server-standalone-0.6.6-SNAPSHOT.jar:selenium-server-standalone-2.44.0.jar org.openqa.grid.selenium.GridLauncher -role hub`
3. Launch node with this command (note: replace the urls as necessary, I tried this locally):
   <small>_Another note: Change `-aut` to the path of your IOS app._</small>

```
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut ios-build.ipa -hub http://127.0.0.1:4444/grid/register -proxy org.uiautomation.ios.grid.IOSMutableRemoteProxy -host 127.0.0.1 -port 5555
```

### Working:

![node](https://cloud.githubusercontent.com/assets/7272343/12724266/224f24ca-c8db-11e5-9f5b-7b2e26639687.PNG)

Done - registered and working.

**Comment by moofnbg** [comment]
Hi Guys, thanks for the tip. I will try it out nexy days!

**Comment by freezer-glp** [comment]
hi, I met this issue too. 
I am using`selenium-server-standalone-2.53.1.jar` and `ios-grid-plugin-0.6.6-snapshot.jar` to start hub, and using `ios-driver-0.6.6-snapshot.jar` to start node.
I've tried to use `selenium-server-standalone-2.44.0.jar` but I have
`java.lang.IllegalArgumentException: No enum constant org.openqa.selenium.Platform.WIN10`

can anybody help me?
Thx
