### ISSUE TITLE
Cannot get iPad Simulator Safari to work

### ISSUE THREAD

**Issue by CMTaylor** [ios-driver/ios-driver#398]
I followed the instructions here: http://ios-driver.github.io/ios-driver/?page=safari 
After doing the permission changes to the SDK files I started the ios-server like this:

```
cmtaylor$ java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -port 42424
06:12:939 INFO ApplicationStore.<init>  App archive folder:/Users/cmtaylor/_AccuRev_/RF-integ-CORE-Martin_Mac/TI-RF/robotframework-ExamCalcLibrary/3rdPartyDrivers/Java/applications
version:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560
Beta features enabled (enabled by -real flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:42424/inspector/
Tests can access the server at http://0.0.0.0:42424/wd/hub
Server status: http://0.0.0.0:42424/wd/hub/status
Connected devices: http://0.0.0.0:42424/wd/hub/devices/all
Applications: http://0.0.0.0:42424/wd/hub/applications/all
Capabilities: http://0.0.0.0:42424/wd/hub/capabilities/all
...
Build info: ios-driver 0.6.6-SNAPSHOT (built:20141009-1559,sha:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560)
Running on: Mac OS X 10.10.3 (x86_64)
Using java: 1.7.0_71
Using Xcode install: /Applications/Xcode.app
Using instruments: version:6.4, build: 57082
Using iOS version 8.4
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
    CFBundleName=Safari,CFBundleVersion=600.1.4,/Users/cmtaylor/.ios-driver/safariCopies/safari-8.4.app
2016-01-08 16:06:14.168:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2016-01-08 16:06:14.247:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:42424
```

Then in another terminal window I used interactive Python to do this:

```
cmtaylor$ python
ActivePython 2.7.2.5 (ActiveState Software Inc.) based on
Python 2.7.2 (default, Jun 24 2011, 12:20:15) 
[GCC 4.2.1 (Apple Inc. build 5664)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> driver = webdriver.Remote("http://0.0.0.0:42424/wd/hub", webdriver.DesiredCapabilities.IPAD)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 87, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 141, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: The server cannot run Capabilities [{platform=MAC, javascriptEnabled=true, CFBundleIdentifier=com.apple.mobilesafari, CFBundleName=Safari, locale=en_GB, variation=Retina, device=ipad, version=, sdkVersion=8.4}] at the moment.org.uiautomation.ios.application.APPIOSApplication cannot be cast to org.uiautomation.ios.application.IPAApplication
Stacktrace:
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.safeStart (NewSessionNHandler.java:101)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle (NewSessionNHandler.java:55)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators (BaseCommandHandler.java:110)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse (IOSServlet.java:158)
    at org.uiautomation.ios.servlet.IOSServlet.process (IOSServlet.java:85)
    at org.uiautomation.ios.servlet.IOSServlet.doPost (IOSServlet.java:60)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerList.handle (HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle (Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest (AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content (AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content (AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext (HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable (HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle (AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle (SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run (SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:543)
    at java.lang.Thread.run (Thread.java:745)
```

Meanwhile the ios-driver server window showed a similar error message:

```
07:30:674 INFO NewSessionNHandler.safeStart  The server cannot run Capabilities [{platform=MAC, javascriptEnabled=true, CFBundleIdentifier=com.apple.mobilesafari, CFBundleName=Safari, locale=en_GB, variation=Retina, device=ipad, version=, sdkVersion=8.4}] at the moment.org.uiautomation.ios.application.APPIOSApplication cannot be cast to org.uiautomation.ios.application.IPAApplication
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'cmtaylor.home', ip: '192.168.1.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.7.0_71'
Driver info: driver.version: unknown
```

Any fixes to the instructions referenced above, or other help to get this working, would be very much appreciated.

Thanks,
Martin

**Comment by Send2gal** [comment]
Have the same issue.
`
java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -port 4444
55:19:241 INFO ApplicationStore.<init>  App archive folder:/Users/Gal/Documents/selenium/ios/applications
version:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560
Beta features enabled (enabled by -real flag): false
Simulator enabled : true
Inspector: http://0.0.0.0:4444/inspector/
Tests can access the server at http://0.0.0.0:4444/wd/hub
Server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/Gal/Documents/selenium/ios/applications' for new applications
Archived apps: /Users/Gal/Documents/selenium/ios/applications
Build info: ios-driver 0.6.6-SNAPSHOT (built:20141009-1559,sha:663b7cc0a7a48ff629b1bcb39bbd78aed1c1e560)
Running on: Mac OS X 10.11.3 (x86_64)
Using java: 1.8.0_65
Using Xcode install: /Applications/Xcode.app
Using instruments: version:7.2, build: 59503
Using iOS version 9.2
iOS >= 6.0. Safari and hybrid apps are supported.
Applications :
    CFBundleName=Safari,CFBundleVersion=601.1,/Users/Gal/.ios-driver/safariCopies/safari-9.2.app
2016-01-28 14:55:19.782:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2016-01-28 14:55:19.826:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4444
`
run python script:

`from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub',
                          desired_capabilities=DesiredCapabilities.IPAD)`

and getting:

`Traceback (most recent call last):
  File "/Users/Gal/PycharmProjects/qa-automation/tests/test.py", line 6, in <module>
    desired_capabilities=DesiredCapabilities.IPAD)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 87, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 141, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: The server cannot run Capabilities [{javascriptEnabled=true, sdkVersion=9.2, CFBundleIdentifier=com.apple.mobilesafari, locale=en_GB, CFBundleName=Safari, device=ipad, version=, platform=MAC, variation=Retina}] at the moment.org.uiautomation.ios.application.APPIOSApplication cannot be cast to org.uiautomation.ios.application.IPAApplication
Stacktrace:
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.safeStart (NewSessionNHandler.java:101)
    at org.uiautomation.ios.command.uiautomation.NewSessionNHandler.handle (NewSessionNHandler.java:55)
    at org.uiautomation.ios.command.BaseCommandHandler.handleAndRunDecorators (BaseCommandHandler.java:110)
    at org.uiautomation.ios.servlet.IOSServlet.getResponse (IOSServlet.java:158)
    at org.uiautomation.ios.servlet.IOSServlet.process (IOSServlet.java:85)
    at org.uiautomation.ios.servlet.IOSServlet.doPost (IOSServlet.java:60)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:229)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerList.handle (HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle (Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest (AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content (AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content (AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext (HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable (HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle (AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle (SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run (SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:543)
    at java.lang.Thread.run (Thread.java:745)`

**Comment by hpb0412** [comment]
I had similar issue on both 0.6.5 and 0.6.6 snapshot but with iPhone simulator.

Here is the situation:
- iOS version : 9.2
- XCode : 7.2 Beta
- Chmod as instruction on Safari instruction page
- Testing code as first example on Safari instruction page
- Java with Eclipse Luna SR2

`Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: expected 1 result for automation on instruments -s , got []
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_40'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_40'
Driver info: driver.version: unknown
Command duration or timeout: 9.40 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:191)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
    at First.main(First.java:14)
Caused by: org.openqa.selenium.SessionNotCreatedException: expected 1 result for automation on instruments -s , got []
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_40'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_40'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_40'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.command.uiautomation.NewSessionNHandler.handle(NewSessionNHandler.java:54)
    at org.uiautomation.ios.server.command.BaseCommandHandler.handleAndRunDecorators(BaseCommandHandler.java:86)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:144)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:85)
    at org.uiautomation.ios.server.servlet.IOSServlet.doPost(IOSServlet.java:57)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:745)
`
