### ISSUE TITLE
WebDriverException: cannot find command for GET

### ISSUE THREAD

**Issue by freynaud** [ios-driver/ios-driver#4]
Hey @freynaud 

I am able to run ios-driver perfectly well on one of my apps. I tried setting up the tests with a new one but am seeing the following when i try to access "http://localhost:4444/wd/hub" (Wonder if i missed any step here):

org.openqa.selenium.WebDriverException: cannot find command for GET, /
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.6.0_37'
Driver info: driver.version: unknown
    at org.uiautomation.ios.communication.WebDriverLikeCommand.getCommand(WebDriverLikeCommand.java:286)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getGenericCommand(WebDriverLikeRequest.java:115)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getVariableValue(WebDriverLikeRequest.java:119)
    at org.uiautomation.ios.communication.WebDriverLikeRequest.getSession(WebDriverLikeRequest.java:132)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:139)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:83)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:45)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:680)

**Comment by freynaud** [comment]
Check to see if you have the BundleName wrong for your application. After starting the server in Terminal it displays CFBundleName="yourBundle", CFBundleVersion="yourVersion". Make sure these match what is in the line
DesiredCapabilities cap = IOSCapabilities.iphone("yourBundleName", "yourVersion");

I was using the CFBundleExecutable instead of CFBundleName and it was causing me to see this exception.

**Comment by freynaud** [comment]
Hi,
there is nothing bound to http://localhost:4444/wd/hub
If you want to see the status, it's http://localhost:4444/wd/hub/status

François

**Comment by lukeis** [comment]
closing this issue, françois' last comment addresses it.
