### ISSUE TITLE
WebDriverException: bug.null while trying to open the inspector

### ISSUE THREAD

**Issue by freynaud** [ios-driver/ios-driver#5]
Hey @freynaud 

I had gotten the http://localhost:4444/inspector/ working earlier with your help on my app. But for some reason, today it doesn't seem to work and i haven't changed anything. And my test is running and/or paused when im trying to do this.

SYMPTOMS:
When i go to "http://localhost:4444/inspector/", i actually get redirected to "http://localhost:4444/inspector/session//home"

IOS-SERVER logs:
org.openqa.selenium.WebDriverException: bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.6.0_37'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:153)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:83)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:45)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.uiautomation.ios.server.CommandMapping.createHandler(CommandMapping.java:297)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:131)
    ... 25 more
Caused by: org.openqa.selenium.WebDriverException: Cannot find session  on the sesver.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.6.0_37'
Driver info: driver.version: IOSDriver
    at org.uiautomation.ios.server.IOSDriver.getSession(IOSDriver.java:192)
    at org.uiautomation.ios.server.command.BaseCommandHandler.<init>(BaseCommandHandler.java:42)
    at org.uiautomation.ios.server.command.BaseNativeCommandHandler.<init>(BaseNativeCommandHandler.java:23)
    at org.uiautomation.ios.server.command.UIAScriptHandler.<init>(UIAScriptHandler.java:31)
    at org.uiautomation.ios.server.command.uiautomation.LogElementTreeNHandler.<init>(LogElementTreeNHandler.java:42)
    ... 31 more
org.openqa.selenium.WebDriverException: java.lang.ClassCastException: java.lang.String cannot be cast to org.openqa.selenium.remote.Response
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.6.0_37'
Driver info: driver.version: RemoteUIADriver
    at org.uiautomation.ios.client.uiamodels.impl.RemoteUIADriver.execute(RemoteUIADriver.java:201)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteUIADriver.logElementTree(RemoteUIADriver.java:213)
    at org.uiautomation.ios.inspector.model.IDESessionModelImpl.refresh(IDESessionModelImpl.java:77)
    at org.uiautomation.ios.inspector.controllers.IDEController.handle(IDEController.java:43)
    at org.uiautomation.ios.inspector.IDEServlet.doGet(IDEServlet.java:93)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.openqa.selenium.remote.Response
    at org.uiautomation.ios.communication.Helper.exctractResponse(Helper.java:58)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteUIADriver.execute(RemoteUIADriver.java:199)
    ... 27 more
16:37:666 WARNING IDEServlet.doGet  java.lang.ClassCastException: java.lang.String cannot be cast to org.openqa.selenium.remote.Response
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.6.0_37'
Driver info: driver.version: RemoteUIADriver

**Comment by freynaud** [comment]
I'll add more debug. there is something wrong with the redirect. The session id is missing.

**Comment by freynaud** [comment]
Thanks @freynaud 

Is there any other way i can use the inspector as a workaround?

**Comment by freynaud** [comment]
The server is single threaded. "my test is running and/or paused when im trying to do this." won't work.
Can you try with the test paused only ?

**Comment by freynaud** [comment]
I did try it with the test paused. It still gives me the same issue.

**Comment by freynaud** [comment]
I've been having the same issue, when logging getSessionId() from the test environment I get the unique ID, but when it's compared in IOSDriver.getSession on the server, it appears null.

**Comment by lukeis** [comment]
@jayeshpatil can you let us know if you have the same issue with 0.6?

**Comment by freynaud** [comment]
doesn't seem to be a problem anymore.

**Comment by iboyarinov** [comment]
I have the same problem with latest updates

**Comment by nicegraham** [comment]
can you make sure you have the trailing / other people have had problems when they didn't have that
http://localhost:4444/inspector/

**Comment by iboyarinov** [comment]
That what I get when try to start ios-server
Igors-Mac-mini:ios-driver igorboyarinov$ java -jar ios-server-0.7.0-SNAPSHOT.jar -aut /Users/igorboyarinov/Dev/build/Release-iphonesimulator/TailoringTest.app
Exception in thread "main" org.openqa.selenium.WebDriverException: there was an error.stderr is not empty
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_21'
Driver info: driver.version: unknown
    at org.uiautomation.ios.utils.ShowSDKsPasrer.getSDKs(ClassicCommands.java:147)
    at org.uiautomation.ios.utils.ClassicCommands.getInstalledSDKs(ClassicCommands.java:108)
    at org.uiautomation.ios.utils.ClassicCommands.getDefaultSDK(ClassicCommands.java:113)
    at org.uiautomation.ios.server.HostInfo.<init>(HostInfo.java:45)
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:54)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:118)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:91)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:62)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:66)

**Comment by nicegraham** [comment]
@iboyarinov this looks like something different, can you please open a new issue?
