### ISSUE TITLE
Error starting ios-server using the -beta flag

### ISSUE THREAD

**Issue by rdissertori** [ios-driver/ios-driver#54]
```
java -jar ios-server-0.7.0-SNAPSHOT.jar -beta -hub http://build.ecom.at:4444/grid/register -host 10.0.10.124 -port 5555
loading lib /generated/libiosdriver.dylib
loading lib /generated/libiosdriver.dylib
Cannot find /generated/libiosdriver.dylib as a pre-generated artefact.
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.uiautomation.iosdriver.services.jnitools.JNIService.<clinit>(JNIService.java:8)
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:58)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:115)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:88)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:61)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:65)
Caused by: org.uiautomation.iosdriver.IOSDriverServiceException: Cannot find /generated/libiosdriver.dylib as a pre-generated artefact.
    at org.uiautomation.iosdriver.services.jnitools.JniLoader.extractFromJar(JniLoader.java:43)
    at org.uiautomation.iosdriver.services.jnitools.JniLoader.<init>(JniLoader.java:23)
    at org.uiautomation.iosdriver.services.jnitools.JniLoader.<clinit>(JniLoader.java:15)
    ... 6 more
```

**Comment by nicegraham** [comment]
I've seen this happen when the libimobile submodule is not in sync. I've had intellij do something weird with the submodule linking which reseting to head and getting latest has fixed, or on our build machine we just blast the local copy and clone it again.

**Comment by rdissertori** [comment]
Yes thank you that did it

**Comment by nicegraham** [comment]
I'm actually seeing this error now - and getting a clean copy hasn't fixed it, is there a library missing?

**Comment by rdissertori** [comment]
kinda embarassing :)
I thought it worked when I deleted old resources and freshly built it, but it seems I just forgot to add the "-beta" parameter after that. So yes thanks for re-opening

**Comment by nicegraham** [comment]
at least it's consistent! :)

**Comment by freynaud** [comment]
https://github.com/ios-driver/libimobile-java/tree/b5cc5d04e8c3e397467fd593e94f07f854c15b3c/src/main/resources/generated
need to be there. Or you need to generate it yourself using
libimoobile-java/build.sh

You need libimobile installed for the build script to work

François

**Comment by nicegraham** [comment]
I got the latest code, I'm now seeing:
https://gist.github.com/nicegraham/5575760

**Comment by nicegraham** [comment]
@rdissertori it's more complicated than anticipated to package all the files needed. Can you use an older version of the branch for now? Or if you need the latest you'll have to compile libimobile yourself I'm afraid.

**Comment by rdissertori** [comment]
ok thank you @freynaud and @nicegraham  - this will do.

**Comment by rdissertori** [comment]
phew - I thought it would be easier - but there's tons of dependencies which I'm afraid I don't have the time to take care of. I was also getting similar errormessages as @nicegraham mentioned

```
loading lib /generated/libiosdriver.dylib
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/bj/2nx3f58x2qd55ftxyy3jtydm0000gn/T/libiosdriver8649139451292968441.jnilib: dlopen(/private/var/folders/bj/2nx3f58x2qd55ftxyy3jtydm0000gn/T/libiosdriver8649139451292968441.jnilib, 1): Library not loaded: /usr/local/lib/libusbmuxd.2.dylib
```

which wanted me to install libplist, libimobiledevice

those had dependencies themselves on pkg-config, glib2, xmllib and so on and forth (at this point I gave up)
opening this issue again in order for you to keep me updated in here.

so no, installing libimobiledevice depending on libusbmuxd and so many follow-up dependencies isn't really an option to me.

Thanks!

**Comment by nicegraham** [comment]
issue https://github.com/ios-driver/ios-driver/issues/59 captures this most recent dependency problem - closing this issue
