### ISSUE TITLE
If a click triggers new page load the page is not waited to finish loading

### ISSUE THREAD

**Issue by ivanlvasilev** [ios-driver/ios-driver#55]
The idea about page loading in WebDriver is that the script/client shouldn't worry about the page ready state. In ios-driver webDriver.get() waits for the new page to load. However if later the script clicks to an element for example select new option from select menu which triggers new page to load ios-driver doesn't wait for loading to complete and returns control to client. This can in turn cause the script to throw an error if checks for an element present on the page.

**Comment by PavithraNavaneeth** [comment]
Any update on this bug?
For me, in the login page after submit it is not waiting for the new page load to complete and the new element.click is throwing the below error (if i don't mention Thread.sleep)

Exception in thread "DefaultMessageHandler-161" org.openqa.selenium.WebDriverException: Error creating an event generated by the webview:{"method":"DOM.childNodeInserted","params":{"node":{"childNodeCount":0,"localName":"iframe","nodeId":192,"nodeValue":"","nodeName":"IFRAME","attributes":["frameborder","0","style","border: 0px; vertical-align: bottom; position: absolute; left: 1px; top: 1px; height: 1px; width: 1px; visibility: hidden; ","src","javascript:\"\""],"nodeType":1},"parentNodeId":154,"previousNodeId":191}}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.4', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at org.uiautomation.ios.wkrdp.events.EventFactory.createEvent(EventFactory.java:33)
    at org.uiautomation.ios.context.BaseWebInspector.onMessage(BaseWebInspector.java:545)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.process(DefaultMessageHandler.java:76)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.access$000(DefaultMessageHandler.java:31)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler$1.run(DefaultMessageHandler.java:64)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.uiautomation.ios.wkrdp.events.EventFactory.createObject(EventFactory.java:45)
    at org.uiautomation.ios.wkrdp.events.EventFactory.createEvent(EventFactory.java:29)
    ... 4 more
Caused by: org.json.JSONException: JSONObject["contentDocument"] not found.
    at org.json.JSONObject.get(JSONObject.java:499)
    at org.json.JSONObject.getJSONObject(JSONObject.java:593)
    at org.uiautomation.ios.wkrdp.events.inserted.ChildIframeInserted.<init>(ChildIframeInserted.java:59)
    ... 10 more

**Comment by coding-yogi** [comment]
though this issue has been raised long back.. even I am facing this issue with latest server jar.
ImplicitWait doesnt seem to help either. I think you can fire a java script and keep it polling till load status is complete
