### ISSUE TITLE
Issue: Library not loaded: /usr/local/lib/libusbmuxd.2.dylib 

### ISSUE THREAD

**Issue by xuyuansi** [ios-driver/ios-driver#59]
I was running the main method in org.uiautomation.ios.Demo.java of ios-driver module, but got the following error message. How to solve the problem please? 

loading lib /generated/libiosdriver.dylib
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/h5/1qxsrlmj0v9g_97gncb5h_zw0m6zq7/T/libiosdriver5387217954960949929.jnilib: dlopen(/private/var/folders/h5/1qxsrlmj0v9g_97gncb5h_zw0m6zq7/T/libiosdriver5387217954960949929.jnilib, 1): Library not loaded: /usr/local/lib/libusbmuxd.2.dylib
  Referenced from: /private/var/folders/h5/1qxsrlmj0v9g_97gncb5h_zw0m6zq7/T/libiosdriver5387217954960949929.jnilib
  Reason: image not found
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1939)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1864)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
    at java.lang.Runtime.load0(Runtime.java:792)
    at java.lang.System.load(System.java:1059)
    at org.uiautomation.iosdriver.services.jnitools.JNIService.<clinit>(JNIService.java:8)
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:58)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:118)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:57)
    at org.uiautomation.ios.Demo.main(Demo.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

**Comment by nicegraham** [comment]
hi @xuyuansi 

This is a known issue right now which we are working to resolve, it should only be a problem if you're running with the -beta flag which is only needed for physical devices. It's only a issue on the latest code so if you can use 0.6.0 for now or pull from an older commit it shouldn't be an issue for you. 

cheers,
Graham

**Comment by xuyuansi** [comment]
Got it. Thanks! 

Cheers, 
Xuyuan
