### ISSUE TITLE
Application Under Test is terminated in the simulator on loading the inspector.

### ISSUE THREAD

**Issue by freynaud** [ios-driver/ios-driver#6]
Application Under Test (AUT) got terminated, on loading the inspector (http://localhost:4444/inspector/).
There is no exception / error info at the server console.

After that, as an alternative, in the code, I have used getPageSource() to view the page details. Following is observed.
Once application is loaded (after authentication), on issuing getPageSource(), kills the application in the simulator. Got the following exception
trace at the server end.

org.json.JSONException: JSONObject["translation"] not found.
    at org.json.JSONObject.get(JSONObject.java:499)
    at org.json.JSONObject.getBoolean(JSONObject.java:515)
    at org.uiautomation.ios.server.command.uiautomation.LogElementTreeNHandler.<init>(LogElementTreeNHandler.java:52)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.uiautomation.ios.server.CommandMapping.createHandler(CommandMapping.java:297)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:131)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:83)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:45)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:680)
org.openqa.selenium.WebDriverException: bug.null
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8', java.version: '1.6.0_37'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:153)
    at org.uiautomation.ios.server.servlet.IOSServlet.process(IOSServlet.java:83)
    at org.uiautomation.ios.server.servlet.IOSServlet.doGet(IOSServlet.java:45)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.uiautomation.ios.server.CommandMapping.createHandler(CommandMapping.java:297)
    at org.uiautomation.ios.server.servlet.IOSServlet.getResponse(IOSServlet.java:131)
    ... 25 more
Caused by: org.openqa.selenium.WebDriverException: wrong params
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8', java.version: '1.6.0_37'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.command.uiautomation.LogElementTreeNHandler.<init>(LogElementTreeNHandler.java:65)
    ... 31 more
Caused by: org.json.JSONException: JSONObject["attachScreenshot"] not found.
    at org.json.JSONObject.get(JSONObject.java:499)
    at org.json.JSONObject.getBoolean(JSONObject.java:515)
    at org.uiautomation.ios.server.command.uiautomation.LogElementTreeNHandler.<init>(LogElementTreeNHandler.java:61)
    ... 31 more

**Comment by freynaud** [comment]
the server is single threaded. You cannot have both the test and the inspector sending command at the same time.
You need to pause the test, then open the inspector. If the tests keeps sending commands while the inspector is being loaded, you'll have issues.
Is it the scenario you're trying ?

**Comment by freynaud** [comment]
Hi.,

Thanks for the reply.

I am not trying to run both at the same.
1. I wanted to view the list of controls at the in AUT's first screen. Todo
   that, I made the script to wait for the keyboard key from the script. The
   script would be waiting for the key from the user. Meanwhile, I went to the
   browser and trying to use inspector to view the controls.

When I was loading the inspector, the AUT got crashed.,

May be I can try pausing the script (in the debug mode) and give a
shot...and let you know my observations...

Thanks.,

rgds,
Saraav.

On Thu, Feb 14, 2013 at 12:20 PM, François Reynaud <notifications@github.com

**Comment by freynaud** [comment]
Hi.,

I paused the code in the debug mode and tried loading the inspector in the browser. The same issue is observed again like, the aut gets crashed... :(

Thanks.,

**Comment by freynaud** [comment]
are you trying on one of the demo app ? Could you share your test code ?

**Comment by freynaud** [comment]
Hi @freynaud,
Thanks for the reply.
No I am trying with my application.

I have captured the logElementTree output from Instruments app as plist file. Pls. let me know so that I can share...

Pls find the code that I have used.

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.Augmenter;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.Assert;
import org.uiautomation.ios.IOSCapabilities;

import bsh.StringUtil;

public class SkyBoxAutomationDemo {

```
public static final int TIMEOUT = 60000;
RemoteWebDriver driver;

public SkyBoxAutomationDemo() {

}

public boolean setup() throws Exception
{
    boolean status = false;
    DesiredCapabilities cap = IOSCapabilities.iphone("SkyboxMobileUniversal", "1.0");
    cap.setCapability(IOSCapabilities.LANGUAGE, "en");

    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), cap);
    status = true;
    System.out.println("Launched the application");
    return status;
}

public void teardown() {

    try {
        if(driver != null) {
            System.out.println("Terminating the application...");
            driver.quit();
        }
    } catch(Exception e) {
        e.printStackTrace();
    }
}

public boolean verifyiForgot() throws Exception {

    boolean status = false;

    Assert.assertTrue(setup(), "Failed to setup the test environment for SkyBox Testing");

    List<WebElement> btnList =  driver.findElements(By.xpath("//UIAButton[@name='iForgot']"));
    System.out.println("No. of iForgot in found as:" + btnList.size());

    //WebElement btnSubmit = driver.findElement(By.xpath("//UIAButton[@name='iForgot'] + UIAButton[@name='Sign In']"));
    WebElement btniForgot = null;
    if(btnList.size() >= 2) {
        btniForgot = btnList.get(1);
    } else {
        btniForgot = btnList.get(0);
    }
    btniForgot.click();

    List<WebElement> labelTextList =  driver.findElements(By.xpath("//UIAAlert/UIAStaticText"));
    System.out.println("No. of label text list found as:" + labelTextList.size());
    System.out.println("Data" + labelTextList.get(1).getAttribute("label"));

    List<WebElement> listOfButtons =  driver.findElements(By.xpath("//UIAAlert/UIAButton"));
    System.out.println("No. of buttons in the alert found as:" + listOfButtons.size());

    for(WebElement btn : listOfButtons) {
        String strLabel = btn.getAttribute("label");
        System.out.println("Btn lable as:" + strLabel);
        if(strLabel.equalsIgnoreCase("Cancel")) {
            System.out.println("Cancelling the iForgot app");
            btn.click();
            status = true;
        }
    }

    status = true;

    return status;
}

private boolean waitForElementPresent(String aElement) {
    boolean status = false;

    long startTime = System.currentTimeMillis();
    long endTime = startTime + TIMEOUT;

    while(startTime < endTime) {
        status = isElementPresent(aElement);
        if(status) {
            break;
        }

        try { Thread.sleep(500); } catch(Exception e) { }
        startTime= System.currentTimeMillis();
    }
    if(! status) {
        System.err.println("Element:" + aElement + " is found found after:" + TIMEOUT + " ms.");
    }
    return status;
}


private boolean isElementPresent(String aElement) {
    boolean status = false;

    try {
        //WebElement element = driver.findElementByXPath("//UIAKey[matches(@label, 'more')]");
        WebElement element = driver.findElementByXPath(aElement);
        if(element != null) {
            status = true;
        }
    } catch(Exception e) {

    }
    return status;
}

private Object executeScript(String script, Object... args) {
    return ((JavascriptExecutor) driver).executeScript(script, args);
}

private boolean typeTextUsingJS(WebElement txtElement, String aText) {
    boolean status = false;

    executeScript("UIATarget.localTarget().frontMostApp().keyboard().typeString('" + aText + "');");

    return status;
}

private boolean typeText(String aText) {
    boolean status = false;
    boolean isNumericMode = false;
    //aText = aText.toUpperCase();
    for(int i = 0; i < aText.length(); i++) {
        String aLocator = "//UIAKey[@label='" + aText.charAt(i) + "']";
        if(Character.isDigit(aText.charAt(i))) {
            //more, numbers
            if(! isNumericMode) {
                driver.findElementByXPath("//UIAKey[matches(@label, 'more')]").click();
                isNumericMode = true;
            }
        } else {
            isNumericMode = false;

        }
        driver.findElementByXPath(aLocator).click();
    }

    status = true;
    return status;
}

public boolean login() throws Exception {
    boolean status = false;

    Assert.assertTrue(setup(), "Failed to setup the test environment for SkyBox Testing");


    WebElement txtUsername = driver.findElement(By.className("UIATextField"));
    //System.out.println("The username value is:" + txtUsername.getAttribute("value"));
    txtUsername.click();
    //txtUsername.clear();
    //txtUsername.sendKeys("testuser");
    //typeText("vabbi");
    typeTextUsingJS(txtUsername, "vabbi");


    WebElement txtPassword = driver.findElement(By.xpath("//UIASecureTextField"));
    //System.out.println("The password value is:" + txtPassword.getAttribute("value"));
    txtPassword.click();
    //txtPassword.clear();
    //txtPassword.sendKeys("password");
    //typeText("apple1234");
    typeTextUsingJS(txtPassword, "Apple1234");

    List<WebElement> btnList =  driver.findElements(By.xpath("//UIAButton[@name='Sign In']"));
    System.out.println("No. of sign in found as:" + btnList.size());

    //for(WebElement e : btnList) {
    //  System.out.println("Sign In button label is:" + e.getAttribute("label"));
    //}

    //WebElement btnSubmit = driver.findElement(By.xpath("//UIAButton[@name='iForgot'] + UIAButton[@name='Sign In']"));
    WebElement btnSignIn = null;
    if(btnList.size() >= 2) {
        btnSignIn = btnList.get(1);
    } else {
        btnSignIn = btnList.get(0);
    }

    System.out.println("Sign In button label is:" + btnSignIn.getAttribute("label"));

    btnSignIn.click();

    System.out.println("Submit button has been clicked");

    //Thread.sleep(20000);
    //wait

    String f = getWorkingDirectory() + File.separator + System.currentTimeMillis() + ".png";
    System.out.println("Taking screenshot to:" + f);

    handleAlert();

    takeScreenshot(f);

    handleConfirmation("yes");

    takeScreenshot(f);
    //Thread.sleep(15000);

    //In the following function, I have set the break-point and loaded the inspector. AUT crashes..
    readInputFromCommandLine();

    //System.out.println("Page Source is:" + driver.getPageSource());

    waitForElementPresent("//UIAWindow/UIAStaticText[contains(value, 'All:')]");

    status = true;
    return status;
}

private boolean handleAlert() {
    boolean status = false;

    if(! waitForElementPresent("//UIAAlert/UIAStaticText")) {
        System.err.println("Failed to find the alert message");
        return status;
    }

    List<WebElement> labelTextList =  driver.findElements(By.xpath("//UIAAlert/UIAStaticText"));
    System.out.println("No. of label text list found as:" + labelTextList.size());
    for(WebElement staticText : labelTextList) {
        System.out.println("Element text found as:" + staticText.getAttribute("label"));
    }

    List<WebElement> btnListInAlert =  driver.findElements(By.xpath("//UIAAlert/UIAButton"));
    System.out.println("No. of buttons in alert found as:" + btnListInAlert.size());
    for(WebElement btnElement : btnListInAlert) {
        String strDisplayedTextInBtn = btnElement.getAttribute("label");
        System.out.println("Btn text found as:" + strDisplayedTextInBtn);
        if(strDisplayedTextInBtn.equalsIgnoreCase("ok")) {
            btnElement.click();
            status = true;
        }
    }


    return status;
}

private String readInputFromCommandLine() {


    /*
     BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

      String data = null;

      //  read the username from the command-line; need to use try/catch with the
      //  readLine() method
      try {
         data = br.readLine();
      } catch (IOException ioe) {
         System.out.println("IO error trying to read your name!");
         System.exit(1);
      }
      */
        try { 
            Thread.sleep(10000); 
        } catch(Exception e) { }
      return "";
}

private boolean handleConfirmation(String aOptionToSelect) {
    boolean status = false;

    if(! waitForElementPresent("//UIAAlert/UIAStaticText")) {
        System.err.println("Failed to find the confirmation message");
        return status;
    }

    List<WebElement> labelTextList =  driver.findElements(By.xpath("//UIAAlert/UIAStaticText"));
    System.out.println("No. of label text list found as:" + labelTextList.size());
    for(WebElement staticText : labelTextList) {
        System.out.println("Element text found as:" + staticText.getAttribute("label"));
    }

    List<WebElement> btnListInAlert =  driver.findElements(By.xpath("//UIAAlert/UIAButton"));
    System.out.println("No. of buttons in alert found as:" + btnListInAlert.size());
    for(WebElement btnElement : btnListInAlert) {
        String strDisplayedTextInBtn = btnElement.getAttribute("label");
        System.out.println("Btn text found as:" + strDisplayedTextInBtn);
        if(strDisplayedTextInBtn.equalsIgnoreCase(aOptionToSelect)) {
            btnElement.click();
            status = true;
        }
    }


    return status;
}

public String getWorkingDirectory() {
    URL location = SkyBoxAutomationDemo.class.getProtectionDomain().getCodeSource().getLocation();
    return location.getFile();
}

private void takeScreenshot(String aFile) {
    try {

         // take a screenshot using the normal selenium api.
        TakesScreenshot screen =(TakesScreenshot)new Augmenter().augment(driver);
        File ss = new File(aFile);
        screen.getScreenshotAs(OutputType.FILE).renameTo(ss);
        System.out.println("screenshot take :"+ ss.getAbsolutePath());
    } catch(Exception e) {

    }
}

public void test() {

    try {

        Assert.assertTrue(login(), "Failed to login");
        //Assert.assertTrue(verifyiForgot(), "Failed to verify iForgot");


    } catch(Exception e) {
        e.printStackTrace();
    } finally {
        teardown();
    }


}



public static void main(String[] args) throws Exception {

    SkyBoxAutomationDemo d = new SkyBoxAutomationDemo();
    d.test();   
}
```

}

**Comment by lukeis** [comment]
@saraav could you try again with 0.6 and let us know the results?

**Comment by freynaud** [comment]
no update. Probably fixed
