### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: there was an error.stderr is not empty

### ISSUE THREAD

**Issue by iboyarinov** [ios-driver/ios-driver#62]
I get this exception when try to start ios-server for both version 0.6.0 and 0.7.0

Exception in thread "main" org.openqa.selenium.WebDriverException: there was an error.stderr is not empty
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_21'
Driver info: driver.version: unknown
    at org.uiautomation.ios.utils.ShowSDKsPasrer.getSDKs(ClassicCommands.java:147)
    at org.uiautomation.ios.utils.ClassicCommands.getInstalledSDKs(ClassicCommands.java:108)
    at org.uiautomation.ios.utils.ClassicCommands.getDefaultSDK(ClassicCommands.java:113)
    at org.uiautomation.ios.server.HostInfo.<init>(HostInfo.java:45)
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:54)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:115)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:88)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:61)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:65)

**Comment by nicegraham** [comment]
Do you have xcode installed? The only place that error is thrown which I can see is when it's trying to return the list of available ios SDKs.

**Comment by iboyarinov** [comment]
Yes. XCode was installed before using ios-driver

xcodebuild -showsdks
2013-05-22 10:00:56.609 xcodebuild[7526:1207] XcodeColors: load (v10.1)
2013-05-22 10:00:56.611 xcodebuild[7526:1207] XcodeColors: pluginDidLoad:
OS X SDKs:
    Mac OS X 10.7                   -sdk macosx10.7
    OS X 10.8                       -sdk macosx10.8

iOS SDKs:
    iOS 6.1                         -sdk iphoneos6.1

iOS Simulator SDKs:
    Simulator - iOS 5.1             -sdk iphonesimulator5.1
    Simulator - iOS 6.0             -sdk iphonesimulator6.0
    Simulator - iOS 6.1             -sdk iphonesimulator6.1
