### ISSUE TITLE
cannot run simulator tests

### ISSUE THREAD

**Issue by sassda** [ios-driver/ios-driver#67]
for some reason I can't seem to run anything using the simulator, everything works fine on real device, but on simulator the simulator opens up and hangs and I get

2013-06-11 16:03:02.827:INFO::jetty-7.x.y-SNAPSHOT
2013-06-11 16:03:02.902:INFO::Started SelectChannelConnector@0.0.0.0:5555
05:40:933 WARNING IOSSimulatorManager.restoreExiledSDKs  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs doesn't exist.Cannot move folders from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/exiledSDKs Make sure the rights are correct (chmod -R +rw ... )

Any ideas?

**Comment by nicegraham** [comment]
It's a known issue in the latest code to do with the replacement of
instruments with libimobile, I think there's another couple of issues I the
same thing. Bear with us or revert to 0.6.0 for real device right now.

**Comment by sassda** [comment]
I should've specified, I am using 0.6.0 and the pb is for simulator only, it works good on real devices

**Comment by sassda** [comment]
some more precisions,
I also tried on 0.5.0 just in case.
Didn't solve it.
sometimes I get this message
47:36:918 WARNING DefaultCommandListener.stderr  2013-06-11 16:47:36.917 instruments[43058:e0b] Recording cancelled : At least one target failed to launch; aborting run
java.io.IOException: Bad file descriptor
    at java.io.FileInputStream.readBytes(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:220)
    at java.lang.UNIXProcess$DeferredCloseInputStream.read(UNIXProcess.java:227)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:264)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:306)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:158)
    at java.io.InputStreamReader.read(InputStreamReader.java:167)
    at java.io.BufferedReader.fill(BufferedReader.java:136)
    at java.io.BufferedReader.readLine(BufferedReader.java:299)
    at java.io.BufferedReader.readLine(BufferedReader.java:362)
    at org.uiautomation.ios.server.utils.Command$1.run(Command.java:118)
    at java.lang.Thread.run(Thread.java:680)

with a popup sayinf the simulator session timedout

**Comment by nicegraham** [comment]
What simulator are you asking for? If it's not the latest installed you'll
need to create the exiled sdk folder with appropriate permissions.

**Comment by sassda** [comment]
ok, so I cleaned up the whole thing and now it works, here is what I did.

deleted the "iPhone Simulator" folder contained in my 
"/Users/<My-User>/Library/Application Support"

then started the simulator tru Xcode.
then did the chmod -R +rw to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs

and now it works.
So its good for me, closing this issue then.
