### ISSUE TITLE
Inspector not showing

### ISSUE THREAD

**Issue by JUNGWOO-HWANG** [ios-driver/ios-driver#78]
When i go to the inspector on web browser, do something error on server console like this.

Driver info: driver.version: RemoteIOSDriver
    at org.uiautomation.ios.client.uiamodels.impl.configuration.WebDriverLikeCommandExecutor.execute(WebDriverLikeCommandExecutor.java:76)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.logElementTree(RemoteIOSDriver.java:286)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.logElementTree(RemoteIOSDriver.java:97)
    at org.uiautomation.ios.inspector.model.IDESessionModelImpl.refresh(IDESessionModelImpl.java:75)
    at org.uiautomation.ios.inspector.controllers.IDEController.handle(IDEController.java:43)
    at org.uiautomation.ios.inspector.IDEServlet.doGet(IDEServlet.java:95)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1049)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:680)
Caused by: org.openqa.selenium.WebDriverException: not a valid response 
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.6.0_51'

what problem is it.

my build info here:

  "value": {
    "build": {
      "revision": "7fc89bb6547d85a55c9ea7caabc50c9343c8be3a",
      "time": "20130327-1606",
      "version": "0.6.0"
    },
    "ios": {"simulatorVersion": "6.1"},
    "java": {"version": "1.6.0_51"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.7.5"
    },

**Comment by freynaud** [comment]
what URL are you trying to access ?

**Comment by nicegraham** [comment]
can you try this build https://github.com/ios-driver/ios-driver/releases/tag/0.6.2 and reopen if you still have problems. You should be able to connect to it when your application is break-pointed and on this url http://[server-ip]:4444/inspector/ 

The last "/" is important

**Comment by JUNGWOO-HWANG** [comment]
I'll try it. thanks
