### ISSUE TITLE
getPageSource returns timeout error

### ISSUE THREAD

**Issue by medwyn** [ios-driver/ios-driver#80]
I have a quite simple script in php which requests the source of a page on an iphone after some inline javascript to rewrite large sections of the page (this only takes a few seconds to run) has finished executing:

$webdriver = new WebDriver("localhost", "4444");
$webdriver->connect("iphone");
$webdriver->get($url);

// page runs a lot of javascript, but when finished sets the HTML title to 'ready'
while($webdriver->getTitle() != 'ready'){
    sleep(1);
}

$source =  $webdriver->getPageSource();
$webdriver->close();

This code runs fine on non-iOS webdriver e.g. Firefox (via selenium-server-standalone-2.33.0), but when running via iOS-driver, I get an error which seems related to a timeout - here is a dump of the getPageSource call below:

If I run the same test on the same URL (but without running the JS after the page has loaded), then I don't get this error.

I have tried extending the timeout on startup of ios-server e.g.

 java -jar ios-server-0.6.0.jar -sessionTimeout 18000

but this does not have any effect. As mentioned above, the script loaded when the page loads does not take very long to run at all - just a few seconds

Any thoughts on what the issue could be or how I can circumvent this?

As mentioned, it all works fine when testing on Firefox, so seems to be an issue in ios-driver???

Would be grateful for any advice

stdClass Object
(
    [message] => org.openqa.selenium.WebDriverException: timeout waiting for a response for request id : 13
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.2', java.version: '1.6.0_37'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.2', java.version: '1.6.0_37'
Driver info: driver.version: RemoteIOSWebDriver
    [screen] => 
    [cause] => stdClass Object
        (
            [message] => timeout waiting for a response for request id : 13
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.2', java.version: '1.6.0_37'
Driver info: driver.version: unknown
            [screen] => 
            [class] => org.openqa.selenium.WebDriverException
            [stackTrace] => Array
                (
                    [0] => stdClass Object
                        (
                            [fileName] => DefaultWebKitResponseFinder.java
                            [lineNumber] => 52
                            [className] => org.uiautomation.ios.wkrdp.internal.DefaultWebKitResponseFinder
                            [methodName] => startSearch
                        )

```
                [1] => stdClass Object
                    (
                        [fileName] => ResponseFinderList.java
                        [lineNumber] => 55
                        [className] => org.uiautomation.ios.wkrdp.ResponseFinderList$1
                        [methodName] => run
                    )

                [2] => stdClass Object
                    (
                        [fileName] => Thread.java
                        [lineNumber] => 680
                        [className] => java.lang.Thread
                        [methodName] => run
                    )

            )

    )

[class] => org.openqa.selenium.WebDriverException
[stackTrace] => Array
    (
        [0] => stdClass Object
            (
                [fileName] => BaseWebInspector.java
                [lineNumber] => 220
                [className] => org.uiautomation.ios.context.BaseWebInspector
                [methodName] => getPageSource
            )

        [1] => stdClass Object
            (
                [fileName] => RemoteIOSWebDriver.java
                [lineNumber] => 283
                [className] => org.uiautomation.ios.wkrdp.RemoteIOSWebDriver
                [methodName] => getPageSource
            )

        [2] => stdClass Object
            (
                [fileName] => GetPageSourceHandler.java
                [lineNumber] => 36
                [className] => org.uiautomation.ios.server.command.web.GetPageSourceHandler
                [methodName] => handle
            )

        [3] => stdClass Object
            (
                [fileName] => BaseCommandHandler.java
                [lineNumber] => 86
                [className] => org.uiautomation.ios.server.command.BaseCommandHandler
                [methodName] => handleAndRunDecorators
            )

        [4] => stdClass Object
            (
                [fileName] => IOSServlet.java
                [lineNumber] => 131
                [className] => org.uiautomation.ios.server.servlet.IOSServlet
                [methodName] => getResponse
            )

        [5] => stdClass Object
            (
                [fileName] => IOSServlet.java
                [lineNumber] => 82
                [className] => org.uiautomation.ios.server.servlet.IOSServlet
                [methodName] => process
            )

        [6] => stdClass Object
            (
                [fileName] => IOSServlet.java
                [lineNumber] => 45
                [className] => org.uiautomation.ios.server.servlet.IOSServlet
                [methodName] => doGet
            )

        [7] => stdClass Object
            (
                [fileName] => HttpServlet.java
                [lineNumber] => 707
                [className] => javax.servlet.http.HttpServlet
                [methodName] => service
            )

        [8] => stdClass Object
            (
                [fileName] => HttpServlet.java
                [lineNumber] => 820
                [className] => javax.servlet.http.HttpServlet
                [methodName] => service
            )

        [9] => stdClass Object
            (
                [fileName] => ServletHolder.java
                [lineNumber] => 533
                [className] => org.eclipse.jetty.servlet.ServletHolder
                [methodName] => handle
            )

        [10] => stdClass Object
            (
                [fileName] => ServletHandler.java
                [lineNumber] => 475
                [className] => org.eclipse.jetty.servlet.ServletHandler
                [methodName] => doHandle
            )

        [11] => stdClass Object
            (
                [fileName] => SessionHandler.java
                [lineNumber] => 224
                [className] => org.eclipse.jetty.server.session.SessionHandler
                [methodName] => doHandle
            )

        [12] => stdClass Object
            (
                [fileName] => ContextHandler.java
                [lineNumber] => 920
                [className] => org.eclipse.jetty.server.handler.ContextHandler
                [methodName] => doHandle
            )

        [13] => stdClass Object
            (
                [fileName] => ServletHandler.java
                [lineNumber] => 403
                [className] => org.eclipse.jetty.servlet.ServletHandler
                [methodName] => doScope
            )

        [14] => stdClass Object
            (
                [fileName] => SessionHandler.java
                [lineNumber] => 184
                [className] => org.eclipse.jetty.server.session.SessionHandler
                [methodName] => doScope
            )

        [15] => stdClass Object
            (
                [fileName] => ContextHandler.java
                [lineNumber] => 856
                [className] => org.eclipse.jetty.server.handler.ContextHandler
                [methodName] => doScope
            )

        [16] => stdClass Object
            (
                [fileName] => ScopedHandler.java
                [lineNumber] => 117
                [className] => org.eclipse.jetty.server.handler.ScopedHandler
                [methodName] => handle
            )

        [17] => stdClass Object
            (
                [fileName] => HandlerList.java
                [lineNumber] => 47
                [className] => org.eclipse.jetty.server.handler.HandlerList
                [methodName] => handle
            )

        [18] => stdClass Object
            (
                [fileName] => HandlerWrapper.java
                [lineNumber] => 114
                [className] => org.eclipse.jetty.server.handler.HandlerWrapper
                [methodName] => handle
            )

        [19] => stdClass Object
            (
                [fileName] => Server.java
                [lineNumber] => 352
                [className] => org.eclipse.jetty.server.Server
                [methodName] => handle
            )

        [20] => stdClass Object
            (
                [fileName] => HttpConnection.java
                [lineNumber] => 596
                [className] => org.eclipse.jetty.server.HttpConnection
                [methodName] => handleRequest
            )

        [21] => stdClass Object
            (
                [fileName] => HttpConnection.java
                [lineNumber] => 1049
                [className] => org.eclipse.jetty.server.HttpConnection$RequestHandler
                [methodName] => headerComplete
            )

        [22] => stdClass Object
            (
                [fileName] => HttpParser.java
                [lineNumber] => 590
                [className] => org.eclipse.jetty.http.HttpParser
                [methodName] => parseNext
            )

        [23] => stdClass Object
            (
                [fileName] => HttpParser.java
                [lineNumber] => 212
                [className] => org.eclipse.jetty.http.HttpParser
                [methodName] => parseAvailable
            )

        [24] => stdClass Object
            (
                [fileName] => HttpConnection.java
                [lineNumber] => 426
                [className] => org.eclipse.jetty.server.HttpConnection
                [methodName] => handle
            )

        [25] => stdClass Object
            (
                [fileName] => SelectChannelEndPoint.java
                [lineNumber] => 510
                [className] => org.eclipse.jetty.io.nio.SelectChannelEndPoint
                [methodName] => handle
            )

        [26] => stdClass Object
            (
                [fileName] => SelectChannelEndPoint.java
                [lineNumber] => 34
                [className] => org.eclipse.jetty.io.nio.SelectChannelEndPoint
                [methodName] => access$000
            )

        [27] => stdClass Object
            (
                [fileName] => SelectChannelEndPoint.java
                [lineNumber] => 40
                [className] => org.eclipse.jetty.io.nio.SelectChannelEndPoint$1
                [methodName] => run
            )

        [28] => stdClass Object
            (
                [fileName] => QueuedThreadPool.java
                [lineNumber] => 450
                [className] => org.eclipse.jetty.util.thread.QueuedThreadPool$2
                [methodName] => run
            )

        [29] => stdClass Object
            (
                [fileName] => Thread.java
                [lineNumber] => 680
                [className] => java.lang.Thread
                [methodName] => run
            )

    )
```

)

**Comment by freynaud** [comment]
Can you give the url of the page you're testing ? It's impossible to debug without the page under test.
-sessionTimeout 18000 is a different timeout. The webkit timeout isn't configurable.

**Comment by medwyn** [comment]
I am trying to create a page that I can host publicly in which I can isolate potentially where the problem is - stripping out any of the irrelevant code -I will respond here when I can do this. In the meantime, I notice that if the jar also throws some diagnostic information that could be useful:

ios >= 6.0. Safari and hybrid apps are supported.

## Applications :

```
CFBundleName=Safari,CFBundleVersion=8536.25
```

2013-07-29 22:22:15.317:INFO::jetty-7.x.y-SNAPSHOT
2013-07-29 22:22:15.469:INFO::Started SelectChannelConnector@0.0.0.0:5555
22:35:563 WARNING DefaultCommandListener.stderr  2013-07-29 22:22:35.562 ScriptAgent[39923:2f1f] -[ScriptAgent handleAlert:]: script status is 2
22:35:564 WARNING DefaultCommandListener.stderr  2013-07-29 22:22:35.563 ScriptAgent[39923:2f1f] -[ScriptAgent handleAlert:]: Calling onAlert
22:35:565 WARNING DefaultCommandListener.stderr  2013-07-29 22:22:35.564 ScriptAgent[39923:2f1f] -[ScriptAgent handleAlert:]: Call to onAlert returned 'YES'
22:40:863 WARNING DefaultCommandListener.stderr  2013-07-29 22:22:40.862 ScriptAgent[39923:2f1f] -[ScriptAgent handleAlert:]: script status is 2
22:40:863 WARNING DefaultCommandListener.stderr  2013-07-29 22:22:40.863 ScriptAgent[39923:2f1f] -[ScriptAgent handleAlert:]: Calling onAlert
22:40:864 WARNING DefaultCommandListener.stderr  2013-07-29 22:22:40.863 ScriptAgent[39923:2f1f] -[ScriptAgent handleAlert:]: Call to onAlert returned 'YES'
java.lang.NullPointerException
    at org.uiautomation.ios.wkrdp.message.BaseIOSWebKitMessage.<init>(BaseIOSWebKitMessage.java:17)
    at org.uiautomation.ios.wkrdp.message.MessageFactory.create(MessageFactory.java:37)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.process(DefaultMessageHandler.java:73)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler.access$000(DefaultMessageHandler.java:31)
    at org.uiautomation.ios.wkrdp.internal.DefaultMessageHandler$1.run(DefaultMessageHandler.java:64)
^C22:55:097 WARNING DefaultCommandListener.stderr  2013-07-29 22:22:55.094 instruments[39887:5707] Automation Instrument ran into an exception while trying to run the script.  UIAScriptAgentSignaledException
java.io.IOException: Bad file descriptor
    at java.io.FileInputStream.readBytes(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:220)
    at java.lang.UNIXProcess$DeferredCloseInputStream.read(UNIXProcess.java:227)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:264)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:306)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:158)
    at java.io.InputStreamReader.read(InputStreamReader.java:167)
    at java.io.BufferedReader.fill(BufferedReader.java:136)
    at java.io.BufferedReader.readLine(BufferedReader.java:299)
    at java.io.BufferedReader.readLine(BufferedReader.java:362)
    at org.uiautomation.ios.utils.Command$2.run(Command.java:135)
    at java.lang.Thread.run(Thread.java:680)
java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:145)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:255)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:317)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:264)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:306)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:158)
    at java.io.InputStreamReader.read(InputStreamReader.java:167)
    at java.io.BufferedReader.fill(BufferedReader.java:136)
    at java.io.BufferedReader.readLine(BufferedReader.java:299)
    at java.io.BufferedReader.readLine(BufferedReader.java:362)
    at org.uiautomation.ios.utils.Command$2.run(Command.java:135)
    at java.lang.Thread.run(Thread.java:680)
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:1961)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1996)
    at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:322)
    at org.uiautomation.ios.server.instruments.CommunicationChannel.getNextCommand(CommunicationChannel.java:69)
    at org.uiautomation.ios.server.servlet.UIAScriptServlet.getResponse(UIAScriptServlet.java:94)
    at org.uiautomation.ios.server.servlet.UIAScriptServlet.doPost(UIAScriptServlet.java:55)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:533)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
    at java.lang.Thread.run(Thread.java:680)

**Comment by medwyn** [comment]
Okay - I finally got back to this.

I have created the following file that it fails on: http://medwyn.pwp.blueyonder.co.uk/lipsum2.html

(Note that this page does not have any Javascript so it looks like we can eliminate that part of things).

However, I find that if I remove just one character then the problem did not occur.

I thought initially that it was related to file size, so I created a simpler (less HTML tags) file of the same length, but this worked fine. Hopefully you can reproduce the error with the above file
