### ISSUE TITLE
zh-Hans (simplified chinese) not supported?

### ISSUE THREAD

**Issue by djjwhw** [ios-driver/ios-driver#81]
Hi! I am trying to use ios-driver to test a native iOS app and when I try to run the app from command line (java -jar ios-server-0.5.0.jar -aut ~/Documents/build/Test.app -port 4444) I get an error saying Exception in thread "main" org.openqa.selenium.WebDriverException: no support for zh-Hans.

Exception in thread "main" org.openqa.selenium.WebDriverException: no support for zh-Hans
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.4', java.version: '1.6.0_45'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.application.AppleLocale.<init>(AppleLocale.java:86)
    at org.uiautomation.ios.server.application.LanguageDictionary.<init>(LanguageDictionary.java:54)
    at org.uiautomation.ios.server.application.IOSApplication.loadAllContent(IOSApplication.java:152)
    at org.uiautomation.ios.server.application.IOSApplication.<init>(IOSApplication.java:62)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:94)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:72)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:62)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:44)

Someone else had a similar problem (https://github.com/ios-driver/ios-driver/issues/9) but I cant use the same solution: I need to support simplified Chinese so I cant remove language supports. Is there any other solution?

Thanks!
Palas.

build": {
      "revision": "1ed497ad4dab6652dfa4dee201ed5e7100a934ea",
      "time": "20130130-2125",
      "version": "0.5.0"
    },

**Comment by nicegraham** [comment]
could you upgrade to 0.6.0? One of the apps we unit test against has zh-Hans and we don't have a problem. 
https://s3-eu-west-1.amazonaws.com/ios-driver/ios-server-0.6.0.jar

**Comment by djjwhw** [comment]
Was following the old page (http://freynaud.github.io/ios-driver/) which have the previous version (0.5.0) to dowload, sorry.

After try the new version I got this error:

46:36:647 WARNING AppleLocale.findBestLocale  zh-Hans isn't recognized.Please file a bug on github.You won't be able to start the app in that language.

**Comment by freynaud** [comment]
this is a bug. the language  + locale selection has to be redone.

**Comment by freynaud** [comment]
5ce50ea9df5e97635b888b85b69b3e7f95513c3b should fix it.

**Comment by freynaud** [comment]
please try with https://s3-eu-west-1.amazonaws.com/ios-driver/ios-server-0.7.13d8f4db88688b0b6d4e6581118e421025c40027.jar and reopen if that doesn'"t fix your issue.
