### ISSUE TITLE
Could not run the ios-driver jar file successfully

### ISSUE THREAD

**Issue by ranjithramachandran** [ios-driver/ios-driver#84]
Getting an error when I try to run the jar file

java -jar ios-server-0.5.0.jar -port 4444

Exception in thread "main" org.openqa.selenium.WebDriverException: there was an error.stderr is not empty

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'

System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_43'

Driver info: driver.version: IOSDriver

```
        at org.uiautomation.ios.server.utils.ShowSDKsPasrer.getSDKs(ClassicCommands.java:146)

        at org.uiautomation.ios.server.utils.ClassicCommands.getInstalledSDKs(ClassicCommands.java:107)

        at org.uiautomation.ios.server.utils.ClassicCommands.getDefaultSDK(ClassicCommands.java:112)

        at org.uiautomation.ios.server.HostInfo.<init>(HostInfo.java:45)

        at org.uiautomation.ios.server.IOSDriver.<init>(IOSDriver.java:51)

        at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:92)

        at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:72)

        at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:62)

        at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:44)
```

**Comment by nicegraham** [comment]
Can you update to the latest version, 0.6.0, please? It's linked on the
wiki page.

**Comment by ranjithramachandran** [comment]
thank you. let me download it and run it..

**Comment by ranjithramachandran** [comment]
getting the same error when running the newer version 0.6.0. 

Could you please let me know where we can find the class IOSCapabilities. Could not find such a class in Selenium class names http://selenium.googlecode.com/svn/trunk/docs/api/java/allclasses-noframe.html

**Comment by nicegraham** [comment]
The IOSCapabilities is just a wrapper on DesiredCapabilities to set the capabilitieswe need for ios-driver. The class is in our project, so if you want to use it you need to include ios-driver in the classpath. 

Alternatively you can just specify the capabilities needed in the normal way, for example:

DesiredCapabilities myCaps = new DesiredCapabilities(){{
    setCapability("device", "iphone");
    setCapability("language", "en");
    setCapability("locale", "en_GB");
    setCapability("CFBundleName", "your_app_name");
    setCapability("CFBundleVersion", "app version");
    setCapability("variation", "Regular");
    setCapability("simulator", true);
  }};

You can find IOSCapabilities here:
https://github.com/ios-driver/ios-driver/blob/dev/common/src/main/java/org/uiautomation/ios/IOSCapabilities.java?source=cc

 Are you running the code on a mac? do you have xcode installed?

**Comment by ranjithramachandran** [comment]
The test scripts are running on a windows machine remotely and connecting to the Mac where the ios-driver and the ios-simulator is running. Xcode is installed in the mac. And the selenium test script is in C# code.

**Comment by ghost** [comment]
I'm doing the same scenario with no major problems. One thing you need to have is xcode and I'd recommend installing command line tools. Try and open IOS Simulator manually or through xcode first (make sure it loads to the screen). Once that is done:

Use: sudo chmod 666 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator*.sdk/Applications/MobileSafari.app/Info.plist

Then use: java -jar ios-server-0.6.0.jar -port 5555 

Once it's open and running I use something like this in C#:

DesiredCapabilities capability = DesiredCapabilities.Android();
driver = new RemoteWebDriver(new Uri("http://<machost/IP>:5555/wd/hub"), capability, TimeSpan.FromMinutes(2));

Then something like this: driver.Navigate().GoToUrl("http://www.google.com");

**Comment by ranjithramachandran** [comment]
@jack090  I did follow the steps you have mentioned.
I verified if the command line tools are installed for XCode - and yes it is installed. ios simulator was opened.Then ran the sudo command 
After that I started the ios-server as mentioned but I am still getting the error while starting it. here is the error log
$ sudo chmod 666 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator*.sdk/Applications/MobileSafari.app/Info.plist

$ java -jar ios-server-0.6.0.jar -port 5555
Exception in thread "main" org.openqa.selenium.WebDriverException: there was an error.stderr is not empty
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_43'
Driver info: driver.version: unknown
    at org.uiautomation.ios.utils.ShowSDKsPasrer.getSDKs(ClassicCommands.java:147)
    at org.uiautomation.ios.utils.ClassicCommands.getInstalledSDKs(ClassicCommands.java:108)
    at org.uiautomation.ios.utils.ClassicCommands.getDefaultSDK(ClassicCommands.java:113)
    at org.uiautomation.ios.server.HostInfo.<init>(HostInfo.java:45)
    at org.uiautomation.ios.server.IOSServerManager.<init>(IOSServerManager.java:54)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:115)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:88)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:61)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:65)
$

**Comment by ghost** [comment]
Any reason you are using version .5 vs .6?

**Comment by ranjithramachandran** [comment]
sorry - i have updated the error for version 0.6.0

**Comment by ranjithramachandran** [comment]
here is error message for 0.6.0 version
$ sudo chmod 666 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator*.sdk/Applications/MobileSafari.app/Info.plist

$ java -jar ios-server-0.6.0.jar -port 5555
Exception in thread "main" org.openqa.selenium.WebDriverException: there was an error.stderr is not empty
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_43'
Driver info: driver.version: unknown
at org.uiautomation.ios.utils.ShowSDKsPasrer.getSDKs(ClassicCommands.java:147)
at org.uiautomation.ios.utils.ClassicCommands.getInstalledSDKs(ClassicCommands.java:108)
at org.uiautomation.ios.utils.ClassicCommands.getDefaultSDK(ClassicCommands.java:113)
at org.uiautomation.ios.server.HostInfo.(HostInfo.java:45)
at org.uiautomation.ios.server.IOSServerManager.(IOSServerManager.java:54)
at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:115)
at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:88)
at org.uiautomation.ios.server.IOSServer.(IOSServer.java:61)
at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:65)
$

**Comment by ghost** [comment]
I bet you don't have your java_home setup. I'm replying from my phone can get you exact command later. Also go to terminal and type java -version and make sure its showing at least 1.6

**Comment by ranjithramachandran** [comment]
the java version is 1.6.0_43

**Comment by ghost** [comment]
Have you checked the permissions on the folder you have the jar file in? Also don't have ios simulator open it will auto-open when you connect. Is your error appearing when you try and connect from your windows machine or when you are first loading ios-driver? 

Side note: I noticed i'm using 1.6.0._51 of java sdk and Xcode version 4.6.3

**Comment by ranjithramachandran** [comment]
The issue is occuring when i try to load the ios-driver using the command java -jar ios-server-0.6.0.jar -port 5555.

i have xcode 4.6.3 and the logged in user does have Read & Write permission on the folder which has Jar file.

**Comment by freynaud** [comment]
what happens when you type 
xcodebuild -showsdks
in the console ?

**Comment by ranjithramachandran** [comment]
gets an error
xcrun: Error: could not stat active Xcode path 'Volumes/XCode/Xcode.app/Contents/Developer',(No such file or directory)
looks like that's the root cause of the issue

**Comment by ranjithramachandran** [comment]
i ran this command sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

 and then started the server - the ios-driver started working ..
Thank you all for helping me fix this issue
