### ISSUE TITLE
OOM at com.dd.plist.BinaryPropertyListParser.doParse

### ISSUE THREAD

**Issue by ghost** [ios-driver/ios-driver#85]
Java(TM) SE Runtime Environment (build 1.6.0_51-b11-456-11M4508)

Running a test results in an java.lang.OutOfMemoryError. At this point, i'm trying to type some text to an input field. Obviously caused by a 3rd party component, perhaps an update or safer handling is required?

Exception in thread "Thread-42" java.lang.OutOfMemoryError: Java heap space
    at com.dd.plist.BinaryPropertyListParser.doParse(BinaryPropertyListParser.java:113)
    at com.dd.plist.BinaryPropertyListParser.parse(BinaryPropertyListParser.java:73)
    at org.uiautomation.ios.utils.PlistManager.plistBinaryToXml(PlistManager.java:92)
    at org.uiautomation.ios.wkrdp.internal.SimulatorProtocolImpl.pushInput(SimulatorProtocolImpl.java:99)
    at org.uiautomation.ios.wkrdp.internal.SimulatorProtocolImpl.read(SimulatorProtocolImpl.java:119)
    at org.uiautomation.ios.wkrdp.internal.WebKitRemoteDebugProtocol$1.run(WebKitRemoteDebugProtocol.java:72)
    at java.lang.Thread.run(Thread.java:680)

**Comment by bijoyv** [comment]
seems like it is better to have the user to take a look at the situation rather than ios-driver catches, it's completely beyond the driver I guess

**Comment by mach6** [comment]
please re-open if you have an update
