### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: no support for pt-PT

### ISSUE THREAD

**Issue by freynaud** [ios-driver/ios-driver#9]
Hey freynaud,

Thanks for the help earlier to get the InternationMountains app working. I am now trying to start the server on the app i am working on and i get the following error:

Jayeshs-MacBook-Pro:Downloads jayeshpatil$ java -jar ios-server-0.5.0.jar -aut ../Documents/TaggedIOSApps/Tagged.app/ -port 4444
Exception in thread "main" org.openqa.selenium.WebDriverException: no support for pt-PT
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.6.0_37'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.application.AppleLocale.<init>(AppleLocale.java:86)
    at org.uiautomation.ios.server.application.LanguageDictionary.<init>(LanguageDictionary.java:54)
    at org.uiautomation.ios.server.application.IOSApplication.loadAllContent(IOSApplication.java:152)
    at org.uiautomation.ios.server.application.IOSApplication.<init>(IOSApplication.java:62)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:94)
    at org.uiautomation.ios.server.IOSServer.init(IOSServer.java:72)
    at org.uiautomation.ios.server.IOSServer.<init>(IOSServer.java:62)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:44)

Any pointers?

**Comment by freynaud** [comment]
Hum. Apple isn't great for consistency. In all the example I've seen, it was pt_PT ( that's what safari has too ). Do you know how your project ended up with pt-PT instead of pt_PT ?

**Comment by freynaud** [comment]
When i start the server.

**Comment by freynaud** [comment]
ok. I'll write something to work around that. In the meantime, you should be able to unblcock the situation by going in your application.app, the one you specify when you start the server. Locate the pt-PT folder, and rename it to pt_PT.
That should work as a temporary workaround.

**Comment by freynaud** [comment]
Ah thanks.
I did that and seems like its now complaining for something else:
Exception in thread "main" org.openqa.selenium.WebDriverException: no support for zh-Hans

Though this time around, zh_Hans doesn't seem to help instead of zh-Hans.

**Comment by freynaud** [comment]
So i worked around it. I just deleted all the localization folders that had "-" in their names from my app and it works for now.

**Comment by freynaud** [comment]
glad you have it working. It's still not ideal though. Do you know where those - come from ? Was the app built a long time ago ?
I'd like to know if I need to write something to accept - as well as _, or if it's a edge case.
thanks,
françois

**Comment by freynaud** [comment]
Actually yes. The app was written a long time ago. A little over 2 years
back i suppose.

**Comment by freynaud** [comment]
fixed.
